### ISSUE TITLE
ndb.interfaces.values() raise KeyError: 'object does not exists'

### ISSUE THREAD

**Issue by fqucuo** [svinota/pyroute2#1059]
pyroute2: 0.7.3

Steps:
1. Create a vxlan interface
   ` ip link add enp3s0.4096 type vxlan id 4096 remote X.X.X.X dstport 4789 dev enp3s0`
2. Create some macvlan interfaces based on vxlan interface
   ` ip link add vif60 link enp3s0.4096 type macvlan`
3. Assign IPs
   ` ip address add x.x.x.x/x dev vif60 `
4. Set up macvlan interfaces
   ` ip link set vif60 up `
5. Write a simple code
```
import pyroute2
import logging
import time

while True:
    try:
        with pyroute2.NDB() as ndb:
            for v in ndb.interfaces.values():
                print(v)
    except Exception as e:
        logging.getLogger().exception(e)
    time.sleep(10)
```

7. Then wait a few minutes or hours

Results:
Sometimes a exception raised:
```
Traceback (most recent call last):
    for v in ndb.interfaces.values():
  File "/usr/local/lib/python3.7/dist-packages/pyroute2/ndb/view.py", line 399, in values
    yield self[key]
  File "/usr/local/lib/python3.7/dist-packages/pyroute2/ndb/auth_manager.py", line 67, in guard
    return f(obj, *argv, **kwarg)
  File "/usr/local/lib/python3.7/dist-packages/pyroute2/ndb/view.py", line 281, in __getitem__
    ret = self.template(key, table)
  File "/usr/local/lib/python3.7/dist-packages/pyroute2/ndb/view.py", line 173, in template
    auth_managers=self.auth_managers,
  File "/usr/local/lib/python3.7/dist-packages/pyroute2/ndb/objects/interface.py", line 546, in __init__
    super(Interface, self).__init__(*argv, **kwarg)
  File "/usr/local/lib/python3.7/dist-packages/pyroute2/ndb/objects/__init__.py", line 333, in __init__
    raise KeyError('object does not exists')
KeyError: 'object does not exists'
```

In debug mode, so far, always crash while key is a macvlan interface, in my production machine, i have many macvlan interfaces, not crash on same one, but always macvlan interface.

**Comment by ljluestc** [comment]
```

import pyroute2
import logging
import time

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

while True:
    try:
        with pyroute2.NDB() as ndb:
            # Safely iterate over interfaces
            for key in list(ndb.interfaces.keys()):
                try:
                    interface = ndb.interfaces[key]
                    # Print or process the interface
                    print(interface)
                except KeyError:
                    # Log the missing interface without crashing
                    logger.warning(f"Interface with key {key} does not exist.")
                except Exception as ex:
                    # Catch all other exceptions and log them
                    logger.exception(f"An error occurred while accessing interface {key}: {ex}")
    except Exception as e:
        logger.exception("An error occurred in the NDB context.")
    
    # Wait for a defined period before the next iteration
    time.sleep(10)

```
