### ISSUE TITLE
How set CONNMARK - NFTA_TARGET_INFO parameter

### ISSUE THREAD

**Issue by BlackSmith** [svinota/pyroute2#1072]
Hi,
I have a problem with setup firewall rule. 
`iptables -t mangle -A OUTPUT -j CONNMARK --restore-mark`

When I printed the firewall rules via pyroute2, I get this
```
...
'attrs': [('NFTA_RULE_TABLE', 'mangle'),
           ('NFTA_RULE_CHAIN', 'OUTPUT'),
           ('NFTA_RULE_HANDLE', 2),
           ('NFTA_RULE_EXPRESSIONS', [
            {'attrs': [('NFTA_EXPR_NAME', 'target'),
                       ('NFTA_EXPR_DATA', {'attrs': [
                           ('NFTA_TARGET_NAME', 'CONNMARK'),
                           ('NFTA_TARGET_REV', 2),
                           ('NFTA_TARGET_INFO', '00:00:00:00:ff:ff:ff:ff:ff:ff:ff:ff:00:00:02:00')
                           ]})]}])],
...
```

However, when I try to setup this firewall rule by pyroute2, I don't have lucky.
```
> from pyroute2.nftables.main import NFTables
> from pyroute2.nftables.expressions import genex

> conmark = genex('target', {'name': 'CONNMARK', 'rev': 2,  'info': '00:00:00:00:ff:ff:ff:ff:ff:ff:ff:ff:00:00:02:00'})
> print(conmark)
{'attrs': [('NFTA_EXPR_NAME', 'target'), ('NFTA_EXPR_DATA', {'attrs': [('NFTA_TARGET_NAME', 'CONNMARK'), ('NFTA_TARGET_REV', 2), ('NFTA_TARGET_INFO', '00:00:00:00:ff:ff:ff:ff:ff:ff:ff:ff:00:00:02:00')]})]}


> nft = NFTables(nfgen_family=2)
> nft.begin()

> nft.rule('add', table='mangle', chain='OUTPUT', expressions=(conmark, ) )
Traceback (most recent call last):
  File "/app/./test.py", line 30, in <module>
    nft.rule('add', table='mangle', chain='OUTPUT',
  File "/usr/local/lib/python3.9/site-packages/pyroute2/nftables/main.py", line 324, in rule
    return self._command(nft_rule_msg, commands, cmd, kwarg)
  File "/usr/local/lib/python3.9/site-packages/pyroute2/netlink/nfnetlink/nftsocket.py", line 1298, in _command
    self.nlm_request_batch(messages, noraise=(flags & NLM_F_ACK) == 0)
  File "/usr/local/lib/python3.9/site-packages/pyroute2/netlink/nlsocket.py", line 883, in nlm_request_batch
    return tuple(self._genlm_request_batch(*argv, **kwarg))
  File "/usr/local/lib/python3.9/site-packages/pyroute2/netlink/nlsocket.py", line 1174, in nlm_request_batch
    for msg in self.get(msg_seq=seq, noraise=noraise):
  File "/usr/local/lib/python3.9/site-packages/pyroute2/netlink/nlsocket.py", line 874, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/usr/local/lib/python3.9/site-packages/pyroute2/netlink/nlsocket.py", line 551, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (2, 'No such file or directory')
```

I guess, the problem is in `NFTA_TARGET_INFO`. I have tried to use hexadecimal numbers and bytes, but nothing works.
Which python format should I use for `NFTA_TARGET_INFO`?

**Comment by BlackSmith** [comment]
OK, OK, my mistake.

```python
> from pyroute2.nftables.main import NFTables
> from pyroute2.common import hexload
> from pyroute2.nftables.expressions import genex

> conmark = genex('target', {'name': 'CONNMARK', 'rev': 2,  'info': hexload('00:00:00:00:ff:ff:ff:ff:ff:ff:ff:ff:00:00:02:00')})
> print(conmark)
{'attrs': [('NFTA_EXPR_NAME', 'target'), ('NFTA_EXPR_DATA', {'attrs': [('NFTA_TARGET_NAME', 'CONNMARK'), ('NFTA_TARGET_REV', 2), ('NFTA_TARGET_INFO', b'\x00\x00\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x02\x00')]})]}


> nft = NFTables(nfgen_family=2)
> nft.begin()

> nft.rule('add', table='mangle', chain='OUTPUT', expressions=((conmark, ), ) )
```

The problem was with `expressions` attribute, it requires tuple in tuple (list in list).

**Comment by svinota** [comment]
Oh thanks. This part is missing documentation, and it's so complicated that I'm not sure how to start with :)

So thanks for such cases, they definitely will help me with documenting the NFTables API
