### ISSUE TITLE
IPRoute.get_links() throws "Permission denied: '/sys/class/net/lo/'" exception

### ISSUE THREAD

**Issue by kaiweifan** [svinota/pyroute2#113]
I was able to use IPRoute().get_links() without root privilege when using version 0.3.4. With 0.3.5 now I'm getting the following error unless I use root to run the python script.

ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/proxy.py", line 38, in handle
    ret = plugin(data, self.nl)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/rtnl/ifinfmsg.py", line 566, in proxy_linkinfo
    kind = get_interface_type(ifname)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/rtnl/ifinfmsg.py", line 937, in get_interface_type
    ifattrs = os.listdir('/sys/class/net/%s/' % (name))
OSError: [Errno 13] Permission denied: '/sys/class/net/lo/'

Traceback (most recent call last):
  File "t.py", line 6, in <module>
    links = netns.get_links()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/iproute.py", line 218, in get_links
    result.extend(self.nlm_request(msg, RTM_GETLINK, msg_flags))
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 758, in nlm_request
    ret = self.get(msg_seq=msg_seq, terminate=terminate)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 625, in get
    raise msg['header']['error']
pyroute2.netlink.NetlinkError: (13, 'Permission denied')

**Comment by svinota** [comment]
Oops. Thanks, will be fixed immediately.

**Comment by svinota** [comment]
Please, check if the fix will work for you — pushed to the master.

Corresponding test cases will be added later to the CI. Thanks again!

**Comment by kaiweifan** [comment]
Verified that get_links() works without root privilege with latest update. Thanks.
