### ISSUE TITLE
OVS create bridge issue on RHEL7

### ISSUE THREAD

**Issue by svinota** [svinota/pyroute2#141]
Traceback:
```
======================================================================
ERROR: test_ipdb.TestExplicit.test_create_ovs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/peet/Project/pyroute2/tests/test_ipdb.py", line 823, in test_create_ovs
    self._create_master('openvswitch')
  File "/home/peet/Project/pyroute2/tests/test_ipdb.py", line 776, in _create_master
    i.add_ip('172.16.0.1/24')
  File "/home/peet/Project/pyroute2/pyroute2/ipdb/transactional.py", line 199, in __exit__
    self.commit()
  File "/home/peet/Project/pyroute2/pyroute2/ipdb/interface.py", line 722, in commit
    raise error
CommitException: ports target is not set
```

System details:
```
$ rpm -qa | grep -i switch
openvswitch-2.3.1-2.el7.x86_64
$ uname -a
Linux rhel7-node1.kvm 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by svinota** [comment]
OVS support is dropped.
