### ISSUE TITLE
traceback from pyroute when adding vxlan device with ipv6 address

### ISSUE THREAD

**Issue by jtluka** [svinota/pyroute2#151]
```python
from pyroute2 import IPRSocket

# create the socket
ip = IPRSocket()

# bind
ip.bind()

# get and parse a broadcast message
ip.get()

# close
ip.close()
```

run following command:
```
ip link add vxlan0 type vxlan id 42 remote fe01::2 local fe01::1
```

traceback:
```
WARNING:root:decoding NDA_DST
WARNING:root:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/__init__.py", line 1132, in decode_nlas
    nla.decode()
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/__init__.py", line 1264, in decode
    self.value = socket.inet_ntop(family, self['value'])
ValueError: invalid length of packed IP address string
```

I'm using pyroute from git, commit acc833e9527823e4ce3f14cb3519b1fafc19b028

**Comment by svinota** [comment]
Really stupid bug. Thanks, fixin' it.

**Comment by svinota** [comment]
Should be fixed now. Thanks for reporting — and pls excuse for this bug.

**Comment by jtluka** [comment]
Checked with your patch. The issue is gone, thanks!
