### ISSUE TITLE
KeyboardInterrupt causes hang in NetNS child processes

### ISSUE THREAD

**Issue by drzaeus77** [svinota/pyroute2#156]
I have written the following test script that can be run interactively to show the bug:

```
from pyroute2 import IPRoute, IPDB, NetNS, NSPopen

ipr = IPRoute()
ipdb = IPDB(nl=ipr)

try:
    test = IPDB(nl=NetNS("testns"))
    test_ns = test.nl
    br100 = ipdb.create(ifname="br100", kind="bridge").commit()
    proc = NSPopen(test_ns.netns, ["sleep", "100"])

    input("Press ctrl-c to trigger bug:")
except KeyboardInterrupt:
    pass
finally:
    proc.kill()
    proc.release()
    test_ns.remove()
    test.release()
    br100.remove().commit()
    ipdb.release()
```

Run, and then ctrl-c at the prompt. It seems that KeyboardInterrupt is raised in the children before the parent, leaving the join dangling.

```
$ sudo python test_raise.py 
Press ctrl-c to trigger bug:^CProcess Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Process Process-2:
Traceback (most recent call last):
  File "/home/bblanco/work/pyroute2/pyroute2/netns/nslink.py", line 154, in NetNServer
    events = poll.poll()
KeyboardInterrupt
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bblanco/work/pyroute2/pyroute2/netns/process/proxy.py", line 49, in NSPopenServer
    call = channel_in.get()
  File "/usr/lib/python3.4/multiprocessing/queues.py", line 96, in get
    res = self._recv_bytes()
  File "/usr/lib/python3.4/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.4/multiprocessing/connection.py", line 416, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.4/multiprocessing/connection.py", line 383, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt


```
Pressing ctrl-c several more times halts the parent python, but the 'finally' block is never called.

**Comment by svinota** [comment]
Ok, got it. Will be fixed this weekend.

**Comment by svinota** [comment]
A bit more complicated task, sorry, so it takes some time.

**Comment by svinota** [comment]
The main issue remains in the IPDB. Unfortunately, it can not be fixed w/o a performance impact, as it requires me to use `get()` from `Queue` with non-zero timeout argument (so it can be interrupted safely), but it means that Python will turn on polling on the queue and will load CPU with meaningless activity.

Trying to find how to solve the issue in some more effective way.

**Comment by drzaeus77** [comment]
What if just the keyboard interrupt (SIGINT) is masked in the child processes. I expect that there are other types of exceptions that can be thrown in the child that will cause this race condition, and so a more complete fix may be required, but masking SIGINT might catch the common cases (at least for me).


```
diff --git a/pyroute2/netns/nslink.py b/pyroute2/netns/nslink.py
index 38d0d72..6fbd992 100644
--- a/pyroute2/netns/nslink.py
+++ b/pyroute2/netns/nslink.py
@@ -68,6 +68,7 @@ import os
 import errno
 import atexit
 import select
+import signal
 import struct
 import threading
 import traceback
@@ -126,6 +127,7 @@ def NetNServer(netns, rcvch, cmdch, flags=os.O_CREAT):
            implementations, but it is required by the protocol standard.
 
     '''
+    signal.signal(signal.SIGINT, signal.SIG_IGN)
     try:
         nsfd = setns(netns, flags)
     except OSError as e:
```

Let me know if that patch makes sense as a short term fix, and I will send a pull request.

**Comment by svinota** [comment]
It makes sense, but it doesn't help much, if we try it with your sample of the bug trigger. But as a general approach it looks not as bad.

**Comment by drzaeus77** [comment]
You're right, that patch has no effect on the test case mentioned. It did have some effect on a different use case (no process running in the netns), but this one still gets stuck. The search continues...

**Comment by drzaeus77** [comment]
Ahah!

With the combination of this patch and some more cleanup added in the test script, I am able to exit reliably.

```python
from pyroute2 import IPRoute, IPDB, NetNS, NSPopen

ipr = IPRoute()
ipdb = IPDB(nl=ipr)

try:
    test = IPDB(nl=NetNS("testns"))
    test_ns = test.nl
    br100 = ipdb.create(ifname="br100", kind="bridge").commit()
    proc = NSPopen(test_ns.netns, ["sleep", "100"])

    input("Press ctrl-c to trigger bug:")
except KeyboardInterrupt:
    pass
finally:
    if not proc.released:
        try:
            proc.kill()
            proc.wait()
        except:
            pass
        finally:
            proc.release()
    test_ns.remove()
    test.release()
    br100.remove().commit()
    ipdb.release()
```

**Comment by svinota** [comment]
Related issue: https://github.com/svinota/pyroute2/issues/211
