### ISSUE TITLE
With 4.1 rc7 kernel, WARNING:root:decoding IFLA_VXLAN_LOCAL

### ISSUE THREAD

**Issue by drzaeus77** [svinota/pyroute2#157]
Hi, I am getting the following error with the below test program. The 
device still gets created and functions properly.

```
WARNING:root:decoding IFLA_VXLAN_GROUP
WARNING:root:Traceback (most recent call last):
  File "/root/pyroute2/pyroute2/netlink/__init__.py", line 1133, in decode_nlas
    nla.decode()
  File "/root/pyroute2/pyroute2/netlink/__init__.py", line 1229, in decode
    self['value'])
ValueError: invalid length of packed IP address string

WARNING:root:decoding IFLA_VXLAN_LOCAL
WARNING:root:Traceback (most recent call last):
  File "/root/pyroute2/pyroute2/netlink/__init__.py", line 1133, in decode_nlas
    nla.decode()
  File "/root/pyroute2/pyroute2/netlink/__init__.py", line 1229, in decode
    self['value'])
ValueError: invalid length of packed IP address string
```

Test script:
```
from pyroute2 import IPDB
ip = IPDB()
try:
    ip.create(ifname="eth0a", kind="veth", peer="eth0b").commit()
    with ip.create(ifname="vxlan0", kind="vxlan", vxlan_id=10001,
                   vxlan_link=ip.interfaces.eth0a, vxlan_port=4789,
                   vxlan_group="239.1.1.1") as vx:
        vx.up()
    with ip.create(ifname="br100", kind="bridge") as br:
        br.add_port(ip.interfaces.vxlan0)
        br.up()

finally:
    if "vxlan0" in ip.interfaces: ip.interfaces.vxlan0.remove().commit()
    if "eth0a" in ip.interfaces: ip.interfaces.eth0a.remove().commit()
    if "br100" in ip.interfaces: ip.interfaces.br100.remove().commit()
    ip.release()
```

**Comment by svinota** [comment]
Got it, fixing.

**Comment by svinota** [comment]
Thanks for reporting, the library tried to handle 'IFLA_INFO_SLAVE_DATA' in a completely wrong way.

Pls check, if it works for you now.

**Comment by drzaeus77** [comment]
Works great! Thanks.
