### ISSUE TITLE
pyroute2 jams/freezes when manipulating a NetNS under Upstart after SIGTERM sent

### ISSUE THREAD

**Issue by Callum027** [svinota/pyroute2#211]
Got a somewhat perplexing issue, here.

Creating a network namespace, doing what you need, and removing the interfaces and the network namespace at the end of a run works fine, when just running the commands themselves.

However, this changes when you run a script using pyroute2 as a service through Upstart. When you do this, adding interfaces and namespaces work as normal in the startup process, but the moment the script gets a `SIGTERM` from `service stop {service}` and it tries to remove things, pyroute2 freezes on any calls to remove interfaces or release the IPDB. It works properly if you directly send it a `SIGTERM` using the `kill` command even if it was started by Upstart, so I thought there was nothing peculiar about the Upstart environment, but I have no idea how this could be happening.

[Here](https://github.com/svinota/pyroute2/files/116836/test-pyroute2.txt) is a test script which exhibits the issue, and [here](https://github.com/svinota/pyroute2/files/116839/test-pyroute2.upstart.txt) is an Upstart script for this script (it assumes the test script is placed at `/usr/local/sbin/test-pyroute2`, and the Upstart config itself should be placed at `/etc/init/test-pyroute2.conf`).

Given these test scripts, here is the expected total output for the script:

    root@ubuntu:~# test-pyroute2
    creating netns...
    creating netns IPDB...
    creating root IPDB...
    creating gre...
    comitting...
    created gre...
    adding address to gre...
    comitting...
    added address to gre...
    bringing up gre...
    comitting...
    brought up gre...
    setting signal handler...
    pausing...
    <SIGTERM sent via kill>
    unpaused...
    bringing down gre...
    comitting...
    brought down gre...
    removing gre...
    comitting...
    removed gre...
    releasing netns IPDB...
    closing netns...
    removing netns...
    releasing root IPDB...

And here is the actual output:

    root@ubuntu:~# tail -n0 -f /var/log/upstart/test-pyroute2.log
    creating netns...
    creating netns IPDB...
    creating root IPDB...
    creating gre...
    comitting...
    created gre...
    adding address to gre...
    comitting...
    added address to gre...
    bringing up gre...
    comitting...
    brought up gre...
    setting signal handler...
    pausing...
    <SIGTERM sent via service stop>
    unpaused...
    bringing down gre...
    comitting...

The call to `service test-pyroute2 stop` then goes on to wait for the required 30 seconds before sending a `SIGKILL` to the script to forcefully terminate it.

`supervisord` and regular `/etc/init.d` scripts do not exhibit this issue.

I've been testing this on Ubuntu 14.04 LTS, using both the 3.13.0 and 4.2.0 kernels.

Please let me know if you have any questions on this bug, and whether you'd like me to do additional testing or anything like that.

**Comment by svinota** [comment]
thanks, investigating

**Comment by Callum027** [comment]
Just been doing some more testing, looks like it affects any action made to the network namespace IPDB after the `SIGTERM` is sent from Upstart. I just moved the creation of the GRE tunnel to the `close()` function, and this is the result:

    root@ubuntu:~# tail -n0 -f /var/log/upstart/test-pyroute2.log 
    creating netns...
    creating netns IPDB...
    creating root IPDB...
    setting signal handler...
    pausing...
    <SIGTERM sent via service stop>
    unpaused...
    creating gre...
    comitting...

**Comment by svinota** [comment]
The root cause found.

To operate in a netns the library starts a child process upon `NetNS()` instantiation. When the upstart tries to stop the script, it kills not the parent process, but the child, and the parent waits forever.

To be fixed today, stay tuned.

**Comment by svinota** [comment]
Pls check if it will work for you.

**Comment by svinota** [comment]
UPD: not, it's not a proper fix. Update will follow

**Comment by svinota** [comment]
Pls try now. It looks a bit better, though some issues remain.

**Comment by Callum027** [comment]
Thanks for getting onto this bug so quickly, it looks like your changes have fixed the issue. :)

**Comment by Callum027** [comment]
On second thought, on one of the machines I'm testing this on, I got this error while the root IPDB tries to release itself:

    creating netns...
    creating netns IPDB...
    creating root IPDB...
    creating gre...
    comitting...
    created gre...
    adding address to gre...
    comitting...
    added address to gre...
    bringing up gre...
    comitting...
    brought up gre...
    setting signal handler...
    pausing...
    unpaused...
    bringing down gre...
    comitting...
    unpaused...
    bringing down gre...
    comitting...
    brought down gre...
    removing gre...
    comitting...
    removed gre...
    releasing netns IPDB...
    closing netns...
    removing netns...
    releasing root IPDB...
    Traceback (most recent call last):
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/ipdb/interface.py", line 640, in commit
        self.nl.link('set', **request)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/iproute.py", line 704, in link
        exception_handler=update_caps)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/netlink/nlsocket.py", line 783, in nlm_request
        return do_try()
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/netlink/nlsocket.py", line 761, in do_try
        self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/netlink/nlsocket.py", line 537, in put
        self.sendto(msg.buf.getvalue(), addr)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/netlink/nlsocket.py", line 469, in sendto
        return self._sendto(*argv, **kwarg)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/remote/__init__.py", line 296, in _sendto
        return Client.sendto(self, *argv, **kwarg)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/remote/__init__.py", line 277, in sendto
        return self.proxy('sendto', *argv, **kwarg)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/remote/__init__.py", line 258, in proxy
        'kwarg': kwarg})
      File "/usr/lib/python3.4/multiprocessing/connection.py", line 204, in send
        self._check_closed()
      File "/usr/lib/python3.4/multiprocessing/connection.py", line 136, in _check_closed
        raise OSError("handle is closed")
    OSError: handle is closed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/ipdb/interface.py", line 508, in commit
        self.nl.link('add', **request)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/iproute.py", line 704, in link
        exception_handler=update_caps)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/netlink/nlsocket.py", line 783, in nlm_request
        return do_try()
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/netlink/nlsocket.py", line 761, in do_try
        self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/netlink/nlsocket.py", line 537, in put
        self.sendto(msg.buf.getvalue(), addr)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/netlink/nlsocket.py", line 469, in sendto
        return self._sendto(*argv, **kwarg)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/remote/__init__.py", line 296, in _sendto
        return Client.sendto(self, *argv, **kwarg)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/remote/__init__.py", line 277, in sendto
        return self.proxy('sendto', *argv, **kwarg)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/remote/__init__.py", line 258, in proxy
        'kwarg': kwarg})
      File "/usr/lib/python3.4/multiprocessing/connection.py", line 204, in send
        self._check_closed()
      File "/usr/lib/python3.4/multiprocessing/connection.py", line 136, in _check_closed
        raise OSError("handle is closed")
    OSError: handle is closed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/ipdb/__init__.py", line 895, in commit
        target.commit(transaction=tx, rollback=rollback)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/ipdb/interface.py", line 774, in commit
        newif=newif)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/ipdb/interface.py", line 546, in commit
        self.detach()
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/ipdb/interface.py", line 124, in detach
        self.ipdb.detach(self['ifname'], self['index'], self.nlmsg)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/ipdb/__init__.py", line 989, in detach
        target = self.interfaces[idx]
    KeyError: 4

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/sbin/test-pyroute2", line 69, in <module>
        signal.pause()
      File "/usr/local/sbin/test-pyroute2", line 14, in close
        ipdb.commit()
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/ipdb/__init__.py", line 909, in commit
        target.drop(tx)
      File "/opt/l3overlay-virtualenv/lib/python3.4/pyroute2/ipdb/transactional.py", line 364, in drop
        self._tids.remove(tid)
    ValueError: list.remove(x): x not in list

It seems like it is related to the issue we're having here.

**Comment by Callum027** [comment]
Here is another example from a clean test VM, using the latest revision which addressed this issue. Ubuntu 14.04 LTS x64, kernel 4.2.0-27-generic.

    root@ubuntu:~# pip3 list | grep pyroute2
    pyroute2 (0.3.15.post34)
    root@ubuntu:~# touch /var/log/upstart/test-pyroute2.log && tail -n0 -f /var/log/upstart/test-pyroute2.log
    creating netns...
    creating netns IPDB...
    creating root IPDB...
    creating gre...
    comitting...
    created gre...
    adding address to gre...
    comitting...
    added address to gre...
    bringing up gre...
    comitting...
    brought up gre...
    setting signal handler...
    pausing...
    unpaused...
    bringing down gre...
    comitting...
    Traceback (most recent call last):
      File "/usr/local/sbin/test-pyroute2", line 69, in <module>
        signal.pause()
      File "/usr/local/sbin/test-pyroute2", line 13, in close
        print("comitting...")
      File "/usr/local/sbin/test-pyroute2", line 10, in close
        print("unpaused...")
    RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

Seems like the fixes aren't very robust. I'm getting inconsistent results depending on the machine I try it on...

**Comment by svinota** [comment]
Yep. Pardonnez-moi, I'm continuing with the investigation.

**Comment by svinota** [comment]
Related issue: https://github.com/svinota/pyroute2/issues/156

**Comment by svinota** [comment]
in the case of error the sample script starts not one, but two signal handlers:
```
creating netns...
creating netns IPDB...
creating root IPDB...
creating gre...
comitting...
created gre...
adding address to gre...
comitting...
added address to gre...
bringing up gre...
comitting...
brought up gre...
setting signal handler...
pausing...
--> signal handler
unpaused...
bringing down gre...
--> signal handler
```

Adding a lock to the signal handler **doesn't** fix the issue, so the root cause should be somewhere in the IPDB. Continuing to investigate.

**Comment by svinota** [comment]
Traces after the second handler started.

```
creating netns...
creating netns IPDB...
creating root IPDB...
creating gre...
comitting...
created gre...
adding address to gre...
comitting...
added address to gre...
bringing up gre...
comitting...
brought up gre...
setting signal handler...
pausing...
--> signal handler
unpaused...
bringing down gre...
comitting...
--> signal handler
Thread 0x-4a4004c0
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/__init__.py", line 1126, in serve_forever
    messages = self.nl.get()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 676, in get
    data = self.recv(bufsize)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/rtnl/iprsocket.py", line 106, in recv
    data = self._recv(bufsize, flags)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 840, in recv_plugin
    data = self.buffer_queue.get()
  File "/usr/lib/python2.7/Queue.py", line 168, in get
    self.not_empty.wait()
  File "/usr/lib/python2.7/threading.py", line 339, in wait
    waiter.acquire()
()
Thread 0x-49a004c0
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 479, in async_recv
    events = poll.poll()
()
Thread 0x-4903b4c0
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/__init__.py", line 1126, in serve_forever
    messages = self.nl.get()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 676, in get
    data = self.recv(bufsize)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 471, in recv
    return self._recv(*argv, **kwarg)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/remote/__init__.py", line 343, in _recv
    return Client.recv(self, *argv, **kwarg)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/remote/__init__.py", line 277, in recv
    msg = self.brdch.recv()
()
Thread 0x-48a93900
  File "/usr/local/sbin/test-pyroute2", line 74, in <module>
    signal.pause()
  File "/usr/local/sbin/test-pyroute2", line 18, in close
    print("comitting...")
  File "/usr/local/sbin/test-pyroute2", line 14, in close
    with close_lock:
  File "<string>", line 1, in <module>
  File "<string>", line 5, in <module>
()
```

**Comment by svinota** [comment]
So, finally it's not IPDB that is the root cause. Every next signal handler, being launched, effectively freezes the previous one.

The `threading.Lock` doesn't help at all in such race.

So the **only** solution is to call `signal.signal(signal.SIGTERM, signal.SIG_IGN)` as the very first statement of the signal handler.

**Comment by svinota** [comment]
Pls check if the solution will work for you. Unfortunately, it can not be generalized at the library level (it is the signal handlers behaviour in Python), but I will add it to the docs.

**Comment by Callum027** [comment]
Sorry for the late response. I'm having issues running pyroute2 ever since commit 9847e81 and that precludes me from testing this bug, but I'll make a separate issue for that.

**Comment by svinota** [comment]
Ough. Sorry for that, will fix immediately.

**Comment by Callum027** [comment]
Thanks for fixing that quickly. Unfortunately I'm still getting this error when closing it.

    root@ubuntu:~# tail -n0 -f /var/log/upstart/test-pyroute2.log
    creating netns...
    creating netns IPDB...
    creating root IPDB...
    creating gre...
    comitting...
    created gre...
    adding address to gre...
    comitting...
    added address to gre...
    bringing up gre...
    comitting...
    brought up gre...
    setting signal handler...
    pausing...
    unpaused...
    bringing down gre...
    comitting...
    unpaused...
    bringing down gre...
    comitting...
    brought down gre...
    removing gre...
    comitting...
    removed gre...
    releasing netns IPDB...
    closing netns...
    removing netns...
    releasing root IPDB...
    Traceback (most recent call last):
      File "/usr/lib/python3.4/pyroute2/ipdb/interface.py", line 640, in commit
        self.nl.link('set', **request)
      File "/usr/lib/python3.4/pyroute2/iproute.py", line 694, in link
        exception_handler=update_caps)
      File "/usr/lib/python3.4/pyroute2/netlink/nlsocket.py", line 773, in nlm_request
        return do_try()
      File "/usr/lib/python3.4/pyroute2/netlink/nlsocket.py", line 751, in do_try
        self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
      File "/usr/lib/python3.4/pyroute2/netlink/nlsocket.py", line 532, in put
        self.sendto_gate(msg, addr)
      File "/usr/lib/python3.4/pyroute2/remote/__init__.py", line 268, in _gate
        'kwarg': None})
      File "/usr/lib/python3.4/multiprocessing/connection.py", line 204, in send
        self._check_closed()
      File "/usr/lib/python3.4/multiprocessing/connection.py", line 136, in _check_closed
        raise OSError("handle is closed")
    OSError: handle is closed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.4/pyroute2/ipdb/interface.py", line 508, in commit
        self.nl.link('add', **request)
      File "/usr/lib/python3.4/pyroute2/iproute.py", line 694, in link
        exception_handler=update_caps)
      File "/usr/lib/python3.4/pyroute2/netlink/nlsocket.py", line 773, in nlm_request
        return do_try()
      File "/usr/lib/python3.4/pyroute2/netlink/nlsocket.py", line 751, in do_try
        self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
      File "/usr/lib/python3.4/pyroute2/netlink/nlsocket.py", line 532, in put
        self.sendto_gate(msg, addr)
      File "/usr/lib/python3.4/pyroute2/remote/__init__.py", line 268, in _gate
        'kwarg': None})
      File "/usr/lib/python3.4/multiprocessing/connection.py", line 204, in send
        self._check_closed()
      File "/usr/lib/python3.4/multiprocessing/connection.py", line 136, in _check_closed
        raise OSError("handle is closed")
    OSError: handle is closed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.4/pyroute2/ipdb/__init__.py", line 895, in commit
        target.commit(transaction=tx, rollback=rollback)
      File "/usr/lib/python3.4/pyroute2/ipdb/interface.py", line 774, in commit
        newif=newif)
      File "/usr/lib/python3.4/pyroute2/ipdb/interface.py", line 546, in commit
        self.detach()
      File "/usr/lib/python3.4/pyroute2/ipdb/interface.py", line 124, in detach
        self.ipdb.detach(self['ifname'], self['index'], self.nlmsg)
      File "/usr/lib/python3.4/pyroute2/ipdb/__init__.py", line 989, in detach
        target = self.interfaces[idx]
    KeyError: 4

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/sbin/test-pyroute2", line 69, in <module>
        signal.pause()
      File "/usr/local/sbin/test-pyroute2", line 14, in close
        ipdb.commit()
      File "/usr/lib/python3.4/pyroute2/ipdb/__init__.py", line 909, in commit
        target.drop(tx)
      File "/usr/lib/python3.4/pyroute2/ipdb/transactional.py", line 364, in drop
        self._tids.remove(tid)
    ValueError: list.remove(x): x not in list

Did you make any changes to the test script/configuration that I might have to make as well?

**Comment by svinota** [comment]
Here are the test system details:
```
root@ubuntu:~# uname -a
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:18:00 UTC 2015 i686 i686 i686 GNU/Linux
root@ubuntu:~# cat /etc/debian_version 
jessie/sid
root@ubuntu:~# dpkg -l | grep upstart
ii  upstart                              1.12.1-0ubuntu4.2                i386         event-based init daemon
root@ubuntu:~# python3 -V
Python 3.4.3
```
The modified script: [test-pyroute2.gz](https://github.com/svinota/pyroute2/files/168172/test-pyroute2.gz)

The `pyroute2` library — the current master.

And it looks like it is working.

But I will check again the code that is in your traces.

**Comment by Callum027** [comment]
Doh. Sorry, I forgot to add `signal.signal(signal.SIGTERM, signal.SIG_IGN)`, like you said. Sorry about that.

Everything works now. Thanks for your hard work with this barrages of issues, svinota.

**Comment by svinota** [comment]
Cool :) Thank you!
