### ISSUE TITLE
ERROR:root:Restarting IPDB instance after error:... when creating tun/tap interface in NetNS

### ISSUE THREAD

**Issue by Callum027** [svinota/pyroute2#219]
[Test script](https://github.com/svinota/pyroute2/files/141716/test3.py.txt). This works in the root namespace, but not in the network namespace (switch it by changing the value assignment of `foo_ipdb`).

Expected output:

    root@ubuntu:~# ./test3.py
    setting up NetNS for foo
    setting up IPDB for foo
    setting up NetNS for bar
    setting up IPDB for foo
    creating testtap0 on foo
    committing to foo_ipdb
    creating testtun0 on foo
    committing to foo_ipdb
    setting testtap0 netns to bar
    committing to foo_ipdb
    setting testtun0 netns to bar
    committing to foo_ipdb
    fetching testtap0 from bar
    fetching testtun0 from bar
    adding 172.16.0.1/24 to testtap0 on bar
    committing to bar_ipdb
    adding 172.16.0.2/24 to testtun0 on bar
    committing to bar_ipdb
    bringing up testtap0 on bar
    committing to bar_ipdb
    bringing up testtun0 on bar
    committing to bar_ipdb
    bringing down testtap0 on bar
    committing to bar_ipdb
    bringing down testtun0 on bar
    committing to bar_ipdb
    removing testtap0 on bar
    committing to bar_ipdb
    removing testtun0 on bar
    committing to bar_ipdb
    running testtap0 non-existence assert in bar_ipdb
    running testtun0 non-existence assert in bar_ipdb
    closing IPDB for foo
    releasing NetNS for foo
    removing netns foo
    releasing IPDB for foo
    closing NetNS for bar
    removing netns bar

Actual output:

    root@ubuntu:~# ./test3.py
    setting up NetNS for foo
    setting up IPDB for foo
    setting up NetNS for bar
    setting up IPDB for foo
    creating testtap0 on foo
    committing to foo_ipdb
    ERROR:root:Restarting IPDB instance after error:
    Traceback (most recent call last):
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/ipdb/__init__.py", line 1126, in serve_forever
        messages = self.nl.get()
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 676, in get
        data = self.recv(bufsize)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 471, in recv
        return self._recv(*argv, **kwarg)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/remote/__init__.py", line 329, in _recv
        return Client.recv(self, *argv, **kwarg)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/remote/__init__.py", line 264, in recv
        if msg['stage'] == 'signal':
    TypeError: byte indices must be integers, not str

    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/ipdb/__init__.py", line 1126, in serve_forever
        messages = self.nl.get()
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 676, in get
        data = self.recv(bufsize)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 471, in recv
        return self._recv(*argv, **kwarg)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/remote/__init__.py", line 329, in _recv
        return Client.recv(self, *argv, **kwarg)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/remote/__init__.py", line 264, in recv
        if msg['stage'] == 'signal':
    TypeError: byte indices must be integers, not str

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.4/threading.py", line 868, in run
        self._target(*self._args, **self._kwargs)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/ipdb/__init__.py", line 1148, in serve_forever
        raise RuntimeError('Emergency shutdown')
    RuntimeError: Emergency shutdown

Despite the error, the interface actually gets created:

    root@ubuntu:~# ip netns exec foo ip link list
    1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default 
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    2: testtap0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 500
        link/ether 92:19:a3:c4:f9:62 brd ff:ff:ff:ff:ff:ff

**Comment by svinota** [comment]
Fixed. Thanks for the report.

**Comment by Callum027** [comment]
Yep. Confirmed fixed here. Thanks for getting onto that so quickly.
