### ISSUE TITLE
ImportError: No module named 'cls_fw'

### ISSUE THREAD

**Issue by Callum027** [svinota/pyroute2#225]
Got this issue when testing fixes for #211. It looks like it was introduced in commit 9847e81, with the introduction of tc plugins.

    root@ubuntu:~# /usr/local/sbin/test-pyroute2
    creating netns...
    Traceback (most recent call last):
      File "/usr/local/sbin/test-pyroute2", line 39, in <module>
        nl = NetNS('test')
      File "/usr/lib/python3.4/pyroute2/__init__.py", line 90, in __new__
        cls.register(cls.registry['class'])
      File "/usr/lib/python3.4/pyroute2/__init__.py", line 70, in __getitem__
        [name], 0)
      File "/usr/lib/python3.4/pyroute2/netns/nslink.py", line 74, in <module>
        from pyroute2.netlink.rtnl.iprsocket import MarshalRtnl
      File "/usr/lib/python3.4/pyroute2/netlink/rtnl/iprsocket.py", line 9, in <module>
        from pyroute2.netlink.rtnl.tcmsg import tcmsg
      File "/usr/lib/python3.4/pyroute2/netlink/rtnl/tcmsg/__init__.py", line 6, in <module>
        import cls_fw
    ImportError: No module named 'cls_fw'

**Comment by svinota** [comment]
The code somehow missed tests with Python3 :| sorry for that. Fixed.

**Comment by Callum027** [comment]
Yep, it works now. Thanks.
