### ISSUE TITLE
How to create an unreachable route ?

### ISSUE THREAD

**Issue by tmmorin** [svinota/pyroute2#235]
I'm trying this:

`>>> ipdb.routes.add(dst='default', table=1001, rtype='RTN_UNREACHABLE').commit()`

But it fails:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/route.py", line 227, in commit
    self.ipdb.update_routes(self.nl.route('add', **transaction))
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/iproute.py", line 1512, in route
    ret = self.nlm_request(msg, msg_type=command, msg_flags=flags)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 774, in nlm_request
    return do_try()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 753, in do_try
    ret = self.get(msg_seq=msg_seq, terminate=terminate)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 618, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (19, 'No such device')
```

Is this a bug or should I be doing something different ?

**Comment by svinota** [comment]
```
ip.route('add', table=1001, type='unreachable')
```

Docs, docs, docs… :|

**Comment by tmmorin** [comment]
Thanks.
Is there a working equivalent in IPDB() ?

The following does not work:
```
        ip.routes.add({'dst': 'default',
                           'table': self.rt_table,
                           'type': 'unreachable'}).commit()

```
Result:
```
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/route.py", line 227, in commit
    self.ipdb.update_routes(self.nl.route('add', **transaction))
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/iproute.py", line 1512, in route
    ret = self.nlm_request(msg, msg_type=command, msg_flags=flags)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 774, in nlm_request
    return do_try()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 753, in do_try
    ret = self.get(msg_seq=msg_seq, terminate=terminate)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 618, in get
    raise msg['header']['error']
NetlinkError: (19, 'No such device')

```

**Comment by svinota** [comment]
No, in IPDB it [was] not possible — routes management there is very rudimental yet. Shortly will commit the fix.

Thanks for you patience.

**Comment by svinota** [comment]
Should be fixed now. Syntax:
```
from pyroute2 import IPDB

with IPDB() as ip:
    ip.routes.add({'dst': 'default',
                   'table': 202,
                   'type': 'unreachable'}).commit()
    ip.routes.add(dst='default',
                  table=3050,
                  type='blackhole').commit()
```

**Comment by tmmorin** [comment]
Thanks.
I've incorporated the IPDB variant, and it works fine.

**Comment by svinota** [comment]
Thanks!
