### ISSUE TITLE
Issue when removing a route from a specific table with IPDB

### ISSUE THREAD

**Issue by tmmorin** [svinota/pyroute2#239]
I'm trying to remove a route from a specific routing table, with:

with ip.routes.get('1.2.3.4/32', 42) as r:
     r.remove()

And I get the following:

```
  File "/opt/bagpipe-bgp/bagpipe/bgp/vpn/ipvpn/mpls_linux_dataplane.py", line 310, in removeDataplaneForRemoteEndpoint
    r.remove()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/transactional.py", line 230, in __exit__
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/route.py", line 227, in commit
    self.ipdb.update_routes(self.nl.route('add', **transaction))
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/iproute.py", line 1512, in route
    ret = self.nlm_request(msg, msg_type=command, msg_flags=flags)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 774, in nlm_request
    return do_try()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 753, in do_try
    ret = self.get(msg_seq=msg_seq, terminate=terminate)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 618, in get
    raise msg['header']['error']
NetlinkError: (17, 'File exists')
```

The 'File exists' along with the "    self.ipdb.update_routes(self.nl.route('add', **transaction))" in the trace are suspicious.

But maybe I'm not doing the right thing to remove this route...

**Comment by svinota** [comment]
No, that's a bug.

**Comment by svinota** [comment]
Ough, I didn't notice «a specific routing table». Probably, that's what you want:
```
with ipdb.routes.tables[42]['1.2.3.4/32'] as r:
    r.remove()
```

The issue with `self.ipdb.update_routes(self.nl.route('add', **transaction))` is a… let's say, a consequence of a «feature», but now I see that it's so confusing, so should be treated as bug.

**Comment by svinota** [comment]
… no. Really. Can not reproduce. Let's say, I have table `42`, so `routes.get(1.2.3.4/32', 42)` also should work, and it works in my case. Then: if the route exists, it will be removed. If no, there will be:
```
$ sudo python p.py
Traceback (most recent call last):
  File "p.py", line 4, in <module>
    with ip.routes.get('1.2.3.4/32', 42) as r:
  File "/home/peet/Projects/pyroute2/pyroute2/ipdb/route.py", line 564, in get
    return self.tables[table][dst]
  File "/home/peet/Projects/pyroute2/pyroute2/ipdb/route.py", line 459, in __getitem__
    return self.describe(key, forward=False)['route']
  File "/home/peet/Projects/pyroute2/pyroute2/ipdb/route.py", line 400, in describe
    raise KeyError('record not found')
KeyError: 'record not found'
```

Could you please describe the setup in more details — the better is with `ip route` output (if it is not a secret), or any other clue how to reproduce the error?

**Comment by svinota** [comment]
(just in case — do we talk about the master, or a release?)

**Comment by tmmorin** [comment]
I'm working with master.

**Comment by tmmorin** [comment]
The route setup is the following:
```
lnx01:~# ip route show table 1001
unreachable default  proto static 
broadcast 12.11.11.0 dev tons-test2  proto kernel  scope link  src 12.11.11.254 
12.11.11.0/24 dev tons-test2  proto kernel  scope link  src 12.11.11.254 
local 12.11.11.254 dev tons-test2  proto kernel  scope host  src 12.11.11.254 
broadcast 12.11.11.255 dev tons-test2  proto kernel  scope link  src 12.11.11.254 
14.11.11.4  encap mpls  165 via 192.168.177.102 dev eth1  proto static
```

Then the following code is run:
```
              with self.ip.routes.get(repr(prefix), self.rt_table) as r:
                   r.remove()
```
with self.rt_table = 1001, and prefix = 14.11.11.4 (self.ip is an IPDB instance)

And I get:

```
  File "/opt/bagpipe-bgp/bagpipe/bgp/vpn/ipvpn/mpls_linux_dataplane.py", line 301, in removeDataplaneForRemoteEndpoint
    r.remove()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/transactional.py", line 230, in __exit__
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/route.py", line 225, in commit
    self.ipdb.update_routes(self.nl.route('add', **transaction))
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/iproute.py", line 1512, in route
    ret = self.nlm_request(msg, msg_type=command, msg_flags=flags)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 774, in nlm_request
    return do_try()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 753, in do_try
    ret = self.get(msg_seq=msg_seq, terminate=terminate)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 618, in get
    raise msg['header']['error']
NetlinkError: (17, 'File exists')
```

**Comment by tmmorin** [comment]
I get the same result when using:

`            with self.ip.routes.tables[self.rt_table][repr(prefix)] as r:`

**Comment by svinota** [comment]
Thanks. Investigating.

**Comment by svinota** [comment]
I had to rewrite almost from scratch the logic behind `metrics` and `encap`. Not sure it will fix the issue, but it was required to continue the work on it.

Pls try now and post the backtrace, if there will be some.

**Comment by tmmorin** [comment]
Solved !
Many thanks!

**Comment by svinota** [comment]
Good. Thanks for patience.
