### ISSUE TITLE
TypeError exception throw when call tc with command 'add-filter' on PandoraBox(openwrt) 

### ISSUE THREAD

**Issue by coderzh** [svinota/pyroute2#247]
I wrote this test code: 

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pyroute2 import IPRoute
from pyroute2.protocols import ETH_P_IP
from pyroute2.netlink import NetlinkError
from pyroute2.netlink.rtnl import TC_H_ROOT

ipr = IPRoute()
dev = ipr.link_lookup(ifname='eth0')[0]

try:
    ipr.tc('add', 'htb', dev, 0x10000, default=2)
except NetlinkError as e:
    if e.code == 17:
        print('root htb already exist')
    else:
        raise

try:
    ipr.tc('add-class', 'htb', dev, 0x10001, parent=0x10000, rate='100mbit', ceil='100mbit')
except NetlinkError as e:
    if e.code == 17:
        print('add class 0x10001 already exist')
    else:
        raise

try:
    # Not works on PandoraBox(openwrt) ?
    ipr.tc('add-class', 'htb', dev, 0x10002, parent=0x10000, rate='100mbit', ceil='100mbit')
except NetlinkError as e:
    if e.code == 17:
        print('add class 0x10002 already exist')
    else:
        raise


try:
    ipr.tc('add-filter', 'fw', dev, 1, parent=0x10000, prio=10, protocol=ETH_P_IP, classid=0x10001)
except NetlinkError as e:
    if e.code == 17:
        print('add filter already exist')
    else:
        raise


print('done.')
```

This code works perfect on Ubuntu 14.04, but TypeError exception throws on PandoraBox(openwrt):

```
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    ipr.tc('add-filter', 'fw', dev, 1, parent=0x10000, prio=10, protocol=ETH_P_IP, classid=0x10001)
  File "/usr/lib/python2.7/site-packages/pyroute2/iproute.py", line 1312, in tc
    return self.nlm_request(msg, msg_type=command, msg_flags=flags)
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 777, in nlm_request
    return do_try()
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 755, in do_try
    self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 536, in put
    self.sendto_gate(msg, addr)
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 544, in sendto_gate
    msg.encode()
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/__init__.py", line 1000, in encode
    self.encode_nlas()
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/__init__.py", line 1201, in encode_nlas
    nla = msg_class(self.buf, parent=self, init=prime['init'])
TypeError: object.__new__() takes no parameters
```

Could  you give some help about this?  Many thanks!

**Comment by svinota** [comment]
That's a bug. Will be fixed asap, thanks for the report.

**Comment by svinota** [comment]
Pls try, should be fixed now. Thousand thanks for the issue!

**Comment by coderzh** [comment]
So good! I'll try it tomorow.

**Comment by coderzh** [comment]
Good! It works now, thanks!
