### ISSUE TITLE
Duplicate log messages

### ISSUE THREAD

**Issue by nachtmaar** [svinota/pyroute2#255]
Hi, 
while using pyroute2 I recognized a strange behaviour in the python logging module.

As soon as I import pyroute2, I get all log messages twice, but with two different formatters and/or handlers.

See the code below. The first snippet shows the "normal" behaviour, the second the double logging with pyroute2 imported.

```
import logging

#import pyroute2

logger = logging.getLogger("foo")
logger.setLevel(logging.INFO)
formatter = logging.Formatter("%(levelname)s %(name)s %(asctime)s %(module)s: %(message)s")
handler = logging.StreamHandler()
handler.setLevel(logging.INFO)
logger.addHandler(handler)

logger.info("foo")
```

Result:

```
foo
```

```
import logging

import pyroute2

logger = logging.getLogger("foo")
logger.setLevel(logging.INFO)
formatter = logging.Formatter("%(levelname)s %(name)s %(asctime)s %(module)s: %(message)s")
handler = logging.StreamHandler()
handler.setLevel(logging.INFO)
logger.addHandler(handler)

logger.info("foo")
```

Result:

```
foo
INFO:foo:foo
```

**Comment by svinota** [comment]
wow. Looks weird.

Investigating, thanks

**Comment by svinota** [comment]
Looks like the library added a default stream handler by calling `basicConfig()`. And that's really not a proper way.

Submitted a change. Pls check, if that will work for you.

**Comment by nachtmaar** [comment]
Yes, that fixed the problem.

By the way, installing the latest version of pyroute2 fails for me with pip.

```
pip install -e git+https://github.com/svinota/pyroute2.git@203dfd1574727daa9c725d39634e9ffdf2e2c5da#egg=pyroute2

root@f32f9ecd3cac:/tmp/pyroute2# pip install -e git+https://github.com/svinota/pyroute2.git@203dfd1574727daa9c725d39634e9ffdf2e2c5da#egg=pyroute2
Obtaining pyroute2 from git+https://github.com/svinota/pyroute2.git@203dfd1574727daa9c725d39634e9ffdf2e2c5da#egg=pyroute2
  Cloning https://github.com/svinota/pyroute2.git (to 203dfd1574727daa9c725d39634e9ffdf2e2c5da) to ./src/pyroute2
  Could not find a tag or branch '203dfd1574727daa9c725d39634e9ffdf2e2c5da', assuming commit.
  Running setup.py (path:/tmp/pyroute2/src/pyroute2/setup.py) egg_info for package pyroute2
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pyroute2/src/pyroute2/setup.py", line 10, in <module>
        module = __import__(config.get('setup', 'setuplib'),
      File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
        raise NoSectionError(section)
    ConfigParser.NoSectionError: No section: 'setup'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pyroute2/src/pyroute2/setup.py", line 10, in <module>

    module = __import__(config.get('setup', 'setuplib'),

  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get

    raise NoSectionError(section)

ConfigParser.NoSectionError: No section: 'setup'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pyroute2/src/pyroute2
Storing debug log for failure in /root/.pip/pip.log
```

At the moment I am downloading it manually, and install it with "make install".

Is this a bug or am I using it wrong?

**Comment by svinota** [comment]
I just didn't plan to use pip to install the library from the git repo — so there is no `setup.ini`, it is autogenerated. Thus the pip install from git fails.

I will update the `setup.py`, so it will manage with that, thanks.

**Comment by svinota** [comment]
Should work now.

**Comment by nachtmaar** [comment]
It does, thanks a lot :)

**Comment by svinota** [comment]
You're welcome!
