### ISSUE TITLE
test_bridge_vlans and test_bridge_vlans_flags do not pass

### ISSUE THREAD

**Issue by roolebo** [svinota/pyroute2#264]
Either kind of the tests (TestCompat, TestExplicit, TestImplicit) fails on 0.3.x branch:

```
======================================================================
FAIL: test_ipdb.TestImplicit.test_bridge_vlans
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyroute2/.tox/py26/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/root/pyroute2/tests/general/test_ipdb.py", line 1107, in test_bridge_vlans
    assert len(p.vlans) == 1
AssertionError
...snip...
======================================================================
ERROR: test_ipdb.TestImplicit.test_bridge_vlans_flags
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyroute2/.tox/py26/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/root/pyroute2/tests/general/test_ipdb.py", line 1090, in test_bridge_vlans_flags
    p.add_vlan(206)
  File "/root/pyroute2/tests/pyroute2/ipdb/transactional.py", line 221, in __exit__
    self.commit()
  File "/root/pyroute2/tests/pyroute2/ipdb/interface.py", line 940, in commit
    raise error
CommitException: vlans target is not set
```

**Comment by svinota** [comment]
Yep. To be fixed asap, thanks — I had to do it a well ago
