### ISSUE TITLE
Existing bridge interfaces do not store already existing ports

### ISSUE THREAD

**Issue by Callum027** [svinota/pyroute2#278]
When you add a new bridge interface using pyroute2 and add a port to it, everything works as expected. However, when pyroute2 inherits a bridge interface with ports added to it, those ports don't show up in pyroute2. This can result in a situation where you can add an interface to a bridge twice, and pyroute2 doesn't like it.

Test script:
```python
#!/usr/bin/python3

import pyroute2

netns = pyroute2.NetNS("foo")
ipdb = pyroute2.IPDB(nl=netns)

testdummy0 = None
testbr0 = None

if "testdummy0" in ipdb.by_name.keys():
    testdummy0 = ipdb.interfaces["testdummy0"]
else:
    testdummy0 = ipdb.create(ifname="testdummy0", kind="dummy")
    ipdb.commit()

if "testbr0" in ipdb.by_name.keys():
    testbr0 = ipdb.interfaces["testbr0"]
else:
    testbr0 = ipdb.create(ifname="testbr0", kind="bridge")
    ipdb.commit()

print("testbr0 bridge ports (before): %s" % testbr0.ports)

if testdummy0.index not in testbr0.ports:
    print("testdummy0 added")
    testbr0.add_port(testdummy0).commit()
else:
    print("testdummy0 not added")

print("testbr0 bridge ports (after): %s" % testbr0.ports)

ipdb.release()
netns.close()
```

Output (ran once, then ran immediately after):
```
(pyroute2-venv) root@ubuntu:~# python3 test.py
testbr0 bridge ports (before): []
testdummy0 added
testbr0 bridge ports (after): [2]

(pyroute2-venv) root@ubuntu:~# python3 test.py
testbr0 bridge ports (before): []
testdummy0 added
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    testbr0.add_port(testdummy0).commit()
  File "/root/pyroute2-venv/lib/python3.4/site-packages/pyroute2/ipdb/interface.py", line 905, in commit
    raise error
  File "/root/pyroute2-venv/lib/python3.4/site-packages/pyroute2/ipdb/interface.py", line 686, in commit
    raise CommitException('ports target is not set')
pyroute2.ipdb.exceptions.CommitException: ports target is not set
```

**Comment by svinota** [comment]
Thanks! Investigating

**Comment by svinota** [comment]
Sorry for the delay. The error in the code is located, the fix will be ready today.

**Comment by svinota** [comment]
fixed (I believe so), a version (0.4.6) released and published on pypi

**Comment by Callum027** [comment]
Thanks for getting onto it so quickly. All fixed on my end as well.

**Comment by svinota** [comment]
Thanks. So, I close the issue.
