### ISSUE TITLE
generic: report «module not loaded» instead of «file not found» in the init

### ISSUE THREAD

**Issue by xning** [svinota/pyroute2#294]
If I have report this issue, pls drop this.
Following is CentOS 6 outputs when instancing  *IW*

    [nerd@localhost ~]$ python
    Python 2.6.6 (r266:84292, Aug 18 2016, 14:53:48) 
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from pyroute2 import IW
    No handlers could be found for logger "pyroute2"
    >>> iw = IW()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.6/site-packages/pyroute2/__init__.py", line 125, in __new__
        return cls.registry[class](*argv, **kwarg)
      File "/usr/lib/python2.6/site-packages/pyroute2/iwutil.py", line 170, in __init__
        self.bind(groups, async)
      File "/usr/lib/python2.6/site-packages/pyroute2/netlink/nl80211/__init__.py", line 643, in bind
        groups, None, async)
      File "/usr/lib/python2.6/site-packages/pyroute2/netlink/generic/__init__.py", line 37, in bind
        msg = self.discovery(proto)
      File "/usr/lib/python2.6/site-packages/pyroute2/netlink/generic/__init__.py", line 72, in discovery
        raise err
    pyroute2.netlink.exceptions.NetlinkError: (2, No such file or directory)
    >>>

**Comment by svinota** [comment]
looks like nl80211 is not loaded.
```
$ sudo modprobe lib80211
$ sudo modprobe cfg80211
```

Pls keep in mind, that IW functionality is still very limited.

**Comment by svinota** [comment]
The error report at the init should be more reasonable

**Comment by xning** [comment]
@svinota you're write. This error is really caused  by not loading the two modules.

**Comment by svinota** [comment]
(I reopen the issue, since the error reporting should be fixed anyway, and the issue will be a reminder)

**Comment by xning** [comment]
This message does make sense for what cause the issue. Cool.
