### ISSUE TITLE
critical FD leak on RHEL6.5

### ISSUE THREAD

**Issue by svinota** [svinota/pyroute2#298]
The compat code (employed only on old kernels) leaks file descriptors on all bridge and bond operations.

**Comment by svinota** [comment]
… testing the fix

**Comment by jtluka** [comment]
Hi Peet, actually this won't fix the issue completely. Not sure why I have not seen it in my testing but the pipe fd leak is still there. I believe the issue is with Devlink object.

```
>>> from pyroute2 import DL
No handlers could be found for logger "pyroute2"
>>> dl = DL()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/pyroute2/__init__.py", line 126, in __new__
    return cls.registry['class'](*argv, **kwarg)
  File "/usr/lib/python2.6/site-packages/pyroute2/devlink.py", line 34, in __init__
    self.bind(groups, async)
  File "/usr/lib/python2.6/site-packages/pyroute2/netlink/devlink/__init__.py", line 131, in bind
    groups, None, async)
  File "/usr/lib/python2.6/site-packages/pyroute2/netlink/generic/__init__.py", line 37, in bind
    msg = self.discovery(proto)
  File "/usr/lib/python2.6/site-packages/pyroute2/netlink/generic/__init__.py", line 72, in discovery
    raise err
pyroute2.netlink.exceptions.NetlinkError: (2, 'No such file or directory')
>>>
```

When this happens I see 2 pipe fds left open. With every call of DL() it increases by two.

**Comment by jtluka** [comment]
This fixes the issue on RHEL6.8 for me
```
diff --git a/pyroute2/devlink.py b/pyroute2/devlink.py
index 1637473..90dd939 100644
--- a/pyroute2/devlink.py
+++ b/pyroute2/devlink.py
@@ -31,7 +31,11 @@ class DL(DevlinkSocket):
 
         # do automatic bind
         # FIXME: unfortunately we can not omit it here
-        self.bind(groups, async)
+        try:
+            self.bind(groups, async)
+        except:
+            super(DL, self).close()
+            raise
 
     def list(self):
         return self.get_dump()
```

**Comment by jtluka** [comment]
Checked on RHEL7.3, seems ok.

**Comment by svinota** [comment]
Yep. Another bug, huh. Checking, thanks.

**Comment by svinota** [comment]
Checked and pushed. Thanks.

**Comment by svinota** [comment]
@jtluka  maybe, I'm to add another release in the RHEL updates, if it matters?

**Comment by jtluka** [comment]
Sun, Oct 09, 2016 at 10:25:14PM CEST, notifications@github.com wrote:
>@jtluka  maybe, I'm to add another release in the RHEL updates, if it matters?
>

Yes, that would be cool.

**Comment by svinota** [comment]
Ok, so do I.

**Comment by svinota** [comment]
Updates pushed to epel, closing the issue again :)
