### ISSUE TITLE
Original route not removed when modifying priority

### ISSUE THREAD

**Issue by svvitale** [svinota/pyroute2#310]
I'm attempting to shuffle around the priority on some existing routes.  When I change the priority on a route and commit the changes, I see a new route added with the new priority, but the old one is not removed.  The condition is being detected, but not fully handled (see: https://github.com/svinota/pyroute2/blob/master/pyroute2/ipdb/route.py#L405).  It seems like either the old route entry should be fully removed from the kernel routing table, or it should remain and require the caller to remove it.  In its current form, the ipdb.routes list is left in an incorrect state after the transaction completes.

**Comment by svinota** [comment]
Yep, it's a design issue. Thanks, will try to fix.

**Comment by svvitale** [comment]
I would have submitted a pull request, but I didn't feel confident enough about how the multi-phased transactions operate.  Would it work to simply call the delete method with the snapshot data after the new route is created?

```
# create watchdog
wd = self.ipdb.watchdog('RTM_DELROUTE', **self.wd_key(snapshot))
for route in self.nl.route('delete', **snapshot):
    self.ipdb.routes.load_netlink(route)
wd.wait()
```

**Comment by svinota** [comment]
Should be fixed now.

**Comment by svvitale** [comment]
This appears to work correctly for default routes, but fails to set priority for non-default routes.  It raises a NetlinkError: (3, 'No such process').  Let me know if I can provide additional debug information.

**Comment by svinota** [comment]
Ough. Something I didn't expect. Thanks.

Could you pls provide a sample that causes the issue?

**Comment by svvitale** [comment]
Code:
```python
from pyroute2 import IPDB

with IPDB() as ipdb:
    for idx, route in enumerate(ipdb.routes):
        if route['dst'] != 'default':
            print(route)
            route.priority = 500 + idx
            route.commit()
```

Starting route table:
```
[nodepy] pi@node6:~/nodepy (master) $ ip route
default via 192.168.1.1 dev wlan0  metric 303 
default via 192.168.1.1 dev wlan1  metric 304 
192.168.1.0/24 dev wlan0  proto kernel  scope link  src 192.168.1.173  metric 303 
192.168.1.0/24 dev wlan1  proto kernel  scope link  src 192.168.1.137  metric 304 
[nodepy] pi@node6:~/nodepy (master) $
```

Execution fails on the first route update:
```
[nodepy] pi@node6:~/nodepy (master) $ sudo ~/virtualenv/nodepy/bin/python test.py
{'type': 1, 'ipdb_priority': 0, 'encap': {}, 'prefsrc': '192.168.1.173', 'multipath': [], 'oif': 3, 'tos': 0, 'src_len': 0, 'flags': 0, 'metrics': {}, 'dst': '192.168.1.0/24', 'family': 2, 'dst_len': 24, 'priority': 303, 'proto': 2, 'ipdb_scope': 'system', 'scope': 253, 'table': 254}
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    route.commit()
  File "/home/pi/virtualenv/nodepy/lib/python3.4/site-packages/pyroute2/ipdb/route.py", line 480, in commit
    raise error
  File "/home/pi/virtualenv/nodepy/lib/python3.4/site-packages/pyroute2/ipdb/route.py", line 398, in commit
    self.nl.route('del', **dict(old_key._asdict()))
  File "/home/pi/virtualenv/nodepy/lib/python3.4/site-packages/pyroute2/iproute.py", line 1683, in route
    callback=callback)
  File "/home/pi/virtualenv/nodepy/lib/python3.4/site-packages/pyroute2/netlink/nlsocket.py", line 805, in nlm_request
    return do_try()
  File "/home/pi/virtualenv/nodepy/lib/python3.4/site-packages/pyroute2/netlink/nlsocket.py", line 784, in do_try
    callback=callback)
  File "/home/pi/virtualenv/nodepy/lib/python3.4/site-packages/pyroute2/netlink/nlsocket.py", line 649, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (3, 'No such process')
[nodepy] pi@node6:~/nodepy (master) $
```

**Comment by svinota** [comment]
A really tough issue, but it seems to be fixed now. Sorry for such long time.

**Comment by svvitale** [comment]
Hi @svinota,

This works well for default and non-default IPv4 routes, but it seems to fail for IPv6 routes.  I'm not currently using IPv6, so it's not an issue for me, but I thought you'd want to know.

IPv4 Route Table:

```
[nodepy] pi@node6:~ $ ip route
default via 192.168.1.1 dev wlan1  metric 201
default via 192.168.1.1 dev wlan0  metric 300
192.168.1.0/24 dev wlan1  proto kernel  scope link  src 192.168.1.137  metric 200
192.168.1.0/24 dev wlan0  proto kernel  scope link  src 192.168.1.173  metric 301
[nodepy] pi@node6:~ $
```

IPv6 Route Table:

```
[nodepy] pi@node6:~ $ ip -6 route
fe80::/64 dev eth0  proto kernel  metric 256
fe80::/64 dev wlan1  proto kernel  metric 256
fe80::/64 dev wlan0  proto kernel  metric 256
[nodepy] pi@node6:~ $
```

Test code:
```python
temp_priority_range = deque(range(400, 500))                             
                                                                         
with IPDB() as ipdb:                                                     
   # Preserve the route list as it's about to change                     
   route_list = list(ipdb.routes)                                        
                                                                         
   # Deprioritize all routes, making way for the real priority numbers   
   for route in route_list:                                              
       if route.family == socket.AF_INET6.value:                         
           new_priority = temp_priority_range.popleft()                  
           print("Setting priority to", new_priority, "for route", route)
           route.priority = new_priority                                 
           route.commit()                                                
```

Output:
```
[nodepy] pi@node6:~/nodepy (master) $ sudo ~/virtualenv/nodepy/bin/python network_juggler.py
Setting priority to 400 for route {'oif': 1, 'ipdb_scope': 'system', 'family': 10, 'dst_len': 128, 'ipdb_priority': 0, 'tos': 0, 'priority': 403, 'type': 2, 'metrics': {}, 'flags': 0, 'src_len': 0, 'dst': '::1/128', 'encap': {}, 'proto': 2, 'table': 254, 'scope': 0, 'pref': '00', 'multipath': []}
Traceback (most recent call last):
  File "network_juggler.py", line 121, in <module>
    route.commit()
  File "/home/pi/virtualenv/nodepy/lib/python3.4/site-packages/pyroute2/ipdb/route.py", line 482, in commit
    raise error
  File "/home/pi/virtualenv/nodepy/lib/python3.4/site-packages/pyroute2/ipdb/route.py", line 411, in commit
    raise CommitException('route idx conflict')
pyroute2.ipdb.exceptions.CommitException: route idx conflict
[nodepy] pi@node6:~/nodepy (master) $
```

**Comment by svinota** [comment]
Thanks!

**Comment by svvitale** [comment]
Hi @svinota,

I finally tried upgrading to the latest pyroute2, and I'm encountering this same problem again with the non-default routes.  

Same test code:

```
from pyroute2 import IPDB

with IPDB() as ipdb:
    for idx, route in enumerate(ipdb.routes):
        if route['dst'] != 'default':
            print(route)
            route.priority = 500 + idx
            route.commit()
```

Produces the same error:

```
[nodepy] pi@node6:~/nodepy (master) $ sudo ~/virtualenv/nodepy/bin/python test.py
{'type': 1, 'ipdb_priority': 0, 'encap': {}, 'prefsrc': '192.168.1.173', 'multipath': [], 'oif': 3, 'tos': 0, 'src_len': 0, 'flags': 0, 'metrics': {}, 'dst': '192.168.1.0/24', 'family': 2, 'dst_len': 24, 'priority': 303, 'proto': 2, 'ipdb_scope': 'system', 'scope': 253, 'table': 254}
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    route.commit()
  File "/home/pi/virtualenv/nodepy/lib/python3.4/site-packages/pyroute2/ipdb/route.py", line 480, in commit
    raise error
  File "/home/pi/virtualenv/nodepy/lib/python3.4/site-packages/pyroute2/ipdb/route.py", line 398, in commit
    self.nl.route('del', **dict(old_key._asdict()))
  File "/home/pi/virtualenv/nodepy/lib/python3.4/site-packages/pyroute2/iproute.py", line 1683, in route
    callback=callback)
  File "/home/pi/virtualenv/nodepy/lib/python3.4/site-packages/pyroute2/netlink/nlsocket.py", line 805, in nlm_request
    return do_try()
  File "/home/pi/virtualenv/nodepy/lib/python3.4/site-packages/pyroute2/netlink/nlsocket.py", line 784, in do_try
    callback=callback)
  File "/home/pi/virtualenv/nodepy/lib/python3.4/site-packages/pyroute2/netlink/nlsocket.py", line 649, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (3, 'No such process')
[nodepy] pi@node6:~/nodepy (master) $
```

**Comment by svinota** [comment]
Thanks, I reopen the issue.
