### ISSUE TITLE
error: unpack_from requires a buffer of at least 4 bytes when MTU changes on RHEL6.8

### ISSUE THREAD

**Issue by jtluka** [svinota/pyroute2#315]
With LNST on RHEL6.8 I'm getting following traceback from pyroute2:
```
2016-11-21 15:23:53        (machine1)        - WARNING: decoding AF_INET
2016-11-21 15:23:53        (machine1)        - WARNING: 
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/pyroute2/netlink/__init__.py", line 1379, in get_value
        cell.decode()
      File "/usr/lib/python2.6/site-packages/pyroute2/netlink/__init__.py", line 1689, in decode
        nla_base.decode(self)
      File "/usr/lib/python2.6/site-packages/pyroute2/netlink/__init__.py", line 918, in decode
        self.ft_decode(self, offset)
      File "/usr/lib/python2.6/site-packages/pyroute2/netlink/__init__.py", line 1203, in _ft_decode_generic
        value = struct.unpack_from(fmt, self.data, offset)
      File "/usr/lib/python2.6/site-packages/pyroute2/__init__.py", line 32, in wrapped
        return struct._u_f_orig(fmt, str(buf), offset)
    error: unpack_from requires a buffer of at least 4 bytes
```

It happens after updating tunnel (IPIP) device MTU. I was not able to get simplified reproducer for this yet, so to reproduce one needs to run the attached LNST recipe.

lnst version: 41d97e649970c16303ae4158dabfdf25fd7f19de
pyroute2 version: 0bea92f68913ad3c007ce113931d528911448faa

Prepare lnst environment with two RHEL6.8 guests, download both ipip.xml and ipip.py files and then run:
lnst-ctl -d run ipip.xml

**Comment by jtluka** [comment]
[ipip.zip](https://github.com/svinota/pyroute2/files/606330/ipip.zip)

**Comment by svinota** [comment]
Got it, thanks

**Comment by svinota** [comment]
Sorry for delay, started to debug. Expect results on Monday.
