### ISSUE TITLE
ipset failures on 4.8.10

### ISSUE THREAD

**Issue by svinota** [svinota/pyroute2#328]
Looks like there are some issues on 4.8.10 (Fedora 24)

```
$ sudo make test module=general:test_ipset.py
Running as root
net.mpls.platform_labels = 2048
8<------------------------------------------------
kernel: 4.8.10-200.fc24.x86_64
python: /usr/bin/python [Python 2.7.12]
flake8: /usr/bin/flake8 [3.0.4 (mccabe: 0.5.2, pyflakes: 1.2.3, pycodestyle: 2.0.0) CPython 2.7.12 on Linux]
nose: /usr/bin/nosetests [nosetests version 1.3.7]
8<------------------------------------------------
flake8 ... ok
test_ipset.TestIPSet.test_add_delete ... FAIL
test_ipset.TestIPSet.test_add_exclusive_fail ... FAIL
test_ipset.TestIPSet.test_add_exclusive_success ... FAIL
test_ipset.TestIPSet.test_comments ... FAIL
test_ipset.TestIPSet.test_counters ... FAIL
test_ipset.TestIPSet.test_create_destroy ... ok
test_ipset.TestIPSet.test_create_exclusive_fail ... ok
test_ipset.TestIPSet.test_create_exclusive_success ... ok
test_ipset.TestIPSet.test_flush ... FAIL
test_ipset.TestIPSet.test_forceadd ... FAIL
test_ipset.TestIPSet.test_hashsize ... ok
test_ipset.TestIPSet.test_maxelem ... ok
test_ipset.TestIPSet.test_net_and_iface_stypes ... FAIL
test_ipset.TestIPSet.test_net_with_dash ... FAIL
test_ipset.TestIPSet.test_rename ... ok
test_ipset.TestIPSet.test_swap ... FAIL
test_ipset.TestIPSet.test_timeout ... FAIL

======================================================================
FAIL: test_ipset.TestIPSet.test_add_delete
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/peet/Projects/pyroute2/tests/general/test_ipset.py", line 140, in test_add_delete
    assert ipaddr in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_add_exclusive_fail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/peet/Projects/pyroute2/tests/general/test_ipset.py", line 98, in test_add_exclusive_fail
    assert ipaddr in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_add_exclusive_success
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/peet/Projects/pyroute2/tests/general/test_ipset.py", line 113, in test_add_exclusive_success
    assert ipaddr in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_comments
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/peet/Projects/pyroute2/tests/general/test_ipset.py", line 199, in test_comments
    assert ipaddr in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_counters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/peet/Projects/pyroute2/tests/general/test_ipset.py", line 180, in test_counters
    assert ipaddr in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_flush
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/peet/Projects/pyroute2/tests/general/test_ipset.py", line 263, in test_flush
    assert ip_a in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_forceadd
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/peet/Projects/pyroute2/tests/general/test_ipset.py", line 252, in test_forceadd
    assert ipaddr in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_net_and_iface_stypes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/peet/Projects/pyroute2/tests/general/test_ipset.py", line 308, in test_net_and_iface_stypes
    assert entry in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_net_with_dash
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/peet/Projects/pyroute2/tests/general/test_ipset.py", line 321, in test_net_with_dash
    assert "192.168.1.0/27" in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_swap
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/peet/Projects/pyroute2/tests/general/test_ipset.py", line 162, in test_swap
    assert ipaddr_a in self.list_ipset(name_a)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_timeout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/peet/Projects/pyroute2/tests/general/test_ipset.py", line 290, in test_timeout
    assert ip in self.list_ipset(name)
AssertionError

----------------------------------------------------------------------
XML: /home/peet/Projects/pyroute2/tests/nosetests.xml
Name                                  Stmts   Miss  Cover   Missing
-------------------------------------------------------------------
pyroute2.py                              69     30    57%   26-36, 88, 91, 94, 101-113, 117-122, 125-126, 146-148
pyroute2/common.py                      309    185    40%   23-27, 83-88, 91-93, 96, 99, 102-105, 108-115, 118, 121, 124, 127-128, 131, 137-138, 141-156, 159-164, 185, 189-202, 205-208, 211-214, 245-255, 260-281, 288, 295-299, 304-308, 328-363, 383, 421, 427, 431-432, 441, 445, 452-453, 457-466, 476, 478, 495-499, 514-518, 522, 534, 546, 553-562, 569, 576-588
pyroute2/config.py                       16      0   100%
pyroute2/ipdb.py                          0      0   100%
pyroute2/ipdb/exceptions.py               8      0   100%
pyroute2/ipset.py                       142     22    85%   80, 96, 142, 159-162, 174-177, 192, 194, 218, 225, 232-236, 244-248
pyroute2/netlink.py                     786    304    61%   426, 607, 647-653, 661-663, 672-680, 684-695, 698-701, 710-715, 718-755, 761, 767, 770, 779-810, 814-817, 828, 839-842, 909-919, 924, 953-962, 981-984, 987, 991, 993, 996-1001, 1036-1037, 1046-1048, 1054-1059, 1067-1068, 1072, 1081, 1084, 1101-1109, 1115-1134, 1153, 1163, 1169-1190, 1211, 1217-1219, 1232, 1265-1266, 1273-1274, 1308, 1320-1321, 1351, 1365-1366, 1385-1388, 1395, 1398-1400, 1407-1413, 1416-1418, 1440-1441, 1450-1451, 1489-1490, 1517-1522, 1525-1531, 1546-1551, 1554-1577, 1580-1594, 1606-1609, 1612-1613, 1623-1624, 1637-1644, 1647-1649, 1652-1659, 1675, 1682-1685
pyroute2/netlink/exceptions.py           21      2    90%   21, 53
pyroute2/netlink/nfnetlink.py            16      0   100%
pyroute2/netlink/nfnetlink/ipset.py      36      0   100%
pyroute2/netlink/nlsocket.py            462    163    65%   119-120, 158, 182-191, 241-242, 266, 272, 299, 333-336, 345, 351-353, 356, 359, 362-364, 401-403, 410-414, 437, 457-467, 475-487, 490, 493, 496, 499, 502-517, 554-555, 563-564, 570, 595, 598, 621-625, 696-699, 718-726, 737, 741-746, 761, 808, 810-811, 817, 820, 826, 829, 835, 838, 841, 848-851, 854, 857-859, 862, 871, 892-896, 900, 916-961, 969, 973-974
-------------------------------------------------------------------
TOTAL                                  1865    706    62%
----------------------------------------------------------------------
Ran 17 tests in 33.861s

FAILED (failures=11)
Makefile:128: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by jllorente** [comment]
Same for Ubuntu 16.04 (4.4.0-57-generic)

```
Running as root
net.mpls.platform_labels = 2048
8<------------------------------------------------
kernel: 4.4.0-57-generic
python: /usr/bin/python3 [Python 3.5.2]
flake8: /usr/local/bin/flake8 [3.2.1 (pyflakes: 1.3.0, pycodestyle: 2.2.0, mccabe: 0.5.3) CPython 2.7.12 on Linux]
nose: /usr/local/bin/nosetests [nosetests version 1.3.7]
8<------------------------------------------------
flake8 ... ok
/home/ubuntu/.local/lib/python3.5/site-packages/nose/importer.py:12: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import find_module, load_module, acquire_lock, release_lock
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
test_ipset.TestIPSet.test_add_delete ... FAIL
test_ipset.TestIPSet.test_add_exclusive_fail ... FAIL
test_ipset.TestIPSet.test_add_exclusive_success ... FAIL
test_ipset.TestIPSet.test_comments ... FAIL
test_ipset.TestIPSet.test_counters ... FAIL
test_ipset.TestIPSet.test_create_destroy ... ok
test_ipset.TestIPSet.test_create_exclusive_fail ... ok
test_ipset.TestIPSet.test_create_exclusive_success ... ok
test_ipset.TestIPSet.test_flush ... FAIL
test_ipset.TestIPSet.test_forceadd ... FAIL
test_ipset.TestIPSet.test_hashsize ... ok
test_ipset.TestIPSet.test_maxelem ... ok
test_ipset.TestIPSet.test_net_and_iface_stypes ... FAIL
test_ipset.TestIPSet.test_net_with_dash ... FAIL
test_ipset.TestIPSet.test_rename ... ok
test_ipset.TestIPSet.test_swap ... FAIL
test_ipset.TestIPSet.test_timeout ... FAIL

======================================================================
FAIL: test_ipset.TestIPSet.test_add_delete
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/github/pyroute2/tests/general/test_ipset.py", line 140, in test_add_delete
    assert ipaddr in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_add_exclusive_fail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/github/pyroute2/tests/general/test_ipset.py", line 98, in test_add_exclusive_fail
    assert ipaddr in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_add_exclusive_success
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/github/pyroute2/tests/general/test_ipset.py", line 113, in test_add_exclusive_success
    assert ipaddr in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_comments
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/github/pyroute2/tests/general/test_ipset.py", line 199, in test_comments
    assert ipaddr in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_counters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/github/pyroute2/tests/general/test_ipset.py", line 180, in test_counters
    assert ipaddr in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_flush
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/github/pyroute2/tests/general/test_ipset.py", line 263, in test_flush
    assert ip_a in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_forceadd
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/github/pyroute2/tests/general/test_ipset.py", line 252, in test_forceadd
    assert ipaddr in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_net_and_iface_stypes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/github/pyroute2/tests/general/test_ipset.py", line 308, in test_net_and_iface_stypes
    assert entry in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_net_with_dash
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/github/pyroute2/tests/general/test_ipset.py", line 321, in test_net_with_dash
    assert "192.168.1.0/27" in self.list_ipset(name)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_swap
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/github/pyroute2/tests/general/test_ipset.py", line 162, in test_swap
    assert ipaddr_a in self.list_ipset(name_a)
AssertionError

======================================================================
FAIL: test_ipset.TestIPSet.test_timeout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/github/pyroute2/tests/general/test_ipset.py", line 290, in test_timeout
    assert ip in self.list_ipset(name)
AssertionError

----------------------------------------------------------------------
XML: /home/ubuntu/github/pyroute2/tests/nosetests.xml
----------------------------------------------------------------------
Ran 17 tests in 18.296s

FAILED (failures=11)
Makefile:128: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by svinota** [comment]
Fixed API compatibility. One test is still failing, but it is another issue.
