### ISSUE TITLE
unknown address family 10

### ISSUE THREAD

**Issue by schneuwlym** [svinota/pyroute2#348]
I can see some strack traces at times in my log.

In version 0.4.12:
```
2017-03-22 15:28:54,374 decoding RTA_DST
2017-03-22 15:28:54,374 Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/__init__.py", line 1383, in try_to_decode
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/__init__.py", line 1583, in decode
ValueError: unknown address family 10
```

In version 0.4.13:
```
2017-03-22 15:41:52,692 Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/__init__.py", line 1383, in try_to_decode
    cell.decode()
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/__init__.py", line 1583, in decode
    self.value = inet_ntop(family, self['value'])
ValueError: unknown address family 10
2017-03-22 15:41:52,693 decoding RTA_DST
2017-03-22 15:41:52,693 Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/__init__.py", line 1383, in try_to_decode
    cell.decode()
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/__init__.py", line 1583, in decode
    self.value = inet_ntop(family, self['value'])
ValueError: unknown address family 10
```
Not sure what triggers this. I'm using IPDB to get routing updates.

**Comment by svinota** [comment]
address family 10 — it's IPv6: `socket.AF_INET6`

can you pls check, if your Python is built with IPv6 support?

**Comment by schneuwlym** [comment]
How can I check that? At least this works
```
>>> import socket    
>>> socket.AF_INET6
10
```

**Comment by schneuwlym** [comment]
This sample code doesn't work. So I guess you are right that it was not build with ipv6 support
```
>>> import socket
>>> s = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
>>> s.bind(('', 12345))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: getsockaddrarg: bad family
```

**Comment by svinota** [comment]
I have to take into account, that IPv6 may be missing, and notify about that. Thanks for heads-up!
