### ISSUE TITLE
Where did my link-local address go?

### ISSUE THREAD

**Issue by tuxis-ie** [svinota/pyroute2#351]
Hi,

If I create a vlan interface using iproute2, it automatically gets a link-local IPv6 address. If I create the interface using pyroute2, there is no LLaddress. Should I add it myself, or is there another issue?

**Comment by tuxis-ie** [comment]
It looks like there is a fe80:: address, but as soon as I add a global address, the fe80:: address is removed...

**Comment by tuxis-ie** [comment]
I'm using this function to add ip addresses:
```(python)
def Addaddr(iface, addr):
    print("Adding IP %s to %s" % (addr, iface))
    global ip
    i = ip.interfaces[iface]
    i.add_ip(addr)
    ip.commit()
```

So, looking at https://github.com/svinota/pyroute2/blob/dd39005252dd54087d656248b3cacd78e9b935fb/pyroute2/ipdb/interface.py#L334 I thought I'd add ```scope='global'``` to the add_ip-call, but that gives me this trace:
```
  File "/usr/sbin/ypconfig", line 82, in <module>
    Netlink.Commit(cur, new)
  File "/usr/lib/python3/dist-packages/ypconfig/Netlink.py", line 99, in Commit
    Addvlan(new[iface])
  File "/usr/lib/python3/dist-packages/ypconfig/Netlink.py", line 190, in Addvlan
    Addaddr(iface, addr)
  File "/usr/lib/python3/dist-packages/ypconfig/Netlink.py", line 244, in Addaddr
    ip.commit()
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/main.py", line 909, in commit
    commit_mask=phase)
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/interface.py", line 803, in commit
    **kwarg if kwarg else {})
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/interface.py", line 458, in _run
    return cmd(*argv, **kwarg)
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/iproute.py", line 1363, in addr
    terminate=lambda x: x['header']['type'] ==
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/nlsocket.py", line 805, in nlm_request
    return do_try()
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/nlsocket.py", line 781, in do_try
    self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/nlsocket.py", line 562, in put
    self.sendto_gate(msg, addr)
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/rtnl/iprsocket.py", line 54, in _gate
    msg.encode()
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/__init__.py", line 997, in encode
    log.error(''.join(traceback.format_stack()))

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/__init__.py", line 995, in encode
    struct.pack_into(efmt, self.data, offset, value)
struct.error: required argument is not an integer

error pack: B b'global' <class 'bytes'>
We had an error confirming this new configuration:
 - 'required argument is not an integer
Rolling back
```

**Comment by tuxis-ie** [comment]
Found them!

If you add addresses too fast, the fe80:: address disappears. I fixed it now by commiting first, after ```i.up()```, then do a ```i.wait_ip('fe80:::', mask=64, timeout=5)```, and then returning to further configuration of the interface.

So not a bug, but maybe some kind of future-feature-idea. And it's documented for others. :)

**Comment by svinota** [comment]
I reopen the issue for investigation.
