### ISSUE TITLE
ipdb: Routes out of sync after commit failure

### ISSUE THREAD

**Issue by PaulSD** [svinota/pyroute2#396]
I mentioned this in https://github.com/svinota/pyroute2/issues/381#issuecomment-314907103 but it looks like it was forgotten.

After a route commit failure, ipdb.routes still reflects the attempted changes, but those changes can't be dropped:
```
>>> from pyroute2 import IPDB
>>> ipdb = IPDB()
>>> r = ipdb.routes.add(table=2, dst='10.0.0.0/24', gateway='1.1.1.1')
>>> r.commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/routes.py", line 506, in commit
    raise error
pyroute2.netlink.exceptions.NetlinkError: (1, 'Operation not permitted')
>>> ipdb.routes.tables[2]
[{'oif': 3, 'dst_len': 24, 'family': 2, 'proto': 3, 'tos': 0, 'dst': '10.0.0.0/24', 'ipdb_priority': 0, 'metrics': {}, 'flags': 0, 'encap': {}, 'src_len': 0, 'table': 2, 'multipath': (), 'type': 1, 'scope': 253, 'ipdb_scope': 'system'}, {'family': 2, 'dst': '10.0.0.0/24', 'ipdb_priority': 0, 'metrics': {}, 'encap': {}, 'scope': 0, 'table': 2, 'multipath': (), 'gateway': '1.1.1.1', 'ipdb_scope': 'create'}]
>>> r.review()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/transactional.py", line 381, in review
    raise TypeError('start a transaction first')
TypeError: start a transaction first
>>> r.drop()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/transactional.py", line 413, in drop
    raise TypeError("no transaction")
TypeError: no transaction
```

**Comment by svinota** [comment]
Yep. The `drop()` call drops only the transaction ( == changes), not the object itself. After the failed `commit()` the transaction gets dropped, but the objects remains in the DB to provide the ability to fix it and try to `commit()` again.

In the `interfaces` plugins there is another call, `detach()`, that completely removes the interface object from the DB. There should be a generic call, that would do the same, I believe.

In either case right now the API in the `routes` plugin is incomplete, so will be fixed asap.

**Comment by svinota** [comment]
Sorry for it takes so long time. Next week comes a complete re-design of the IPDB objects life cycle, to get a uiform state machine for all the object types.

**Comment by PaulSD** [comment]
No worries, thanks for working on this!

**Comment by svinota** [comment]
The work on the issue continues on the master branch and will be released as 0.5.0. More on the changes: https://github.com/svinota/pyroute2/commit/cbbf08e4d5a9443a3897eb40fe8b1c4597173b0c (and following commits)

0.4.19 will not have yet this changes, but will provide some othe bugfixes.

**Comment by PaulSD** [comment]
Following up on this...
The transaction handling itself works better now, but ipdb.routes is still inconsistent after a transaction is dropped.  For example, note that the added route is still listed in ipdb.routes even though I called drop() after the commit() failed:
```
>>> from pyroute2 import IPDB
>>> ipdb = IPDB()
>>> ipdb.routes.tables[2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 2
>>> r = ipdb.routes.add(table=2, dst='10.0.0.0/24', gateway='1.1.1.1')
>>> ipdb.routes.tables[2]
[{'family': 2, 'tos': 0, 'dst': '10.0.0.0/24', 'ipdb_priority': 0, 'metrics': {}, 'encap': {}, 'scope': 0, 'table': 2, 'multipath': (), 'gateway': '1.1.1.1', 'ipdb_scope': 'create'}]
>>> r.commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/routes.py", line 499, in commit
    raise error
pyroute2.netlink.exceptions.NetlinkError: (101, 'Network is unreachable')
>>> r.drop()
>>> ipdb.routes.tables[2]
[{'family': 2, 'tos': 0, 'dst': '10.0.0.0/24', 'ipdb_priority': 0, 'metrics': {}, 'encap': {}, 'scope': 0, 'table': 2, 'multipath': (), 'gateway': '1.1.1.1', 'ipdb_scope': 'create'}]
>>> r.review()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/transactional.py", line 399, in review
    raise TypeError('start a transaction first')
TypeError: start a transaction first
>>>
```

**Comment by svinota** [comment]
«not a bug, but a feature»

That's intentionally. The object failed to be created stays in the DB with `ipdb_scope == "create"` — you may see that in the output above — to give a chance to fix it and commit again.

The transaction get's dropped with `drop()`, but the objects itself stays. If you want to remove the failed object, use `ipdb.<object>.remove().commit()`

**fixme: to be documented**

**Comment by PaulSD** [comment]
Hmmm...  This is a problem when using global commits.

If I make a bunch of changes and call `ipdb.commit()` and it fails, then I can't easily call `ipdb.<object>.remove().commit()` since I don't know what was added.  I guess I could scan through all of the tables and look for routes with `ipdb_scope == "create"` and remove them, but that seems ugly.  I could also check for `ipdb_scope == "create"` any time I read the DB after that and ignore any routes that have it, but that also seems ugly.

A few thoughts:
* If a commit fails and you want to fix and commit it again, you can do this before calling `drop()`:
```
>>> r = ipdb.routes.add(table=2, dst='10.0.0.0/24', gateway='1.1.1.1')
>>> r.commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/routes.py", line 520, in commit
    raise error
pyroute2.netlink.exceptions.NetlinkError: (101, 'Network is unreachable')
>>> r.gateway='10.0.0.1'
>>> r.commit()
{'oif': 3, 'dst_len': 24, 'family': 2, 'proto': 4, 'tos': 0, 'dst': '10.0.0.0/24', 'flags': 0, 'ipdb_priority': 0, 'metrics': {}, 'scope': 0, 'encap': {}, 'src_len': 0, 'table': 2, 'multipath': (), 'type': 1, 'gateway': '10.0.0.1', 'ipdb_scope': 'system'}
```
* Calling `drop()` after a failed update or `remove()` leaves the DB in its original state and causes all knowledge of the attempted change(s) to be lost, making it impossible to fix the problem and commit again without re-applying the changes.  It would seem more intuitive if `.add().drop()` behaved the same way.  If the user actually wants to fix the problem and try `commit()` again in any of these cases, I would expect them to do that before calling `drop()`, not after calling it, so I don't think it should be necessary to leave the route in the DB after `.add().drop()`.
* If the route must be left in the DB after `.add().drop()`, could another function be added (maybe `ipdb.reset()` or `ipdb.revert()` or something like that) to flush the routes with `ipdb_scope == "create"`?  This could be called either in addition to or instead of `drop()`.  Or maybe a flag could be passed in to `drop()` to request this behavior?

**Comment by svinota** [comment]
@PaulSD actually, the `drop()` function is the complement to `begin()`, that called implicitly on the first change. Both operate on transactions — `begin()` creates one, while `drop()` drops the transaction object. And `remove()` is the complement to `add()`. These two operate on objects in the DB. While `commit()` applies a transaction to an object in the DB.

Probably there is a reason to remove a newly created DB object, though it would be a model violation.

And it's a good idea to automatically clean up all the failed objects by some call. Thanks, will try to implement it.
