### ISSUE TITLE
ipdb: Bogus CommitException when adding IPv6 route to table>=256

### ISSUE THREAD

**Issue by PaulSD** [svinota/pyroute2#408]
```
>>> from pyroute2 import IPDB
>>> ipdb = IPDB()
>>> ipdb.routes.add({'dst': '1234::/64', 'oif': 3, 'table': 255}).commit()
{'metrics': {}, 'oif': 3, 'dst_len': 64, 'family': 10, 'proto': 4, 'tos': 0, 'dst': '1234::/64', 'pref': '00', 'ipdb_priority': 0, 'priority': 1024, 'flags': 0, 'encap': {}, 'src_len': 0, 'table': 255, 'multipath': (), 'type': 1, 'scope': 0, 'ipdb_scope': 'system'}
>>> ipdb.routes.add({'dst': '1234::/64', 'oif': 3, 'table': 256}).commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/routes.py", line 515, in commit
    raise error
pyroute2.ipdb.exceptions.CommitException: target family is not set
```

The route is actually added to the kernel properly despite the exception.

**Comment by PaulSD** [comment]
The issue is that for IPv4, the kernel uses rtm_table=252 if RTA_TABLE>=256:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/route.c#n2572
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/rtnetlink.h#n291

But for IPv6, the kernel uses rtm_table=(unsigned char)(RTA_TABLE) if RTA_TABLE>=256:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv6/route.c#n3397

So this code doesn't work for IPv6:
https://github.com/svinota/pyroute2/blob/master/pyroute2/ipdb/routes.py#L1064

I'll submit a PR shortly.
