### ISSUE TITLE
Thread crashes with LWT bpf routes

### ISSUE THREAD

**Issue by Zashas** [svinota/pyroute2#433]
Hi,

I spotted the following bug in pyroute2 after having installed a LWT bpf route : 

`sudo ip -6 route add fc00::/16 encap bpf out obj acl_bpf.o sec lwt_acl dev lo`

(acl_bpf.o can be compiled or downloaded from here https://github.com/Zashas/bpf_stuff/tree/master/lwt_acl

```
$ python
Python 2.7.14 (default, Sep 20 2017, 01:25:59) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyroute2
>>> ip = pyroute2.IPDB()
>>> ip.routes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/math/.local/share/virtualenvs/segway-yeSBDavQ/lib/python2.7/site-packages/pyroute2/ipdb/main.py", line 900, in __getattribute__
    obj._register()
  File "/home/math/.local/share/virtualenvs/segway-yeSBDavQ/lib/python2.7/site-packages/pyroute2/ipdb/routes.py", line 997, in _register
    self.load_netlink(msg)
  File "/home/math/.local/share/virtualenvs/segway-yeSBDavQ/lib/python2.7/site-packages/pyroute2/ipdb/routes.py", line 1095, in load_netlink
    key = self.tables[table].load(msg)
  File "/home/math/.local/share/virtualenvs/segway-yeSBDavQ/lib/python2.7/site-packages/pyroute2/ipdb/routes.py", line 920, in load
    self[key] = msg
  File "/home/math/.local/share/virtualenvs/segway-yeSBDavQ/lib/python2.7/site-packages/pyroute2/ipdb/routes.py", line 932, in __setitem__
    record['route'].load_netlink(value)
  File "/home/math/.local/share/virtualenvs/segway-yeSBDavQ/lib/python2.7/site-packages/pyroute2/ipdb/routes.py", line 307, in load_netlink
    for l in value.get_attr('MPLS_IPTUNNEL_DST'):
TypeError: 'NoneType' object is not iterable
```
I'm running kernel 4.13.3

**Comment by svinota** [comment]
Should be already fixed in the master branch (and will be included in the next release).

Pls tell, if the master branch doesn't work for you. Thanks!

**Comment by Zashas** [comment]
Indeed, it works fine with master. Sorry for the disturbance!

**Comment by svinota** [comment]
NP! Glad that it is fixed already :)
