### ISSUE TITLE
Exception is thrown when try change promiscuity state

### ISSUE THREAD

**Issue by lets00** [svinota/pyroute2#460]
Hi,
When I try change promiscuity state on a interface, a Commit Exception is thrown:
```python
>>> import pyroute2
>>> ipdb = pyroute2.IPDB()
>>> ipdb.interfaces['wlp2s0'].set_promiscuity(1).commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pyroute2/ipdb/interfaces.py", line 1043, in commit
    raise error
pyroute2.ipdb.exceptions.CommitException: target promiscuity is not set
```
The code above is running using su user. But, when I use iproute2 tool CLI (ip), the operation is realized:
```
# netstat -i
Tabela de Interfaces do Kernel
Iface      MTU    RX-OK RX-ERR RX-DRP RX-OVR    TX-OK TX-ERR TX-DRP TX-OVR Flg
enp1s0    1200        0      0      0 0             0      0      0      0 BMU
lo       65536       26      0      0 0            26      0      0      0 LRU
veth0     1500       28      0      0 0            39      0      0      0 BMPRU
veth1     1500       39      0      0 0            28      0      0      0 BMRU
wlp2s0    1500   178145      0      0 0         77687      0      0      0 BMRU
# ip l set wlp2s0 promisc on
# netstat -i
Tabela de Interfaces do Kernel
Iface      MTU    RX-OK RX-ERR RX-DRP RX-OVR    TX-OK TX-ERR TX-DRP TX-OVR Flg
enp1s0    1200        0      0      0 0             0      0      0      0 BMU
lo       65536       26      0      0 0            26      0      0      0 LRU
veth0     1500       28      0      0 0            39      0      0      0 BMPRU
veth1     1500       39      0      0 0            28      0      0      0 BMRU
wlp2s0    1500   178190      0      0 0         77693      0      0      0 BMPRU
```
In wlp2s0, after I run ip command, It appears the letter P, Indicates that promisc mode is enabled.

**OS usage**: Fedora 27 Workstation
**Kernel version**: 4.15.3-300.fc27.x86_64
**pyroute2 version**: pyroute2==0.4.21

**Comment by svinota** [comment]
Thanks! Investigating.

**Comment by svinota** [comment]
@lets00  with IPDB:
```
from pyroute2.netlink.rtnl.ifinfmsg import IFF_PROMISC
# ... set the flag
ipdb.interfaces['wlp2s0']['flags'] |= IFF_PROMISC
ipdb.interfaces['wlp2s0'].commit()
# ... clean the flag
ipdb.interfaces['wlp2s0']['flags'] &= ~(0xffffffff & IFF_PROMISC)
ipdb.interfaces['wlp2s0'].commit()
```

**Comment by svinota** [comment]
@carlos-jenkins with IPRoute:
```python
# ... set the flag
ip.link('set', index=..., flags=['IFF_PROMISC'])
# ... clear the flag
ip.link('set', index=..., flags=['!IFF_PROMISC'])
```

**Comment by lets00** [comment]
> @lets00 with IPDB:
> 
> ```python
> from pyroute2.netlink.rtnl.ifinfmsg import IFF_PROMISC
> # ... set the flag
> ipdb.interfaces['wlp2s0']['flags'] |= IFF_PROMISC
> ipdb.interfaces['wlp2s0'].commit()
> # ... clear the flag
> ipdb.interfaces['wlp2s0']['flags'] &= ~(0xffffffff & IFF_PROMISC)
> ipdb.interfaces['wlp2s0'].commit()
> ```

Uow, a year after! I will test this solution. Thank you @svinota!

**Comment by svinota** [comment]
@lets00 I have literally no idea how I missed the ticket. Sorry.

**Comment by lets00** [comment]
It works @svinota, Thank you!
```
$ netstat -i
Iface      MTU    RX-OK RX-ERR RX-DRP RX-OVR    TX-OK TX-ERR TX-DRP TX-OVR Flg
br1       1500        0      0      0 0             0      0      0      0 BMU
docker0   1500        0      0      0 0             0      0      0      0 BMU
...
```
```
$ python
>>> from pyroute2.netlink.rtnl.ifinfmsg import IFF_PROMISC
>>> from pyroute2 import IPDB
>>> ipdb = IPDB()
>>> ipdb.interfaces['br1']['flags'] |= IFF_PROMISC
>>> ipdb.interfaces['br1'].commit()
...
```
```
$ netstat -i
Iface      MTU    RX-OK RX-ERR RX-DRP RX-OVR    TX-OK TX-ERR TX-DRP TX-OVR Flg
br1       1500        0      0      0 0             0      0      0      0 BMPU
docker0   1500        0      0      0 0             0      0      0      0 BMU
...

```
But, I think that use the ```set_promiscuity()``` method could be the easier way. Why this method does not work as expected?

**Comment by svinota** [comment]
@lets00 for whatever reason the `IFLA_PROMISCUITY` is readonly, the kernel simply ignores this NLA when we send the `set` request. So we have to use flags.
