### ISSUE TITLE
"failed to open netns" in chroot

### ISSUE THREAD

**Issue by itdaniher** [svinota/pyroute2#479]
Have a 32b chroot on a 64b (ARM) machine. Pyroute2 doesn't seem to play ball with network namespaces when inside a chroot. `ip netns exec <ns> <cmd>` works fine either way.

Here's a basic example.

> sudo ip netns add test
> sudo python3 test.py

where test.py is
```python
from pyroute2 import IPDB, NetNS
with IPDB(nl=NetNS("test")) as ipdb_ns:
    print(ipdb_ns)
```

Expected result (what happens when not in chroot):
```
<pyroute2.ipdb.main.IPDB object at 0x7ffoobar>
```
Actual result (what happens in chroot):
```python
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    with IPDB(nl=NetNS("test")) as ipdb_ns:
  File "/home/name/.virtualenvs_32b/test-oS4OC6Nn/lib/python3.6/site-packages/pyroute2/netns/nslink.py", line 193, in __init__
    super(NetNS, self).__init__()
  File "/home/name/.virtualenvs_32b/test-oS4OC6Nn/lib/python3.6/site-packages/pyroute2/netlink/nlsocket.py", line 296, in __init__
    super(NetlinkMixin, self).__init__()
  File "/home/name/.virtualenvs_32b/test-oS4OC6Nn/lib/python3.6/site-packages/pyroute2/remote/__init__.py", line 253, in __init__
    raise init['error']
OSError: [Errno 22] failed to open netns: 'test'
```

I haven't tested a 64b host with a 64b chroot.

**Comment by itdaniher** [comment]
arm64 host running an [ubuntu 18.04 beta arm64 chroot](http://cdimage.ubuntu.com/ubuntu-base/releases/18.04/beta-2/ubuntu-base-18.04-beta2-base-arm64.tar.gz) worked fine. Do you know if pyroute2 make any architecture width assumptions that might be relevant, @svinota?

**Comment by itdaniher** [comment]
A stock Ubuntu 18.04 armhf (32b) chroot worked perfectly fine, the first try....

Trying to reproduce on 16.04 armhf.

**Comment by itdaniher** [comment]
Okay, took me ages to figure this one out....

Only fails running in a chroot with sudo. Running as the root user suceeds. sudo su fails.

**Comment by svinota** [comment]
Interesting. Thanks, I'll try to reproduce

**Comment by itdaniher** [comment]
doing more digging - it's a failure in setns (from pyroute/netns/__init__.py) that seems to be specific to (the invoking privileges and?) the architecture.

failing call
```
ip netns add test4
<enter 32b chroot>
sudo python test.py test4
```

succeeding call
```
<enter 32b chroot>
ip netns add test5
sudo python test.py test5
```

They pass the same argument tuple of `(__NR_setns, nsfd, CLONE_NEWNET)` to `libc.syscall`, but the syscall fails trying to manipulate a network namespace created in a 64b host from inside the 32b namespace.

Please excuse my confusion as I've been working to debug this, gaining new familiarity with the implementation of pyroute2 and I've had some missteps along the way.
