### ISSUE TITLE
With IPDB callbacks in use, mass adding and removal of routes cause crash

### ISSUE THREAD

**Issue by crosser** [svinota/pyroute2#484]
pyroute2 from today's github master (dc8aa5b), Python 3.5.

With open IPDB and registered callback, I add a few thousand routes. All events are eventually processed (very slowly, see separate ticket). Then I remove all the routes, e.g. by flushing the appropriate kernel table. Then this happens:

```
2018-04-17 14:04:52,802 - ERROR - Restarting IPDB instance after error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/main.py", line 1291, in serve_forever
    messages = self.mnl.get()
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/nlsocket.py", line 718, in get
    data = self.recv_ft(bufsize)
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/nlsocket.py", line 973, in recv_plugin
    raise data_in
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/nlsocket.py", line 514, in async_recv
    self._sock.recv_into(data, 64000)
OSError: [Errno 105] No buffer space available

2018-04-17 14:04:52,804 - ERROR - Error restarting DB:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/main.py", line 1291, in serve_forever
    messages = self.mnl.get()
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/nlsocket.py", line 718, in get
    data = self.recv_ft(bufsize)
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/nlsocket.py", line 973, in recv_plugin
    raise data_in
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/nlsocket.py", line 514, in async_recv
    self._sock.recv_into(data, 64000)
OSError: [Errno 105] No buffer space available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/main.py", line 1306, in serve_forever
    self.initdb()
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/main.py", line 854, in initdb
    self.release(complete=False)
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/main.py", line 1032, in release
    self._mthread.join()
  File "/usr/lib/python3.5/threading.py", line 1051, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

After that, I hit Ctrl-C twice (I catch KeryboardInterrupt in the master thread, and try to unregister callback and close IPDB), and it results in this:

```
^C2018-04-17 14:04:57,499 - INFO - Keyboard interrupt, stop   <<<--- My message
^C2018-04-17 14:04:57,683 - ERROR - Uncaught exception
Traceback (most recent call last):
  File "pb_route6to4.py", line 269, in <module>
    main()
  File "pb_route6to4.py", line 256, in main
    ipdb.unregister_callback(cuid)
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/main.py", line 995, in unregister_callback
    with safe.lock:
KeyboardInterrupt
```

**Comment by crosser** [comment]
I think that one of the problems manifesting here is that the IPDB.release() in pyroute2/ipdb/main.py:1002 can be called by atexit (cleanup() in __init__()) while the thread is sitting inside release(), presumabliy(?) in `self._mthread.join()`, waiting for thousands of queued events to be processed. It would seem that clearing the queue and killing all threads is a right thing to do here?

Plus, could the large amount of callback threads be causing the symptoms of #483 ?

**Comment by svinota** [comment]
Yep, it's possible. Pls excuse the reaction time, a bit overloaded at the main work now.

Investigating

**Comment by crosser** [comment]
The problems with reinitialization of an IPDB() instance are, strictly speaking, unrelated to the threading callbacks. Though as I understand, you did a cleanup of reinitialization code, so it makes sense to close as "probably fixed, and there is no way to verify".

**Comment by svinota** [comment]
At least there are no more callback threads in IPDB at all. And yes, the reinitialization is reworked.
