### ISSUE TITLE
self.ipdb.routes.filter({'oif': self['index']}) "RuntimeError: dictionary changed size during iteration"

### ISSUE THREAD

**Issue by crosser** [svinota/pyroute2#494]
In the same use case that is described in #483 and #484 , I am running a simple IPBD transaction (adding an IP address to an interface) inside the callback. When I have about ~2000 events queued, and first of them are being processed, I sometimes get this:

```
Exception in thread IPDB callback 140040056085360:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/pyroute2/ipdb/main.py", line 968, in safe
    callback(*argv, **kwarg)
  File "pb_route6to4.py", line 178, in evhandler
    routevent(action, dict(msg['attrs']))
  File "pb_route6to4.py", line 164, in routevent
    iface.commit(tid)
  File "/usr/lib/python3/dist-packages/pyroute2/ipdb/interfaces.py", line 653, in commit
    for record in self.ipdb.routes.filter({'oif': self['index']}):
  File "/usr/lib/python3/dist-packages/pyroute2/ipdb/routes.py", line 1186, in filter
    ret.extend(table.filter(target))
  File "/usr/lib/python3/dist-packages/pyroute2/ipdb/routes.py", line 835, in filter
    for record in self.idx.values():
RuntimeError: dictionary changed size during iteration
```

The code in my `routevent()` looks like this:
```
tid = iface.begin()   # iface is a global variable representing an interface
...
iface.add_ip(str(dstv4), 32)
...
iface.commit(tid)
```

**Comment by crosser** [comment]
This could be the effect of monitoring thread trying to modify routes dict in parallel with multiple callback threads doing the same.
I never observe this problem when processing is performed via eventloop interface as per merge request 499. Maybe only because the supposed race condition is not hammered as aggressively.
