### ISSUE TITLE
IPDB: failing rollback in case of failed commit diagnostic is inadequate

### ISSUE THREAD

**Issue by crosser** [svinota/pyroute2#497]
When using IPDB, if commit() fails for some reason (maybe ENOBUFS on the netlink socket?), implicit rollback is attempted. However, in my tests, rollback fails as well, and in such case diagnostic in the exception does not contain the original issue, making it rather difficult to troubleshoot:

```
2018-05-08 13:47:16,184 - ERROR - Uncaught exception
Traceback (most recent call last):
  File "pb_route6to4.py", line 275, in <module>
    while main():
  File "pb_route6to4.py", line 251, in main
    initial_sync()
  File "pb_route6to4.py", line 222, in initial_sync
    iface.commit(tid)
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ipdb/interfaces.py", line 1075, in commit
    raise error
RuntimeError
```
Here is the offending code:
```
            # something went wrong: roll the transaction back
            if commit_phase == 1:
                if newif:
                    drop = False
                try:
                    self.commit(transaction=init if newif else snapshot,
                                commit_phase=2,
                                commit_mask=commit_mask,
                                newif=newif)

                except Exception as i_e:
                    debug['next_stage'] = i_e
                    error = RuntimeError()
```
Later, this "empty" error is raised.

**Comment by svinota** [comment]
In the case of the rollback error the initial exception is stored in the rollback exception, but it's not obvious neither easy to use. So the time come to redesign that so the initial exception will be raised. Thanks for the issue.
