### ISSUE TITLE
IPDB: main thread is not notified when monitor thread crashes

### ISSUE THREAD

**Issue by crosser** [svinota/pyroute2#498]
When monitor thread crashes, main thread (i.e. the user program) has no way to know about that, so it continues to run unaware of the problem.

One crash scenario is when IPDB instance reinitialization is attempted, e.g. after an error on the netlink socket. In such case, shutting down is attempted from the monitor thread, that includes joining `self._mthread` which is the currently running thread, so another exception is raised, terminating the monitor thread.  There may be other scenarios.

**Comment by svinota** [comment]
Bug. Thanks!

**Comment by crosser** [comment]
I definitely saw diagnostic to the effect "cannot join own thread", but in any case: reinitializing IPDB never succeeded in my tests.
I think that I had it when `atexit` called `cleanup()` (pyroute2/ipdb/main.py:840), and `cleanup()` calls `release()`, which it turn tries to `join()` `_mthread` at the line 1031.

**Comment by svinota** [comment]
```
ERROR:pyroute2.ipdb.main:Error restarting DB:
Traceback (most recent call last):
  File "pyroute2/ipdb/main.py", line 1307, in serve_forever
    self.initdb()
  File "pyroute2/ipdb/main.py", line 854, in initdb
    self.release(complete=False)
  File "pyroute2/ipdb/main.py", line 1033, in release
    self._mthread.join()
  File "/usr/lib64/python2.7/threading.py", line 934, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

**Comment by svinota** [comment]
Yep. Fixing

**Comment by svinota** [comment]
Should be a bit better now. More fixes will follow.

**Comment by crosser** [comment]
AFAIK notification of another thread  cannot be done cleanly without a queue (or something similar) that would require someone in the main thread to check it.

Perhaps this can be left as it is now: when queue is in use, the reader is notified about (at least some of) the problems in the monitor thread, and when queue is not in use, monitor thread tries to revive itself.

On these grounds, I suggest to close it.
