### ISSUE TITLE
pyroute2.NetNS leaks FDs on non-existing Network Namespace

### ISSUE THREAD

**Issue by edwardbadboy** [svinota/pyroute2#501]
Hi, recently I found a problem in the instantiating code of `pyroute2.NetNS`.

It's like
```
class NetNS(IPRouteMixin, RemoteSocket):
    def __init__(self, netns, flags=os.O_CREAT):
        self.netns = netns
        self.flags = flags
        self.cmdch, self._cmdch = config.MpPipe()
        self.brdch, self._brdch = config.MpPipe()
        atexit.register(self.close)
        self.server = config.MpProcess(target=NetNServer,
                                       args=(self.netns,
                                             self._cmdch,
                                             self._brdch,
                                             self.flags))
        self.server.start()
        super(NetNS, self).__init__()
        self.marshal = MarshalRtnl()
```

If the given Network Namespaces does not exist, then an OSError would be raised from the line `super(NetNS, self).__init__()`, for example:

```
>>> import pyroute2
>>> with pyroute2.NetNS('aaa') as ns:
...     print ns
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netns/nslink.py", line 193, in __init__
    super(NetNS, self).__init__()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 296, in __init__
    super(NetlinkMixin, self).__init__()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/remote/__init__.py", line 253, in __init__
    raise init['error']
OSError: [Errno 1] mount rundir failed: 'aaa'
```

Then `self.cmdch` and self.`brdch` would remain open in this case, so FDs are leaked.

`self.cmdch` and `self.brdch` should be deleted and the FD should be closed automatically when the NetNS object is destroyed. However by using  `atexit.register(self.close)`, each instantiating of the class would keep a bound method in `atexit._exithandlers`, so there are reference to `self` of this bound method and `self.cmdch` and `self.brdch` are kept by `self`.

Even if a successful invocation of NetNS instantiation with a successful `close()` will leave a bounded method registered in atexit. I think it's kind of memory leak:
```
>>> import pyroute2
>>> import atexit
>>> with pyroute2.NetNS('nsx-node-agent') as ns: print ns
...
<pyroute2.netns.nslink.NetNS object at 0x7f1c1a9d2950>
>>> atexit._exithandlers
[(<function shutdown at 0x7f1c1d31ae60>, (), {}), (<function _exit_function at 0x7f1c1aeb5b18>, (), {}), (<bound method NetNS.close of <pyroute2.netns.nslink.NetNS object at 0x7f1c1a9d2950>>, (), {}), (<bound method NetNS.close of <pyroute2.netns.nslink.NetNS object at 0x7f1c1a9d2950>>, (), {})]
```

A small script to reproduce the problem is as following.

```
# How to use: run "ulimit -n 1024" in shell first to make the script running out FDs faster
# then run the script in the same shell
import pyroute2

while True:
    try:
        with pyroute2.NetNS('aaa') as ns:
            print ns
    except OSError as e:
        if e.errno == 1:
            pass
        else:
            raise
```

It will output error like:

```
Traceback (most recent call last):
  File "t.py", line 5, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netns/nslink.py", line 185, in __init__
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 107, in Pipe
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 191, in Pipe
OSError: [Errno 24] Too many open files
```

**Comment by svinota** [comment]
Yep. Thanks, fixing!

**Comment by edwardbadboy** [comment]
Hi @svinota , thanks a lot for reviewing the issue so quickly.

Do you need my help? I can draft a patch and a pull request. If you already started coding or have bigger plans to do some refactoring, then I'll just wait.

**Comment by svinota** [comment]
Yep, your PRs are welcome :) so I focus on other bugs then.

Thanks!
