### ISSUE TITLE
NetlinkError: (16, 'Device or resource busy')

### ISSUE THREAD

**Issue by kissgyorgy** [svinota/pyroute2#535]
On latest Ubuntu bionic kernels 4.15.0-29 and 4.15.0-30, we get these Exceptions a lot of the time:

```
test_ipdb.TestExplicit.test_ipv6_dummy ... Exception in thread IPDB main event loop:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/walkman/Upstream/pyroute2/tests/pyroute2/ipdb/main.py", line 1442, in _serve_main
    func(msg)
  File "/home/walkman/Upstream/pyroute2/tests/pyroute2/ipdb/routes.py", line 1137, in load_netlink
    self.tables[table].load(msg)
  File "/home/walkman/Upstream/pyroute2/tests/pyroute2/ipdb/routes.py", line 961, in load
    self[key] = msg
  File "/home/walkman/Upstream/pyroute2/tests/pyroute2/ipdb/routes.py", line 973, in __setitem__
    record['route'].load_netlink(value)
  File "/home/walkman/Upstream/pyroute2/tests/pyroute2/ipdb/routes.py", line 289, in load_netlink
    family=self['family'])
  File "/home/walkman/Upstream/pyroute2/tests/pyroute2/iproute/linux.py", line 1560, in route
    callback=callback)
  File "/home/walkman/Upstream/pyroute2/tests/pyroute2/netlink/nlsocket.py", line 351, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/home/walkman/Upstream/pyroute2/tests/pyroute2/netlink/nlsocket.py", line 832, in nlm_request
    callback=callback):
  File "/home/walkman/Upstream/pyroute2/tests/pyroute2/netlink/nlsocket.py", line 354, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/home/walkman/Upstream/pyroute2/tests/pyroute2/netlink/nlsocket.py", line 675, in get
    raise msg['header']['error']
NetlinkError: (16, 'Device or resource busy')
```

It's very flaky, the first time after reboot, it never appears, but after that we can reproduce it, but not always the same test.
In my current test run (`make test` on pyroute 0.5.2 tag), it affects `test_ipdb.TestExplicit.test_ipv6_dummy`, `test_ipdb.TestImplicit.test_ipv6_bridge`, but it is not always an IPv6 problem, sometimes it's during setting MTU.

The same happens running in a Docker container (with the same kernel). It never happened on a xenial kernel (4.4.0-*) AFAIK.

Our pyroute2 version is 0.5.2.

I tried to increase the `transactional.SYNC_TIMEOUT` to 30 seconds as described in https://github.com/svinota/pyroute2/issues/301, but there is no difference.

If you need anything else, let me know.

**Comment by svinota** [comment]
Looks bad. Thanks for reporting.

**Comment by kissgyorgy** [comment]
We investigated this further, [here is an strace log](https://walkman.cloud/s/EpKwMcF2Hxe34XB) (can't attach it because it's too big) from the 0.5.2 testsuite run. Here are some relevant parts in it:
```
2947  sendto(5, {{len=24, type=RTM_GETADDR, flags=NLM_F_REQUEST|NLM_F_DUMP, seq=266, pid=2947}, {ifa_family=AF_INET6, i
fa_prefixlen=0, ifa_flags=0, ifa_scope=RT_SCOPE_UNIVERSE, ifa_index=0}}, 24, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_gro
ups=00000000}, 12 <unfinished ...>
18458 sendto(5, {{len=56, type=RTM_GETROUTE, flags=NLM_F_REQUEST|NLM_F_DUMP, seq=265, pid=2947}, {rtm_family=AF_INET6, 
rtm_dst_len=8, rtm_src_len=0, rtm_tos=0, rtm_table=RT_TABLE_LOCAL, rtm_protocol=RTPROT_UNSPEC, rtm_scope=RT_SCOPE_UNIVE
RSE, rtm_type=RTN_UNSPEC, rtm_flags=0}, [{{nla_len=8, nla_type=RTA_TABLE}, RT_TABLE_LOCAL}, {{nla_len=20, nla_type=RTA_
DST}, ff00::}]}, 56, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12 <unfinished ...>
2947  <... sendto resumed> )            = 24
18458 <... sendto resumed> )            = 56
18458 futex(0x55f7766de320, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
2947  futex(0x55f7766de320, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
18458 <... futex resumed> )             = -1 EAGAIN (Resource temporarily unavailable)
2947  <... futex resumed> )             = 0
2947  futex(0x55f7766de320, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
18458 futex(0x55f7766de320, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
2947  <... futex resumed> )             = -1 EAGAIN (Resource temporarily unavailable)
18458 <... futex resumed> )             = 0
18458 futex(0x55f7766de320, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
2947  futex(0x55f7766de320, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
18458 <... futex resumed> )             = -1 EAGAIN (Resource temporarily unavailable)
2947  <... futex resumed> )             = 0
2947  futex(0x55f7766de320, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
18458 futex(0x55f7766de320, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
2947  <... futex resumed> )             = 0
18458 <... futex resumed> )             = 1
18458 futex(0x55f7766de320, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
2947  futex(0x55f7766de320, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
18458 <... futex resumed> )             = -1 EAGAIN (Resource temporarily unavailable)
2947  <... futex resumed> )             = 0
2947  recvfrom(5, [{{len=72, type=RTM_NEWADDR, flags=NLM_F_MULTI, seq=266, pid=2938917038}, {ifa_family=AF_INET6, ifa_prefixlen=128, ifa_flags=IFA_F_PERMANENT, ifa_scope=RT_SCOPE_HOST, ifa_index=if_nametoindex("lo")}, [{{nla_len=20, nla_type=IFA_ADDRESS}, ::1}, {{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=4294967295, ifa_valid=4294967295, cstamp=1137, tstamp=1137}}, {{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_PERMANENT}]}, {{len=72, type=RTM_NEWADDR, flags=NLM_F_MULTI, seq=266, pid=2938917038}, {ifa_family=AF_INET6, ifa_prefixlen=64, ifa_flags=IFA_F_SECONDARY, ifa_scope=RT_SCOPE_SITE, ifa_index=if_nametoindex("enp0s31f6")}, [{{nla_len=20, nla_type=IFA_ADDRESS}, fec0::a030:7965:af05:9dac:6bc}, {{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=49310, ifa_valid=568168, cstamp=582301, tstamp=4240533}}, {{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_SECONDARY}]}, {{len=72, type=RTM_NEWADDR, flags=NLM_F_MULTI, seq=266, pid=2938917038}, {ifa_family=AF_INET6, ifa_prefixlen=64, ifa_flags=0, ifa_scope=RT_SCOPE_SITE, ifa_index=if_nametoindex("enp0s31f6")}, [{{nla_len=20, nla_type=IFA_ADDRESS}, fec0::a030:31ad:81a:4c7a:54de}, {{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=604750, ifa_valid=2591950, cstamp=582301, tstamp=4240533}}, {{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_MANAGETEMPADDR|IFA_F_NOPREFIXROUTE}]}, {{len=72, type=RTM_NEWADDR, flags=NLM_F_MULTI, seq=266, pid=2938917038}, {ifa_family=AF_INET6, ifa_prefixlen=64, ifa_flags=IFA_F_PERMANENT, ifa_scope=RT_SCOPE_LINK, ifa_index=if_nametoindex("enp0s31f6")}, [{{nla_len=20, nla_type=IFA_ADDRESS}, fe80::e69f:d4cd:19e1:3fb0}, {{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=4294967295, ifa_valid=4294967295, cstamp=582123, tstamp=4240533}}, {{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_PERMANENT|IFA_F_NOPREFIXROUTE}]}, {{len=72, type=RTM_NEWADDR, flags=NLM_F_MULTI, seq=266, pid=2938917038}, {ifa_family=AF_INET6, ifa_prefixlen=64, ifa_flags=IFA_F_PERMANENT, ifa_scope=RT_SCOPE_LINK, ifa_index=if_nametoindex("wlp1s0")}, [{{nla_len=20, nla_type=IFA_ADDRESS}, fe80::7f6c:accf:3fd7:e92c}, {{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=4294967295, ifa_valid=4294967295, cstamp=704000, tstamp=704169}}, {{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_PERMANENT|IFA_F_NOPREFIXROUTE}]}, {{len=72, type=RTM_NEWADDR, flags=NLM_F_MULTI, seq=266, pid=2938917038}, {ifa_family=AF_INET6, ifa_prefixlen=64, ifa_flags=IFA_F_PERMANENT, ifa_scope=RT_SCOPE_LINK, ifa_index=if_nametoindex("docker0")}, [{{nla_len=20, nla_type=IFA_ADDRESS}, fe80::42:ecff:fec3:57b}, {{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=4294967295, ifa_valid=4294967295, cstamp=33060, tstamp=33060}}, {{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_PERMANENT}]}, {{len=72, type=RTM_NEWADDR, flags=NLM_F_MULTI, seq=266, pid=2938917038}, {ifa_family=AF_INET6, ifa_prefixlen=64, ifa_flags=IFA_F_PERMANENT, ifa_scope=RT_SCOPE_LINK, ifa_index=if_nametoindex("vnet0")}, [{{nla_len=20, nla_type=IFA_ADDRESS}, fe80::fc54:ff:fef1:141f}, {{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=4294967295, ifa_valid=4294967295, cstamp=1541288, tstamp=1541288}}, {{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_PERMANENT}]}, {{len=72, type=RTM_NEWADDR, flags=NLM_F_MULTI, seq=266, pid=2938917038}, {ifa_family=AF_INET6, ifa_prefixlen=64, ifa_flags=IFA_F_TENTATIVE|IFA_F_PERMANENT, ifa_scope=RT_SCOPE_UNIVERSE, ifa_index=if_nametoindex("pr9037ce44")}, [{{nla_len=20, nla_type=IFA_ADDRESS}, fdb3:84e5:4ff4:55e4::1}, {{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=4294967295, ifa_valid=4294967295, cstamp=4245547, tstamp=4245547}}, {{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_TENTATIVE|IFA_F_PERMANENT}]}], 16384, 0, NULL, NULL) = 576
18458 select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=1000} <unfinished ...>
2947  recvfrom(5, {{len=76, type=NLMSG_ERROR, flags=0, seq=265, pid=2938917038}, {error=-EBUSY, msg={{len=56, type=RTM_GETROUTE, flags=NLM_F_REQUEST|NLM_F_DUMP, seq=265, pid=2947}, {rtm_family=AF_INET6, rtm_dst_len=8, rtm_src_len=0, rtm_tos=0, rtm_table=RT_TABLE_LOCAL, rtm_protocol=RTPROT_UNSPEC, rtm_scope=RT_SCOPE_UNIVERSE, rtm_type=RTN_UNSPEC, rtm_flags=0}, [{{nla_len=8, nla_type=RTA_TABLE}, RT_TABLE_LOCAL}, {{nla_len=20, nla_type=RTA_DST}, ff00::}]}}}, 16384, 0, NULL, NULL) = 76
2947  recvfrom(5, {{len=20, type=NLMSG_DONE, flags=NLM_F_MULTI, seq=266, pid=2938917038}, 0}, 16384, 0, NULL, NULL) = 20
18458 <... select resumed> )            = 0 (Timeout)
18458 futex(0x55f7766de320, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
2947  futex(0x55f7766de320, FUTEX_WAKE_PRIVATE, 1) = 1

```
The error code 16 coming from linux kernel is `EBUSY`, it looks like we get this in response(?) to `RTM_GETROUTE` (this run of the test suite, but it might appear somewhere else too, I'm not sure). It can come from [`ip6mr.c`](https://github.com/torvalds/linux/blob/master/net/ipv6/ip6mr.c#L1737-L1738) and multiple places from [`af_netlink.c`](https://github.com/torvalds/linux/blob/a8c199208cd68cc2d71684d84e37e3b56a2ae640/net/netlink/af_netlink.c) (it might come from more, we just got to these places)

I suspect something changed in the linux kernel, so we searched for EBUSY entries in the kernel changelog for EBUSY entries, but found no relevant changes so far.

Do you have ideas what/where we should look further?

**Comment by svinota** [comment]
The main question is that: is it an optimization in the kernel that allows now to send RTNL requests more often, but returns EBUSY if it's not ready to answer (so we could handle that at the `nlm_request()` level simply repeating the request), or is it a particular/corner case that must not be generalized.

I'll try to look into the IPv6 routing code.

**Comment by kissgyorgy** [comment]
> I'll try to look into the IPv6 routing code.

We found this:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv6/ip6mr.c?id=95f4a45de1a0f172b35451fc52283290adb21f6e#n1780
(on Github: https://github.com/torvalds/linux/blob/master/net/ipv6/ip6mr.c#L1739)

but we had a box where the kernel parameter `CONFIG_IPV6_MROUTE_MULTIPLE_TABLES` were turned off, but I still could reproduce it.

We noticed it is probably happening after `RTM_GETROUTE` for ipv6 only. (When we removed IPv6 address manipulation from our test suite, we could not reproduce it.)

I also found another discussion where they were discussing the solution of waiting for 300ms and repeating the call if got EBUSY, but I can't find the url again.

**Comment by kissgyorgy** [comment]
I also found these about received message buffer size, but I don't know if they are relevant in this specific case: 
http://lists.openwall.net/netdev/2007/03/06/214
https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/commit/?id=d35c99ff77ecb2eb239731b799386f3b3637a31e

**Comment by tobias-urdin** [comment]
Subscribing, might be the same as happening on CentOS with kernel 4.18 and pyroute2 0.4.21
https://bugs.launchpad.net/neutron/+bug/1795280

**Comment by tomkcook** [comment]
I'm seeing the same on debian-armhf with a 4.4.50 kernel.  I have a patch that works around it in nlm_request that I'll submit as a pull request today.

**Comment by discostur** [comment]
Saw this today on RHEL 8 with Kernel `4.18.0-372.26.1.el8_6.x86_64`

**Comment by svinota** [comment]
@discostur that was why IPDB became deprecated: it was impossible to make it reliable.

What are the reasons why NDB is not an option in your case?
