### ISSUE TITLE
Create a new Virtual Network Interface

### ISSUE THREAD

**Issue by y-luis** [svinota/pyroute2#536]
Following [this old answer](https://stackoverflow.com/a/28564981/3286487), I get this:

```
>>> from pyroute2 import IPRoute, IPDB
>>> ip = IPRoute()
>>> index = ip.link_lookup(ifname='enp0s8')[0]
>>> ip.addr('add', index, address='10.22.22.190', mask=32)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pyroute2/iproute/linux.py", line 1227, in addr
    terminate=lambda x: x['header']['type'] ==
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 351, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 832, in nlm_request
    callback=callback):
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 354, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 675, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (1, 'Operation not permitted')
```

Is still possible to add a virtual network interface using **pyroute2**?

**Comment by ffourcot** [comment]
Hello,

You need to be root or to have CAP_NET_ADMIN as user to run this code.
