### ISSUE TITLE
Calling IPRoute.link in Multi-thread Programme Triggers NetlinkError: (9, 'Bad file descriptor')

### ISSUE THREAD

**Issue by edwardbadboy** [svinota/pyroute2#547]
Hi,
We use pyroute2 with python multiprocessing.pool.ThreadPool. We found that sometimes IPRoute.link triggers exception NetlinkError: (9, 'Bad file descriptor').

Reproduce steps:
kernel versions:
  3.10.0-862.3.3.el7.x86_64
  4.4.0-128-generic #154~14.04.1-Ubuntu
pyroute2 version: 0.5.3

Here is the sample script to reproduce the problem.

```
import logging
import os
import sys
import time
import traceback

import pyroute2
from pyroute2 import netns

from multiprocessing import pool


def worker(netns_path, work_index):
    with pyroute2.IPRoute() as ip, pyroute2.NetNS(netns_path) as ns:
        try:
            veth_outside = 'veth%s-o' % work_index
            veth_inside = 'veth%s-i' % work_index
            ip.link('add', ifname=veth_outside, kind='veth', peer=veth_inside)
            veth_outside_idx = ip.link_lookup(ifname=veth_outside)[0]
            ip.link('set', index=veth_outside_idx, state='up')
            veth_inside_idx = ip.link_lookup(ifname=veth_inside)[0]
            ip.link('set', index=veth_inside_idx, net_ns_fd=netns_path)
            veth_inside_idx = ns.link_lookup(ifname=veth_inside)[0]
            ns.link('set', index=veth_inside_idx, state='up')
        except Exception:
            logging.exception(
                '%s error setting namespace for %s', os.getpid(), veth_inside)
        finally:
            if veth_outside_idx is not None:
                ip.link('del', index=veth_outside_idx)


def main():
    logging.basicConfig(level=logging.DEBUG)
    worker_pool = pool.ThreadPool(64)

    ns_names = ['testns%i' % i for i in range(5)]
    for ns_name in ns_names:
        pyroute2.NetNS(ns_name)

    while True:
        for i, ns_name in enumerate(ns_names):
            worker_pool.apply_async(
                worker, args=(netns._get_netnspath(ns_name), i))
        time.sleep(5)


if __name__ == '__main__':
    main()
```

It usually prints the following exception after several seconds.

```
ERROR:root:143448 error setting namespace for veth0-i
Traceback (most recent call last):
  File "race.py", line 22, in worker
    ip.link('set', index=veth_inside_idx, net_ns_fd=netns_path)
  File "/home/edward/pyroute2-race/lib/python2.7/site-packages/pyroute2/iproute/linux.py", line 1115, in link
    msg_flags=msg_flags)
  File "/home/edward/pyroute2-race/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 352, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/home/edward/pyroute2-race/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 836, in nlm_request
    callback=callback):
  File "/home/edward/pyroute2-race/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 355, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/home/edward/pyroute2-race/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 679, in get
    raise msg['header']['error']
NetlinkError: (9, 'Bad file descriptor')
```

After some investigation we found some clues.

strace shows that when a thread A opens the full path of "/var/run/netns/testnsX" and gets an FD, another thread B interrupts and closes that FD. Then when thread A sends the FD to the kernel via netlink socket, kernel replies 'Bad file descriptor' (error code 9 is EBADF).

This might because of the following factors combining together.

1. `netlink/rtnl/ifinfmsg/__init__.py`
In class netns_fd, when doing encode, if it finds that self.value is an absolute path, it tries to open the path and get an FD, and register a cleanup callback to close that FD.

2. netlink/nlsocket.py
In class NetlinkMixin, self.addr_pool = AddrPool(minaddr=0x000000ff, maxaddr=0x0000ffff), so each netlink socket of the respective thread gets a separated AddrPool. This means the msg_seq always starts from 0xff in each thread.

3. `netlink/__init__.py`
clean_cbs = {}
The clean_cbs is a global variable. In the implementation of register_clean_cb(), it uses the sequence number as the key, and appends to existing callbacks. "clean_cbs[seq].append(cb)"

So if two threads happens to have the same seq number, they'll all register the FD under the same clean_cbs[seq]. When the a thread tries to decode kernel response message, it calls all callbacks under that seq, and thus closes all the related FDs including FDs used by other threads.

This means pyroute2 is not safe to be used in multi-thread programme. I'd suggest to use thread local to store clean_cbs to solve the problem.

**Comment by edwardbadboy** [comment]
A quick & dirty patch on netlink/__init__.py seems solves the problem.

```
--- lib/python2.7/site-packages/pyroute2/netlink/__init__.py    2018-10-09 14:57:16.879945000 +0800
+++ lib/python2.7/site-packages/pyroute2/netlink/__init__.py        2018-10-09 14:58:44.245973485 +0800
@@ -388,6 +388,7 @@

 import weakref
 import traceback
+import threading
 import logging
 import struct
 import types
@@ -565,7 +566,7 @@

 NETLINK_LISTEN_ALL_NSID = 8

-clean_cbs = {}
+clean_cbs = threading.local()

 # Cached results for some struct operations.
 # No cache invalidation required.
@@ -730,10 +731,10 @@
         else:
             # get the msg_seq -- if applicable
             seq = self.get('header', {}).get('sequence_number', None)
-            if seq is not None and seq not in clean_cbs:
-                clean_cbs[seq] = []
+            if seq is not None and seq not in clean_cbs.__dict__:
+                clean_cbs.__dict__[seq] = []
             # attach the callback
-            clean_cbs[seq].append(cb)
+            clean_cbs.__dict__[seq].append(cb)

     def unregister_clean_cb(self):
         global clean_cbs
@@ -741,14 +742,14 @@
         msf = self.get('header', {}).get('flags', 0)
         if (seq is not None) and \
                 (not msf & NLM_F_REQUEST) and \
-                seq in clean_cbs:
-            for cb in clean_cbs[seq]:
+                seq in clean_cbs.__dict__:
+            for cb in clean_cbs.__dict__[seq]:
                 try:
                     cb()
                 except:
                     log.error('Cleanup callback fail: %s' % (cb))
                     log.error(traceback.format_exc())
-            del clean_cbs[seq]
+            del clean_cbs.__dict__[seq]

     def _strip_one(self, name):
         for i in tuple(self['attrs']):
@@ -977,7 +978,7 @@
         else:
             self._ft_decode(self, offset)

-        if clean_cbs:
+        if clean_cbs.__dict__:
             self.unregister_clean_cb()
         self.decoded = True

```

**Comment by edwardbadboy** [comment]
Thanks svinota, do you think it might be a bug? I'm writing a workaround in the downstream project. It uses pyroute2 to manipulate net namespaces and veth devices. If this is bug I'd merge the workaround patches in the downstream project.

**Comment by svinota** [comment]
Looks like you're right, that's exactly as you said. If you provide a PR, I merge it asap.

**Comment by edwardbadboy** [comment]
Unfortunately the newly added unit test throws exception in py35, but it seems not related to the patch.
