### ISSUE TITLE
ipdb: Cannot add IPv4 route directly to interface

### ISSUE THREAD

**Issue by thardie** [svinota/pyroute2#564]
This is similar to #408 but doesn't seem to be the same cause:

```
>>> from pyroute2 import IPDB
>>> ipdb=IPDB()
>>> ipdb.routes.add(dst='103.243.14.1', oif=19).commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/routes.py", line 572, in commit
    raise error
pyroute2.ipdb.exceptions.CommitException: target family is not set
```

Running version 0.5.3

**Comment by svinota** [comment]
I believe it's fixed now
