### ISSUE TITLE
Creating vti interface using IPDB throws CommitException

### ISSUE THREAD

**Issue by darc1** [svinota/pyroute2#595]
When trying to create vti interface using IPDB I get a CommitException.
This is the code I'm running:

```
from pyroute2 import IPDB
ipdb = IPDB()
ipdb.create(ifname='vtt', kind='vti', vti_local='192.168.43.238', 
    vti_remote='5.4.3.2', vti_ikey=64, vti_okey=72)
ipdb.commit()
```

the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/test/.local/lib/python3.6/site-packages/pyroute2/ipdb/main.py", line 1358, in commit
    commit_mask=phase)
  File "/home/test/.local/lib/python3.6/site-packages/pyroute2/ipdb/interfaces.py", line 1071, in commit
    raise error
  File "/home/test/.local/lib/python3.6/site-packages/pyroute2/ipdb/interfaces.py", line 852, in commit
    transaction.wait_all_targets()
  File "/home/test/.local/lib/python3.6/site-packages/pyroute2/ipdb/transactional.py", line 507, in wait_all_targets
    raise CommitException('target %s is not set' % key)
pyroute2.ipdb.exceptions.CommitException: target vti_local is not set
```

I'm able to use IPRoute to create vti:

```
from pyroute2 import IPRoute
ipr = IPRoute()
ipr.link('add', ifname='vtt', kind='vti', vti_link=2, 
    vti_local='192.168.43.238', vti_remote='5.4.3.2', vti_ikey=64, vti_okey=72)
```
works as expected.

**Comment by svinota** [comment]
Thanks! Investigating

**Comment by svinota** [comment]
Please check if it works for you now.

**Comment by daa** [comment]
I've met the same issue for ``ip6tnl`` interface and when I added ``'ip6tnl'`` to ``supported_kinds`` manually like you've done for ``vti`` it worked.

**Comment by svinota** [comment]
I'm to fix that too, thanks.

**Comment by darc1** [comment]
it works! thanks
