### ISSUE TITLE
sqlite3 lib is required in host OS even if unused

### ISSUE THREAD

**Issue by ykvch** [svinota/pyroute2#600]
OS: FreeBSD 12 (without sqlite3 package installed at system level)
Pyhton 3.6.1

Steps:
```
import pyroute2
```

Expected:
Import done.

Actual:
```
>>> from pyroute2 import IPRoute
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/home/username/venv/lib/python3.6/site-packages/pyroute2/__init__.py", line 38, in <module>
    from pyroute2.ndb.main import NDB
  File "/usr/home/username/venv/lib/python3.6/site-packages/pyroute2/ndb/main.py", line 145, in <module>
    import sqlite3
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

Possible solutions:
* Do not import NDB to top-level (may be compatibility impact, show warning, import inside try block as alternatives).
*  Disable sqlite3 option if import fails https://github.com/svinota/pyroute2/blob/master/pyroute2/ndb/main.py#L606

**Comment by svinota** [comment]
Definitely a bug, it must not be required.

Thanks for the report, will be fixed.

**Comment by svinota** [comment]
Must be fixed. Please reopen, if it happens again.

**Comment by ykvch** [comment]
Tested pyroute2 v0.5.6 with FreeBSD 12:
```
>>> from pyroute2 import IPRoute
>>>
```
And it works flawlessly. Thank You!

**Comment by svinota** [comment]
Thanks!
