### ISSUE TITLE
Using IPBatch throws AttributeError: 'IPBatch' object has no attribute '_sendto'

### ISSUE THREAD

**Issue by evanfoster** [svinota/pyroute2#613]
Hey there!

I'm trying to use IPBatch to create a bunch of IP addresses on an interface. Unfortunately, I haven't had any luck getting IPBatch to work under any circumstances.

[Using this example from the docs:](https://docs.pyroute2.org/iproute.html#pyroute2.iproute.linux.IPBatch)
```python
from pyroute2 import IPBatch
ipb = IPBatch()
# compile requests into the internal buffer
ipb.link("add", index=550, ifname="test", kind="dummy")
ipb.link("set", index=550, state="up")
ipb.addr("add", index=550, address="10.0.0.2", mask=24)
# save the buffer
data = ipb.batch
# reset the buffer
ipb.reset()
```

This exception gets thrown:
```python
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/opt/python/lib/python3.6/site-packages/pyroute2/iproute/linux.py", line 1165, in link
    msg_flags=msg_flags)
  File "/opt/python/lib/python3.6/site-packages/pyroute2/netlink/nlsocket.py", line 352, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/opt/python/lib/python3.6/site-packages/pyroute2/netlink/nlsocket.py", line 835, in nlm_request
    self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
  File "/opt/python/lib/python3.6/site-packages/pyroute2/netlink/nlsocket.py", line 590, in put
    self.sendto_gate(msg, addr)
  File "/opt/python/lib/python3.6/site-packages/pyroute2/netlink/rtnl/iprsocket.py", line 68, in _gate_linux
    return self._sendto(ret['data'], addr)
AttributeError: 'IPBatch' object has no attribute '_sendto'
'IPBatch' object has no attribute '_sendto'
```

I'm able to reproduce this consistently across two systems:
```shell
# First system
foo-system:~ $ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
foo-system:~ $ uname -r
5.1.12-zen1-1-zen
foo-system:~ $ python --version
Python 3.7.3
foo-system:~ $ pip show pyroute2 | grep Version
Version: 0.5.6

# Second system
bar-system:~ $ cat /etc/os-release
NAME="SLES"
VERSION="12-SP2"
VERSION_ID="12.2"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP2"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp2"
bar-system:~ $ uname -r
4.4.120-92.70-default
bar-system:~ $ /opt/python/bin/python3.6 --version
Python 3.6.0
bar-system:~ $ /opt/python/bin/pip3.6 show pyroute2 | grep Version
Version: 0.5.5
```
I also tried using `pyroute2` directly from master:
```shell
pip install -U git+https://github.com/svinota/pyroute2.git@master
```
but I got the exact same result.

Please let me know if you need any other information.

**Comment by svinota** [comment]
Thanks for reporting! Fixing

**Comment by svinota** [comment]
Should be fixed now.

Thanks a lot for the report, this functionality wasn't covered by tests — that's wahy the issue came — now it should work.
