### ISSUE TITLE
NDB() change default route mtu?

### ISSUE THREAD

**Issue by DaveSeddonVDMS** [svinota/pyroute2#638]
G'day,

I hope you are well.

I'm trying to add MTU=1500 to the default route, but struggling.  Possibly the parsing of the dst is different than expected?

Can change MTU on an Ethernet interface easily enough.

```
#!/usr/bin/python3

import pyroute2

if __name__ == "__main__":
  with pyroute2.NDB() as ndb:
    (ndb
     .interfaces['enp0s31f6']
     .set('mtu', 1500)
     .commit()) #commit is implied actually, so not really needed
```
This works nicely! Thanks!

However, changing routes is harder:
```
#!/usr/bin/python3

import pyroute2

if __name__ == "__main__":
  with pyroute2.NDB() as ndb:
    with ndb.routes['default'] as route:
      route.set('mtu',1500)
      route.commit()
```

Error - Doesn't like 'default'
```
das@das-X1-4th:~/Documents/jumbos$ sudo ./python3_pyroute2_play_2019_09_20.py
Traceback (most recent call last):
  File "./python3_pyroute2_play_2019_09_20.py", line 11, in <module>
    with ndb.routes['default'] as route:
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/ndb/main.py", line 309, in __getitem__
    match_pairs=match_pairs)
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/ndb/objects/route.py", line 57, in __init__
    super(Route, self).__init__(*argv, **kwarg)
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/ndb/objects/__init__.py", line 80, in __init__
    ckey = self.complete_key(key)
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/ndb/objects/route.py", line 66, in complete_key
    ret_key['RTA_DST'], ret_key['dst_len'] = key.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
```

Does find the default route via '/0', but can't update the route.
```
#!/usr/bin/python3

import pyroute2

if __name__ == "__main__":
  with pyroute2.NDB() as ndb:
    with ndb.routes['/0'] as route:
      route.set('mtu',1500)
      route.commit()
```

```
das@das-X1-4th:~/Documents/jumbos$ sudo ./python3_pyroute2_play_2019_09_20.py
Traceback (most recent call last):
  File "./python3_pyroute2_play_2019_09_20.py", line 19, in <module>
    route.commit()
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/ndb/objects/__init__.py", line 308, in commit
    self.apply()
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/ndb/objects/route.py", line 90, in apply
    return super(Route, self).apply(rollback)
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/ndb/objects/__init__.py", line 440, in apply
    .api(self.api, method, **req))
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/ndb/source.py", line 205, in api
    return getattr(self.nl, name)(*argv, **kwarg)
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/iproute/linux.py", line 1694, in route
    ret = tuple(ret)
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/netlink/nlsocket.py", line 861, in nlm_request
    self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/netlink/nlsocket.py", line 612, in put
    self.sendto_gate(msg, addr)
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/netlink/rtnl/iprsocket.py", line 61, in _gate_linux
    msg.encode()
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/netlink/rtnl/rtmsg.py", line 704, in encode
    super(rtmsg_base, self).encode()
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/netlink/rtnl/rtmsg.py", line 35, in encode
    return super(nlflags, self).encode()
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/netlink/__init__.py", line 1073, in encode
    offset = self.encode_nlas(offset)
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/netlink/__init__.py", line 1382, in encode_nlas
    nla.encode()
  File "/home/das/.local/lib/python3.7/site-packages/pyroute2/netlink/__init__.py", line 1712, in encode
    self['value'] = inet_pton(family, self.value)
OSError: illegal IP address string passed to inet_pton
...
```

```
das@das-X1-4th:~/Documents/jumbos$ pip3 freeze | grep pyroute
pyroute2==0.5.6
das@das-X1-4th:~/Documents/jumbos$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

Thanks in advance.

Kind regards,
Dave

**Comment by svinota** [comment]
Looks like a bug in our code. Fixing.

**Comment by jsenecal** [comment]
It also fails on getting information from the default route:
``` 
In [5]: with pyroute2.NDB(log='on') as ndb: 
   ...:     with ndb.routes["/0"] as default_route: 
   ...:         print(default_route) 
   ...:                                                                                                  
2020-01-28 12:10:40,781    DEBUG pyroute2.ndb.139714640865168.sources.localhost: init
2020-01-28 12:10:40,781    DEBUG pyroute2.ndb.139714640865168.sources.localhost: starting the source
2020-01-28 12:10:40,781    DEBUG pyroute2.ndb.139714640865168.sources.localhost/netns: init
2020-01-28 12:10:40,782    DEBUG pyroute2.ndb.139714640865168.sources.localhost: connecting
2020-01-28 12:10:40,782    DEBUG pyroute2.ndb.139714640865168.sources.localhost: loading
2020-01-28 12:10:40,782    DEBUG pyroute2.ndb.139714640865168.sources.localhost/netns: starting the source
2020-01-28 12:10:40,783    DEBUG pyroute2.ndb.139714640865168.sources.localhost/netns: connecting
2020-01-28 12:10:40,839    DEBUG pyroute2.ndb.139714640865168.sources.localhost/netns: loading
2020-01-28 12:10:40,877    DEBUG pyroute2.ndb.139714640865168.sources.localhost: running
2020-01-28 12:10:40,901    DEBUG pyroute2.ndb.139714640865168.sources.localhost/netns: running
2020-01-28 12:10:40,902    DEBUG pyroute2.ndb.139714640865168.rtnl_object: init
2020-01-28 12:10:40,902    DEBUG pyroute2.ndb.139714640865168.rtnl_object: complete key {'target': 'localhost', 'RTA_DST': '', 'dst_len': '0'} from table routes
2020-01-28 12:10:40,902    DEBUG pyroute2.ndb.139714640865168.rtnl_object: got {'target': 'localhost', 'RTA_DST': '', 'dst_len': '0', 'tflags': 0, 'family': 2, 'tos': 0, 'RTA_PRIORITY': 600, 'RTA_TABLE': 254}
2020-01-28 12:10:40,903    DEBUG pyroute2.ndb.139714640865168.rtnl_object: load_sql: ('localhost', 0, 2, 0, 0, 0, 254, 16, 0, 1, 0, '', None, None, 3, '172.16.12.1', 600, None, None, None, 254, None, None, None, None, None, None)
2020-01-28 12:10:40,903    DEBUG pyroute2.ndb.139714640865168.view.routes: cache add (('target', 'localhost'), ('tflags', 0), ('family', 2), ('dst_len', 0), ('tos', 0), ('RTA_DST', ''), ('RTA_PRIORITY', 600), ('RTA_TABLE', 254))
{'multipath': [], 'target': 'localhost', 'dst': '', 'dst_len': 0, 'tflags': 0, 'family': 2, 'tos': 0, 'priority': 600, 'table': 254, 'src_len': 0, 'proto': 16, 'scope': 0, 'type': 1, 'flags': 0, 'src': None, 'iif': None, 'oif': 3, 'gateway': '172.16.12.1', 'prefsrc': None, 'protoinfo': None, 'flow': None, 'mark': None, 'newdst': None, 'pref': None, 'encap_type': None, 'route_id': None, 'gc_mark': None}
2020-01-28 12:10:40,903    DEBUG pyroute2.ndb.139714640865168.rtnl_object: commit: [(1580231440.902452, 'invalid'), (1580231440.9032965, 'system')]
2020-01-28 12:10:40,903    DEBUG pyroute2.ndb.139714640865168.rtnl_object: init
2020-01-28 12:10:40,903    DEBUG pyroute2.ndb.139714640865168.rtnl_object: complete key OrderedDict([('target', 'localhost'), ('tflags', 0), ('family', 2), ('dst_len', 0), ('tos', 0), ('RTA_DST', ''), ('RTA_PRIORITY', 600), ('RTA_TABLE', 254)]) from table routes_139714640001280
2020-01-28 12:10:40,903    DEBUG pyroute2.ndb.139714640865168.rtnl_object: got OrderedDict([('target', 'localhost'), ('tflags', 0), ('family', 2), ('dst_len', 0), ('tos', 0), ('RTA_DST', ''), ('RTA_PRIORITY', 600), ('RTA_TABLE', 254)])
2020-01-28 12:10:40,903    DEBUG pyroute2.ndb.139714640865168.rtnl_object: load_sql: ('localhost', 0, 2, 0, 0, 0, 254, 16, 0, 1, 0, '', None, None, 3, '172.16.12.1', 600, None, None, None, 254, None, None, None, None, None, None)
2020-01-28 12:10:40,906    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot interfaces_139714640001280
2020-01-28 12:10:40,907    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot addresses_139714640001280
2020-01-28 12:10:40,907    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot neighbours_139714640001280
2020-01-28 12:10:40,907    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot routes_139714640001280
2020-01-28 12:10:40,908    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot nh_139714640001280
2020-01-28 12:10:40,908    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot rules_139714640001280
2020-01-28 12:10:40,908    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot netns_139714640001280
2020-01-28 12:10:40,909    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot p2p_139714640001280
2020-01-28 12:10:40,909    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot ifinfo_bridge_139714640001280
2020-01-28 12:10:40,910    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot ifinfo_bond_139714640001280
2020-01-28 12:10:40,911    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot ifinfo_vlan_139714640001280
2020-01-28 12:10:40,912    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot ifinfo_vxlan_139714640001280
2020-01-28 12:10:40,913    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot ifinfo_gre_139714640001280
2020-01-28 12:10:40,914    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot ifinfo_vrf_139714640001280
2020-01-28 12:10:40,914    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot ifinfo_vti_139714640001280
2020-01-28 12:10:40,915    DEBUG pyroute2.ndb.139714640865168.schema: create snapshot ifinfo_vti6_139714640001280
2020-01-28 12:10:40,919    DEBUG pyroute2.ndb.139714640865168.rtnl_object: apply: [(1580231440.902452, 'invalid'), (1580231440.9032965, 'system')]
2020-01-28 12:10:40,920    DEBUG pyroute2.ndb.139714640865168.rtnl_object: load_sql: ('localhost', 0, 2, 0, 0, 0, 254, 16, 0, 1, 0, '', None, None, 3, '172.16.12.1', 600, None, None, None, 254, None, None, None, None, None, None)
2020-01-28 12:10:40,920    DEBUG pyroute2.ndb.139714640865168.rtnl_object: apply req: {'target': 'localhost', 'tflags': 0, 'family': 2, 'dst_len': 0, 'tos': 0, 'RTA_DST': '', 'RTA_PRIORITY': 600, 'RTA_TABLE': 254}
2020-01-28 12:10:40,920    DEBUG pyroute2.ndb.139714640865168.rtnl_object: apply idx_req: {'target': 'localhost', 'tflags': 0, 'family': 2, 'dst_len': 0, 'tos': 0, 'RTA_DST': '', 'RTA_PRIORITY': 600, 'RTA_TABLE': 254}
2020-01-28 12:10:40,920    DEBUG pyroute2.ndb.139714640865168.rtnl_object: apply state: system
2020-01-28 12:10:40,920    DEBUG pyroute2.ndb.139714640865168.rtnl_object: run set ({'target': 'localhost', 'tflags': 0, 'family': 2, 'dst_len': 0, 'tos': 0, 'RTA_DST': '', 'RTA_PRIORITY': 600, 'RTA_TABLE': 254})
2020-01-28 12:10:40,921    DEBUG pyroute2.ndb.139714640865168.rtnl_object: rollback: [(1580231440.902452, 'invalid'), (1580231440.9032965, 'system')]
2020-01-28 12:10:40,921    DEBUG pyroute2.ndb.139714640865168.rtnl_object: apply: [(1580231440.9035726, 'invalid'), (1580231440.9212816, 'system')]
2020-01-28 12:10:40,921    DEBUG pyroute2.ndb.139714640865168.rtnl_object: load_sql: ('localhost', 0, 2, 0, 0, 0, 254, 16, 0, 1, 0, '', None, None, 3, '172.16.12.1', 600, None, None, None, 254, None, None, None, None, None, None)
2020-01-28 12:10:40,922    DEBUG pyroute2.ndb.139714640865168.rtnl_object: apply req: {'target': 'localhost', 'tflags': 0, 'family': 2, 'dst_len': 0, 'tos': 0, 'RTA_DST': '', 'RTA_PRIORITY': 600, 'RTA_TABLE': 254}
2020-01-28 12:10:40,922    DEBUG pyroute2.ndb.139714640865168.rtnl_object: apply idx_req: {'target': 'localhost', 'tflags': 0, 'family': 2, 'dst_len': 0, 'tos': 0, 'RTA_DST': '', 'RTA_PRIORITY': 600, 'RTA_TABLE': 254}
2020-01-28 12:10:40,922    DEBUG pyroute2.ndb.139714640865168.rtnl_object: apply state: system
2020-01-28 12:10:40,922    DEBUG pyroute2.ndb.139714640865168.rtnl_object: run set ({'target': 'localhost', 'tflags': 0, 'family': 2, 'dst_len': 0, 'tos': 0, 'RTA_DST': '', 'RTA_PRIORITY': 600, 'RTA_TABLE': 254})
2020-01-28 12:10:40,922     INFO pyroute2.ndb.139714640865168.sources.localhost: source shutdown
2020-01-28 12:10:40,923    DEBUG pyroute2.ndb.139714640865168.sources.localhost: sync
2020-01-28 12:10:40,923    DEBUG pyroute2.ndb.139714640865168.sources.localhost: shutdown handled by the main thread
2020-01-28 12:10:40,923    DEBUG pyroute2.ndb.139714640865168.sources.localhost: stopped
2020-01-28 12:10:40,923    DEBUG pyroute2.ndb.139714640865168.main: flush DB for the target localhost
2020-01-28 12:10:40,924     INFO pyroute2.ndb.139714640865168.sources.localhost/netns: source shutdown
2020-01-28 12:10:40,930    DEBUG pyroute2.ndb.139714640865168.sources.localhost/netns: sync
2020-01-28 12:10:40,930    DEBUG pyroute2.ndb.139714640865168.sources.localhost/netns: shutdown handled by the main thread
2020-01-28 12:10:40,930    DEBUG pyroute2.ndb.139714640865168.sources.localhost/netns: stopped
2020-01-28 12:10:40,930    DEBUG pyroute2.ndb.139714640865168.main: flush DB for the target localhost/netns
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-5-900e60a84491> in <module>
      1 with pyroute2.NDB(log='on') as ndb:
      2     with ndb.routes["/0"] as default_route:
----> 3         print(default_route)
      4 

~/Code/exabgp-for-docker/.env/lib/python3.8/site-packages/pyroute2/ndb/objects/__init__.py in __exit__(self, exc_type, exc_value, traceback)
    259 
    260     def __exit__(self, exc_type, exc_value, traceback):
--> 261         self.commit()
    262 
    263     def __hash__(self):

~/Code/exabgp-for-docker/.env/lib/python3.8/site-packages/pyroute2/ndb/objects/__init__.py in commit(self)
    495         # Apply the changes
    496         try:
--> 497             self.apply()
    498         except Exception as e_c:
    499             # Rollback in the case of any error

~/Code/exabgp-for-docker/.env/lib/python3.8/site-packages/pyroute2/ndb/objects/route.py in apply(self, rollback)
     88             return self
     89         else:
---> 90             return super(Route, self).apply(rollback)
     91 
     92     def load_sql(self, *argv, **kwarg):

~/Code/exabgp-for-docker/.env/lib/python3.8/site-packages/pyroute2/ndb/objects/__init__.py in apply(self, rollback)
    629             try:
    630                 self.log.debug('run %s (%s)' % (method, req))
--> 631                 (self
    632                  .sources[self['target']]
    633                  .api(self.api, method, **req))

~/Code/exabgp-for-docker/.env/lib/python3.8/site-packages/pyroute2/ndb/source.py in api(self, name, *argv, **kwarg)
    191             with self.lock:
    192                 try:
--> 193                     return getattr(self.nl, name)(*argv, **kwarg)
    194                 except (NetlinkError,
    195                         AttributeError,

~/Code/exabgp-for-docker/.env/lib/python3.8/site-packages/pyroute2/iproute/linux.py in route(self, command, **kwarg)
   1864 
   1865         if not (command == RTM_GETROUTE and self.nlm_generator):
-> 1866             ret = tuple(ret)
   1867 
   1868         return ret

~/Code/exabgp-for-docker/.env/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py in nlm_request(self, msg, msg_type, msg_flags, terminate, callback)
    859             while True:
    860                 try:
--> 861                     self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
    862                     for msg in self.get(msg_seq=msg_seq,
    863                                         terminate=terminate,

~/Code/exabgp-for-docker/.env/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py in put(self, msg, msg_type, msg_flags, addr, msg_seq, msg_pid)
    610             msg['header']['sequence_number'] = msg_seq
    611             msg['header']['pid'] = msg_pid
--> 612             self.sendto_gate(msg, addr)
    613         except:
    614             raise

~/Code/exabgp-for-docker/.env/lib/python3.8/site-packages/pyroute2/netlink/rtnl/iprsocket.py in _gate_linux(self, msg, addr)
     59     def _gate_linux(self, msg, addr):
     60         msg.reset()
---> 61         msg.encode()
     62         ret = self._sproxy.handle(msg)
     63         if ret is not None:

~/Code/exabgp-for-docker/.env/lib/python3.8/site-packages/pyroute2/netlink/rtnl/rtmsg.py in encode(self)
    702                                 'RTA_MULTIPATH'):
    703                     raise TypeError('Incorrect NLA type %s for AF_MPLS' % n[0])
--> 704         super(rtmsg_base, self).encode()
    705 
    706 

~/Code/exabgp-for-docker/.env/lib/python3.8/site-packages/pyroute2/netlink/rtnl/rtmsg.py in encode(self)
     33         if isinstance(self['flags'], (set, tuple, list)):
     34             self['flags'] = self.names2flags(self['flags'])
---> 35         return super(nlflags, self).encode()
     36 
     37     def flags2names(self, flags=None):

~/Code/exabgp-for-docker/.env/lib/python3.8/site-packages/pyroute2/netlink/__init__.py in encode(self)
   1073         # write NLA chain
   1074         if self.nla_map:
-> 1075             offset = self.encode_nlas(offset)
   1076         # calculate the size and write it
   1077         if 'header' in self and self.header is not None:

~/Code/exabgp-for-docker/.env/lib/python3.8/site-packages/pyroute2/netlink/__init__.py in encode_nlas(self, offset)
   1414                 nla.setvalue(cell[1])
   1415                 try:
-> 1416                     nla.encode()
   1417                 except:
   1418                     raise

~/Code/exabgp-for-docker/.env/lib/python3.8/site-packages/pyroute2/netlink/__init__.py in encode(self)
   1757             family = self.get_family()
   1758             if family in (AF_INET, AF_INET6):
-> 1759                 self['value'] = inet_pton(family, self.value)
   1760             elif family == AF_MPLS:
   1761                 self['value'] = b''

OSError: illegal IP address string passed to inet_pton

```

This is on `pyroute2==0.5.7.post44`

**Comment by mawiegand** [comment]
Getting the same error `OSError: illegal IP address string passed to inet_pton` when trying to delete the default route.

**Comment by svinota** [comment]
Such an annoying bug was it. I hope I get rid of it. If it happens again — don't hesitate to ping me.

**Comment by mawiegand** [comment]
Thanks for the quick response!
Deletion of a default route seems to be working if I use:
```python
ndb.routes.get({'target': nsname, 'dst': ''}).remove().commit()
```
but using `default` as `dst` for example like this:
```python
ndb.routes.get({'target': nsname, 'dst': 'default'}).remove().commit()
```
doesn't work.

**Comment by svinota** [comment]
Yep, I'm already working on it. An object lookup routine has to be rewritten, will be ready tonight.

**Comment by svinota** [comment]
Quick-n-dirty version in the repo; tests and more fixes will follow tomorrow

**Comment by mawiegand** [comment]
> Quick-n-dirty version in the repo; tests and more fixes will follow tomorrow

Thanks! e06e5da fixed it.
