### ISSUE TITLE
pyroute2.ipdb.exceptions.CommitException: target state is not set

### ISSUE THREAD

**Issue by simble1986** [svinota/pyroute2#643]
## Enviroment
pyroute2==0.5.7
OS: 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
python: Python 2.7.12

## Summary

up/down an interface which is already 'up'/'down' bring exception: target state is not set

## How to reproduce

```
>>> from pyroute2 import IPDB
>>> interfaces=IPDB().interfaces
>>> interfaces['eno2']
{'brport_forward_delay_timer': 0, 'brport_bridge_id': {'addr': '84:2b:2b:4c:b1:41', 'prio': 128}, 'family': 7, 'txqlen': 1000, 'master': 11, 'ipdb_scope': 'system', 'index': 3, 'operstate': 'DOWN', 'vlans': (1,), 'group': 0, 'carrier_changes': 3, 'brport_designated_cost': 0, 'brport_state': 0, 'ipaddr': (('fe80::862b:2bff:fe4c:b141', 64),), 'state': 'up', 'brport_id': 32769, 'ifname': 'eno2', 'neighbours': (), 'carrier': 0, 'brport_cost': 4, 'linkmode': 0, 'brport_hold_timer': 0, 'brport_unicast_flood': 1, 'brport_fast_leave': 0, 'brport_priority': 32, 'promiscuity': 1, 'brport_root_id': {'addr': '84:2b:2b:4c:b1:41', 'prio': 128}, 'brport_message_age_timer': 0, 'brport_proxyarp_wifi': 0, 'brport_config_pending': 0, 'flags': 4099, 'broadcast': 'ff:ff:ff:ff:ff:ff', 'brport_topology_change_ack': 0, 'brport_protect': 0, 'address': '84:2b:2b:4c:b1:41', 'num_tx_queues': 8, 'ipdb_priority': 0, 'brport_mode': 0, 'qdisc': 'mq', 'brport_multicast_router': 1, 'brport_proxyarp': 0, 'brport_designated_port': 32769, 'mtu': 1500, 'num_rx_queues': 8, 'brport_guard': 0, 'brport_no': 1, 'ifi_type': 1, 'proto_down': 0, 'brport_learning': 1, 'ports': ()}
# current state is up
>>> interfaces['eno2']['state']
'up'
>>> interfaces['eno2'].up().commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/myipdb/local/lib/python2.7/site-packages/pyroute2/ipdb/interfaces.py", line 1078, in commit
    raise error
pyroute2.ipdb.exceptions.CommitException: target state is not set
>>> interfaces['eno2'].down().commit()
{'brport_forward_delay_timer': 0, 'brport_bridge_id': {'addr': '84:2b:2b:4c:b1:41', 'prio': 128}, 'family': 0, 'txqlen': 1000, 'master': 11, 'ipdb_scope': 'system', 'index': 3, 'operstate': 'DOWN', 'vlans': (1,), 'group': 0, 'carrier_changes': 3, 'brport_designated_cost': 0, 'brport_state': 0, 'ipaddr': (('fe80::862b:2bff:fe4c:b141', 64),), 'state': 'down', 'brport_id': 32769, 'ifname': 'eno2', 'neighbours': (), 'carrier': 0, 'brport_cost': 4, 'linkmode': 0, 'brport_hold_timer': 0, 'brport_unicast_flood': 1, 'brport_fast_leave': 0, 'brport_priority': 32, 'promiscuity': 1, 'brport_root_id': {'addr': '84:2b:2b:4c:b1:41', 'prio': 128}, 'brport_message_age_timer': 0, 'brport_proxyarp_wifi': 0, 'brport_config_pending': 0, 'flags': 4098, 'broadcast': 'ff:ff:ff:ff:ff:ff', 'brport_topology_change_ack': 0, 'brport_protect': 0, 'address': '84:2b:2b:4c:b1:41', 'num_tx_queues': 8, 'ipdb_priority': 0, 'brport_mode': 0, 'qdisc': 'mq', 'brport_multicast_router': 1, 'brport_proxyarp': 0, 'brport_designated_port': 32769, 'mtu': 1500, 'num_rx_queues': 8, 'brport_guard': 0, 'brport_no': 1, 'ifi_type': 1, 'proto_down': 0, 'brport_learning': 1, 'ports': ()}
# work well after down the interface
>>> interfaces['eno2'].up().commit()
{'brport_forward_delay_timer': 0, 'brport_bridge_id': {'addr': '84:2b:2b:4c:b1:41', 'prio': 128}, 'family': 0, 'txqlen': 1000, 'master': 11, 'ipdb_scope': 'system', 'index': 3, 'operstate': 'DOWN', 'vlans': (1,), 'group': 0, 'carrier_changes': 3, 'brport_designated_cost': 0, 'brport_state': 0, 'ipaddr': (), 'state': 'up', 'brport_id': 32769, 'ifname': 'eno2', 'neighbours': (), 'carrier': 0, 'brport_cost': 4, 'linkmode': 0, 'brport_hold_timer': 0, 'brport_unicast_flood': 1, 'brport_fast_leave': 0, 'brport_priority': 32, 'promiscuity': 1, 'brport_root_id': {'addr': '84:2b:2b:4c:b1:41', 'prio': 128}, 'brport_message_age_timer': 0, 'brport_proxyarp_wifi': 0, 'brport_config_pending': 0, 'flags': 4099, 'broadcast': 'ff:ff:ff:ff:ff:ff', 'brport_topology_change_ack': 0, 'brport_protect': 0, 'address': '84:2b:2b:4c:b1:41', 'num_tx_queues': 8, 'ipdb_priority': 0, 'brport_mode': 0, 'qdisc': 'mq', 'brport_multicast_router': 1, 'brport_proxyarp': 0, 'brport_designated_port': 32769, 'mtu': 1500, 'num_rx_queues': 8, 'brport_guard': 0, 'brport_no': 1, 'ifi_type': 1, 'proto_down': 0, 'brport_learning': 1, 'ports': ()}
>>> interfaces['eno2'].down().commit()
{'brport_forward_delay_timer': 0, 'brport_bridge_id': {'addr': '84:2b:2b:4c:b1:41', 'prio': 128}, 'family': 7, 'txqlen': 1000, 'master': 11, 'ipdb_scope': 'system', 'index': 3, 'operstate': 'DOWN', 'vlans': (1,), 'group': 0, 'carrier_changes': 3, 'brport_designated_cost': 0, 'brport_state': 0, 'ipaddr': (), 'state': 'down', 'brport_id': 32769, 'ifname': 'eno2', 'neighbours': (), 'carrier': 0, 'brport_cost': 4, 'linkmode': 0, 'brport_hold_timer': 0, 'brport_unicast_flood': 1, 'brport_fast_leave': 0, 'brport_priority': 32, 'promiscuity': 1, 'brport_root_id': {'addr': '84:2b:2b:4c:b1:41', 'prio': 128}, 'brport_message_age_timer': 0, 'brport_proxyarp_wifi': 0, 'brport_config_pending': 0, 'flags': 4098, 'broadcast': 'ff:ff:ff:ff:ff:ff', 'brport_topology_change_ack': 0, 'brport_protect': 0, 'address': '84:2b:2b:4c:b1:41', 'num_tx_queues': 8, 'ipdb_priority': 0, 'brport_mode': 0, 'qdisc': 'mq', 'brport_multicast_router': 1, 'brport_proxyarp': 0, 'brport_designated_port': 32769, 'mtu': 1500, 'num_rx_queues': 8, 'brport_guard': 0, 'brport_no': 1, 'ifi_type': 1, 'proto_down': 0, 'brport_learning': 1, 'ports': ()}
>>> interfaces['eno2'].down().commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/myipdb/local/lib/python2.7/site-packages/pyroute2/ipdb/interfaces.py", line 1078, in commit
    raise error
pyroute2.ipdb.exceptions.CommitException: target state is not set
```

**Comment by svinota** [comment]
Ough. Thanks for reporting
