### ISSUE TITLE
**pyroute2.netlink.exceptions.NetlinkError: (2, 'No such file or directory')**

### ISSUE THREAD

**Issue by mnshrr** [svinota/pyroute2#669]
running this code:
```
https://github.com/saburhb/eBPF-cast/tree/master/eBPF-switch
```
just modified the python code with the name of my interfaces and virbr0:
```
ifc = ipdb.interfaces.enp0s3
dst = ipdb.interfaces.virbr0
```

```
ebpf@ebpf-VirtualBox:~/eBPF/bcc/ME/test_ebpf$ 
ebpf@ebpf-VirtualBox:~/eBPF/bcc/ME/test_ebpf$ sudo python test_ebpf.py enp0s3 virbr0
2
2
4
OK
Traceback (most recent call last):
  File "MEtest_ebpf.py", line 48, in <module>
    ipr.tc("del", "ingress", idx, "ffff:")
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/iproute/linux.py", line 1583, in tc
    return tuple(self.nlm_request(msg, msg_type=command, msg_flags=flags))
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 373, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 864, in nlm_request
    callback=callback):
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 376, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 701, in get
    raise msg['header']['error']
**pyroute2.netlink.exceptions.NetlinkError: (2, 'No such file or directory')**
```

More info in case:
```
ebpf@ebpf-VirtualBox:~/eBPF/bcc/ME/test_ebpf$ brctl show
bridge name	bridge id		STP enabled	interfaces
virbr0		8000.08002742d9eb	no		enp0s8
ebpf@ebpf-VirtualBox:~/eBPF/bcc/ME/test_ebpf$ ifconfig
enp0s3    Link encap:Ethernet  HWaddr 08:00:27:eb:2b:bc  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::50e7:c44c:1191:5575/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8555 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3549 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:7510720 (7.5 MB)  TX bytes:496772 (496.7 KB)

enp0s8    Link encap:Ethernet  HWaddr 08:00:27:42:d9:eb  
          inet addr:192.168.0.21  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: 2601:204:c102:ed70:35ac:adee:ca65:1f97/64 Scope:Global
          inet6 addr: fe80::ceeb:de54:5e46:cfb9/64 Scope:Link
          inet6 addr: 2601:204:c102:ed70:ac3b:32a8:2c88:9cf1/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1366 errors:0 dropped:0 overruns:0 frame:0
          TX packets:454 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:144108 (144.1 KB)  TX bytes:44741 (44.7 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1240 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1240 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:118445 (118.4 KB)  TX bytes:118445 (118.4 KB)
```

**Comment by svinota** [comment]
According to the code of the script you referenced, it removes the root ingress qdisc. And yes, it will fail if there is no such qdisc installed. Probably it's enough to ignore this exception for the qdisc removal with `try/except` block, but the `eBPF-cast` project author would know better.
