### ISSUE TITLE
Conntrack with IPv6 fails with: NetlinkError 22 - Invalid argument

### ISSUE THREAD

**Issue by derbroti** [svinota/pyroute2#701]
Hi,
I am trying to use Conntrack with ipv6 but it does not work.

Versions:
`pyroute2               0.5.11`
```
Python 3.7.5 (default, Nov 20 2019, 09:21:52)
[GCC 9.2.1 20191008] on linux
```

Code to reproduce:
```
from pyroute2 import Conntrack
from pyroute2.netlink.nfnetlink.nfctsocket import NFCTAttrTuple
from socket import AF_INET6, IPPROTO_TCP
ct = Conntrack()
ct.entry('get', tuple_orig=NFCTAttrTuple(family=AF_INET6, saddr='<SRC_IP>', daddr='<DST_IP>', sport=39892, dport=80, proto=IPPROTO_TCP))
```

Result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pyroute2/netlink/nfnetlink/nfctsocket.py", line 670, in entry
    terminate=terminate_error_msg)
  File "/usr/local/lib/python3.7/dist-packages/pyroute2/netlink/nfnetlink/nfctsocket.py", line 598, in request
    return self.nlm_request(msg, msg_type, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pyroute2/netlink/nlsocket.py", line 375, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/usr/local/lib/python3.7/dist-packages/pyroute2/netlink/nlsocket.py", line 867, in nlm_request
    callback=callback):
  File "/usr/local/lib/python3.7/dist-packages/pyroute2/netlink/nlsocket.py", line 378, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/usr/local/lib/python3.7/dist-packages/pyroute2/netlink/nlsocket.py", line 703, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (22, 'Invalid argument')
```

Note: With ipv4 it works fine, and I am sure my ipv6 addresses are correct as it would otherwise complain with:
`OSError: illegal IP address string passed to inet_pton`

I am probably just missing something - any idea?

Thanks!

As a side question: How do I get dump_entries() to dump IPv6 entries as well?

**Comment by svinota** [comment]
Looks like the conntrack code of the library doesn't work with IPv6. Yet.

To be fixed asap.

**Comment by svinota** [comment]
My bad, I missed the init call.

To work with IP versions:
```python
import socket

ct = Conntrack(nfgen_family=socket.AF_INET6)
# or
ct = Conntrack(nfgen_family=socket.AF_UNSPEC)
```

By default it starts with `nfgen_family == AF_INET`, that causes this error.

**Comment by derbroti** [comment]
Now both entry and dump_entries() work, thanks!

**Comment by svinota** [comment]
Yep.
