### ISSUE TITLE
Cannot seem to create SIT tunnel

### ISSUE THREAD

**Issue by johnnybubonic** [svinota/pyroute2#703]
This may be user error, but I'm finding it pretty hard to get a SIT up both when using IPRoute and NDB.

This:
```python
from pyroute2 import IPRoute
ipr = IPRoute()
# ... tun_id is a str name, my_ip is a str ip address on the local machine, server is a str ip address for the SIT server.
ipr.link('add',
         ifname = 'tun-{0}'.format(tun_id),
         kind = 'sit',
         ipip_local = my_ip,
         ipip_remote = server,
         ipip_ttl = 255)
```

This gives a `pyroute2.netlink.exceptions.NetlinkError: (17, 'File exists')` exception:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/pyroute2/iproute/linux.py", line 1335, in link
    ret = self.nlm_request(msg,
  File "/usr/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 375, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/usr/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 865, in nlm_request
    for msg in self.get(msg_seq=msg_seq,
  File "/usr/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 378, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/usr/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 703, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (17, 'File exists')
```

The docs say:

> ...use kind=sit and sit_ as prefix for sit tunnels...

but:

1. It is unclear what is meant by "prefix" in this verbiage. Does it mean for `ifname`? Because when I change `ifname` to `ifname = 'sit_tun-{0}'.format(tun_id)` or even just `ifname = 'sit_{0}'.format(tun_id)` or (in an act of desperation) `ifname = 'sit{0}'.format(tun_id),` I still get the same exception (at the same line in nlsocket).
2. The desired link is created fine when using iproute2 via `ip tunnel add tun-<tun_id> mode sit remote <server> local <my_ip> ttl 255`.

Alternatively, I tried NDB:

```python
from pyroute2 import NDB
# ...
with NDB() as ndb:
    ndb.interfaces.create(ifname = 'tun-{0}'.format(tun_id), kind = 'sit', ipip_local = my_ip, ipip_remote = server, ipip_ttl = 255).commit()
```

but this just hangs and eventually just returns:

```python
2020-05-10 08:58:46,077     INFO pyroute2.ndb.140545464844192.sources.localhost: source shutdown
2020-05-10 08:58:46,087     INFO pyroute2.ndb.140545464844192.sources.nsmanager: source shutdown
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.8/site-packages/pyroute2/ndb/auth_manager.py", line 69, in guard
    return f(obj, *argv, **kwarg)
  File "/usr/lib/python3.8/site-packages/pyroute2/ndb/objects/__init__.py", line 564, in commit
    raise e_i
  File "/usr/lib/python3.8/site-packages/pyroute2/ndb/objects/__init__.py", line 553, in commit
    return self.apply()
  File "/usr/lib/python3.8/site-packages/pyroute2/ndb/auth_manager.py", line 69, in guard
    return f(obj, *argv, **kwarg)
  File "/usr/lib/python3.8/site-packages/pyroute2/ndb/objects/interface.py", line 558, in apply
    super(Interface, self).apply(rollback)
  File "/usr/lib/python3.8/site-packages/pyroute2/ndb/auth_manager.py", line 69, in guard
    return f(obj, *argv, **kwarg)
  File "/usr/lib/python3.8/site-packages/pyroute2/ndb/objects/__init__.py", line 757, in apply
    raise Exception('lost sync in apply()')
Exception: lost sync in apply()
```

Any ideas?

**Comment by johnnybubonic** [comment]
DUH. I just figured it out.

"use kind=sit and sit_ as prefix for sit tunnels" refers to replacing the `ipip_` prefix in *parameter names*!

Could you perhaps update the docs to clarify this? You may also want to do the same for creating `ip6gre` links as well, as it uses similar verbiage.

**Comment by svinota** [comment]
Thanks, I do that!
