### ISSUE TITLE
struct.error: unpack_from requires a buffer of at least 16292 bytes ... (actual buffer size is 16284)

### ISSUE THREAD

**Issue by christian-2** [svinota/pyroute2#711]
I am using `pyroute2 0.5.12` in a Docker container that is based on Alpine Linux 3.11 and that runs on each of a Kubernetes cluster’s nodes with`hostNetwork: true` (i.e. in the node's default network namespace). Some cluster nodes run Debian 9, others Debian 10. I am observing the following warning only in containers that are hosted on Debian 9 nodes:

```
[WARNING] decoding INET_DIAG_INFO
[WARNING] Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyroute2/netlink/__init__.py", line 1520, in try_to_decode
    cell.decode()
  File "/usr/lib/python3.8/site-packages/pyroute2/netlink/diag/__init__.py", line 226, in decode
    nla.decode(self)
  File "/usr/lib/python3.8/site-packages/pyroute2/netlink/__init__.py", line 2016, in decode
    nla_base.decode(self)
  File "/usr/lib/python3.8/site-packages/pyroute2/netlink/__init__.py", line 1016, in decode
    self._ft_decode(self, offset)
  File "/usr/lib/python3.8/site-packages/pyroute2/netlink/__init__.py", line 1335, in _ft_decode_generic
    value = struct.unpack_from(fmt, self.data, offset)
struct.error: unpack_from requires a buffer of at least 16292 bytes for unpacking 8 bytes at offset 16284 (actual buffer size is 16284)

```
I assume this is because of some version differences for libraries that are relevant to `pyroute2` between the older Debian 9 and current Alpine. An overall lack of memory on the affected nodes seems unlikely. Does this ring any bells?

**Comment by svinota** [comment]
Investigating, thanks
