### ISSUE TITLE
DEFAULT_RCVBUF  to small when querying interfaces with large number of VF's

### ISSUE THREAD

**Issue by javacruft** [svinota/pyroute2#751]
I have a deployment where an SR-IOV card has a large number of VF's configured - 63.

When pyroute2 (0.5.9) is used to interrogate the interface I see the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pyroute2/iproute/linux.py", line 1330, in link
    ret = self.nlm_request(msg,
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 373, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 862, in nlm_request
    for msg in self.get(msg_seq=msg_seq,
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 376, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 701, in get
    raise msg['header']['error']
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 177, in parse
    msg.decode()
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/rtnl/ifinfmsg/__init__.py", line 1087, in decode
    nlmsg.decode(self)
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/__init__.py", line 1315, in _ft_decode_generic
    raise NetlinkNLADecodeError(e)
pyroute2.netlink.exceptions.NetlinkNLADecodeError: unpack_from requires a buffer of at least 19240 bytes for unpacking 4 bytes at offset 19236 (actual buffer size is 16384)
```

Doubling the size of the RCVBUF resolves the issue and appears to be valid for later kernel versions where the maximum message size has increased to 32K

**Comment by svinota** [comment]
Got it, thanks! Will be fixed.
