### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2

### ISSUE THREAD

**Issue by gfphoenix78** [svinota/pyroute2#753]
Hi developer,
When I use pyroute2, I hit the following error, not sure if it's caused by pyroute2.
Here is the call stack.
```
======================================================================
ERROR: test suite for <module 'test_auth' from '/tmp/build/b6206905/pg_auto_failover_src/tests/test_auth.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nose/suite.py", line 229, in run
    self.tearDown()
  File "/usr/local/lib/python3.6/site-packages/nose/suite.py", line 352, in tearDown
    self.teardownContext(ancestor)
  File "/usr/local/lib/python3.6/site-packages/nose/suite.py", line 368, in teardownContext
    try_run(context, names)
  File "/usr/local/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/tmp/build/b6206905/pg_auto_failover_src/tests/test_auth.py", line 18, in teardown_module
    cluster.destroy()
  File "/tmp/build/b6206905/pg_auto_failover_src/tests/pgautofailover_utils.py", line 126, in destroy
    datanode.destroy()
  File "/tmp/build/b6206905/pg_auto_failover_src/tests/pgautofailover_utils.py", line 856, in destroy
    self.stop_pg_autoctl()
  File "/tmp/build/b6206905/pg_auto_failover_src/tests/pgautofailover_utils.py", line 320, in stop_pg_autoctl
    return self.pg_autoctl.stop()
  File "/tmp/build/b6206905/pg_auto_failover_src/tests/pgautofailover_utils.py", line 1441, in stop
    return self.pgnode.cluster.communicate(self, COMMAND_TIMEOUT)
  File "/tmp/build/b6206905/pg_auto_failover_src/tests/pgautofailover_utils.py", line 176, in communicate
    return proc.communicate(timeout=1)
  File "/tmp/build/b6206905/pg_auto_failover_src/tests/pgautofailover_utils.py", line 1463, in communicate
    self.out, self.err = self.run_proc.communicate(timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pyroute2/netns/process/proxy.py", line 160, in proxy
    return _handle(self.channel_in.get())
  File "/usr/local/lib/python3.6/site-packages/pyroute2/netns/process/proxy.py", line 25, in _handle
    raise result['data']
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 13202: ordinal not in range(128)
```

**Comment by svinota** [comment]
Yep, investigating.
