### ISSUE TITLE
"async=False" invalid syntax

### ISSUE THREAD

**Issue by AntouanK** [svinota/pyroute2#762]
hi there.

getting this error, any idea how I can fix it ( I installed the latest version, but it doesn't fix it )

```
❯ python main.py      
Traceback (most recent call last):
  File "/run/media/antouank/evo1/_REPOS_/02/main.py", line 7, in <module>
    from pyroute2 import IPRoute
  File "/home/antouank/.local/lib/python3.9/site-packages/pyroute2/__init__.py", line 19, in <module>
    from pyroute2.iproute import (IPRoute,
  File "/home/antouank/.local/lib/python3.9/site-packages/pyroute2/iproute.py", line 230, in <module>
    from pyroute2.netlink.rtnl.iprsocket import IPRSocket
  File "/home/antouank/.local/lib/python3.9/site-packages/pyroute2/netlink/rtnl/iprsocket.py", line 49
    def bind(self, groups=rtnl.RTNL_GROUPS, async=False):
                                            ^
SyntaxError: invalid syntax

❯ python --version
Python 3.9.1

❯ pip install pyroute2
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyroute2 in /home/antouank/.local/lib/python3.9/site-packages (0.4.21)
```

**Comment by smurfix** [comment]
The argument is now named "async_cache".
Current version on pypi is 0.5.14, not 0.4.21, so you seem to have an installation problem somewhere in there.
