### ISSUE TITLE
NetlinkError when removing rules with NDB

### ISSUE THREAD

**Issue by luis5tb** [svinota/pyroute2#771]
When trying to remove ip rules with NDB, the rule gets removed but a pyroute.netlink.exceptions.NetlinkError is thrown.

For the next: 
>>> with pyroute2.NDB() as n:
...        with n.rules[{'table': 200, 'dst': '172.20.20.20', 'dst_len': 32}] as rule:                                                                                                                                
...            rule.remove()

Where the next ip rule exists:
$ ip rule
0:      from all lookup local
999:    from all to 172.20.20.20 lookup test (== table 200)
...

The next exception is thrown:
{'table': 200, 'dst': '172.20.20.20', 'dst_len': 32, 'target': 'localhost', 'tflags': None, 'family': 2, 'src_len': 0, 'tos': 0, 'action': 1, 'flags': 0, 'src': None, 'iifname': None, 'goto': None, 'priority': 999, 'fwmark': None, 'flow': None, 'tun_id': None, 'suppress_ifgroup': None, 'suppress_prefixlen': 4294967295, 'fwmask': None, 'oifname': None, 'l3mdev': None, 'uid_range': None, 'protocol': None, 'ip_proto': None, 'sport_range': None, 'dport_range': None, 'res1': 0, 'res2': 0}
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py", line 317, in __exit__
    self.commit()
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/auth_manager.py", line 69, in guard
    return f(obj, *argv, **kwarg)
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py", line 578, in commit
    self.apply()
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/auth_manager.py", line 69, in guard
    return f(obj, *argv, **kwarg)
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py", line 736, in apply
    raise e
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py", line 717, in apply
    .api(self.api, method, **req))
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/source.py", line 229, in api
    return getattr(self.nl, name)(*argv, **kwarg)
  File "/usr/lib/python3.6/site-packages/pyroute2/iproute/linux.py", line 2038, in rule
    ret = tuple(ret)
  File "/usr/lib/python3.6/site-packages/pyroute2/netlink/nlsocket.py", line 869, in nlm_request
    callback=callback):
  File "/usr/lib/python3.6/site-packages/pyroute2/netlink/nlsocket.py", line 704, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (2, 'No such file or directory')

But the actual ip rule gets deleted

**Comment by svinota** [comment]
Fixing

**Comment by svinota** [comment]
The issue should be fixed by https://github.com/svinota/pyroute2/commit/c467f0af2cc1843a2af674459e647e69743f257f

**Comment by luis5tb** [comment]
Great! Thanks!
