### ISSUE TITLE
Excetip: lost sync in apply() when removing routes with NDB

### ISSUE THREAD

**Issue by luis5tb** [svinota/pyroute2#772]
When trying to delete a route with NDB, the " Exception: lost sync in apply() is raised:

>>> with pyroute2.NDB() as ndb:
...     ndb.routes[{'dst': XXXX, 'table': 200}].remove().commit()
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/auth_manager.py", line 69, in guard
    return f(obj, *argv, **kwarg)
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py", line 578, in commit
    self.apply()
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/auth_manager.py", line 69, in guard
    return f(obj, *argv, **kwarg)
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/objects/route.py", line 624, in apply
    return super(Route, self).apply(rollback)
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/auth_manager.py", line 69, in guard
    return f(obj, *argv, **kwarg)
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py", line 757, in apply
    raise Exception('lost sync in apply()')
Exception: lost sync in apply()

**Comment by svinota** [comment]
Unfortunately I couldn't reproduce the issue under available conditions.

Could you please provide more info regarding the case? Thanks a lot

**Comment by luis5tb** [comment]
Perhaps it was related to the ip family too. I'm not hitting this again either... I'll close it and if I re-hit it again I'll add more details about the specific existing routes

**Comment by svinota** [comment]
Thanks

**Comment by luis5tb** [comment]
I'm hitting this again. This is the peace of code hitting the issue: https://github.com/luis5tb/bgp-agent/blob/main/bgp_agent/platform/utils/linux_net.py#L264-L276

Locally, I have this route at table 201:
$ $ ip route show table br-vlan
default dev br-vlan scope link 
172.24.200.142 dev br-vlan.1 scope link 

Then the program discovering this route:
THE ROUTE IS {'multipath': [], 'metrics': {}, 'table': 201, 'dst': '172.24.200.142', 'target': 'localhost', 'tflags': 0, 'fa
mily': 2, 'dst_len': 32, 'tos': 0, 'priority': 0, 'via': '', 'newdst': '', 'src_len': 0, 'proto': 3, 'scope': 253, 'type': 1, 'flags': 0, 'src': None, 'iif': None, 'oif': 13, 'gateway': None, 'prefsrc': None, 'protoinfo': None, 'flow': None, 'mark': None, 'pref': None, 'encap_type': None, 'route_id': None, 'gc_mark': None} 

And triggering the deletion (https://github.com/luis5tb/bgp-agent/blob/main/bgp_agent/platform/utils/linux_net.py#L273-L274) with the next dict:
THE ROUTE DEL COMMAND IS WITH {'dst': '172.24.200.142', 'dst_len': 32, 'family': 2, 'oif': 13, 'table': 201}

Then, I see the next logs:
021-03-22 10:58:44.181 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] init __init__ /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:239                                         
2021-03-22 10:58:44.181 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] complete key {'dst': '172.24.200.142', 'dst_len': 32, 'family': 2, 'oif': 13, 'table': 201, 'target': 'localhost'} from table rout
es complete_key /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:468                                                                                                                         
2021-03-22 10:58:44.181 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] got {'dst': '172.24.200.142', 'dst_len': 32, 'family': 2, 'oif': 13, 'table': 201, 'target': 'localhost', 'tflags': 0, 'tos': 0, '
RTA_DST': '172.24.200.142', 'RTA_PRIORITY': 0, 'RTA_TABLE': 201, 'RTA_VIA': '', 'RTA_NEWDST': ''} complete_key /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:500                          
2021-03-22 10:58:44.182 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] load_sql: ('localhost', 0, 2, 32, 0, 0, 201, 3, 253, 1, 0, '172.24.200.142', None, None, 13, None, 0, None, None, None, 201, None,
 '', '', None, None, None, None) load_sql /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:850                                                                                               
2021-03-22 10:58:44.183 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] commit: [(1616410724.1812854, 'invalid'), (1616410724.1832862, 'system'), (1616410724.1833293, 'remove')] commit /usr/local/lib/p$
thon3.6/site-packages/pyroute2/ndb/objects/__init__.py:547                                                                                                                                                          
2021-03-22 10:58:44.183 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] init __init__ /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:239                                         
2021-03-22 10:58:44.184 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] complete key {'target': 'localhost', 'tflags': 0, 'family': 2, 'dst_len': 32, 'tos': 0, 'RTA_DST': '172.24.200.142', 'RTA_PRIORIT$
': 0, 'RTA_TABLE': 201, 'RTA_VIA': '', 'RTA_NEWDST': '', 'table': 201} from table routes_139820862939912 complete_key /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:468                   
2021-03-22 10:58:44.184 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] got {'target': 'localhost', 'tflags': 0, 'family': 2, 'dst_len': 32, 'tos': 0, 'RTA_DST': '172.24.200.142', 'RTA_PRIORITY': 0, 'R$
A_TABLE': 201, 'RTA_VIA': '', 'RTA_NEWDST': '', 'table': 201} complete_key /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:500                                                              
2021-03-22 10:58:44.185 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] load_sql: ('localhost', 0, 2, 32, 0, 0, 201, 3, 253, 1, 0, '172.24.200.142', None, None, 13, None, 0, None, None, None, 201, None$
 '', '', None, None, None, None) load_sql /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:850                                                                                               
2021-03-22 10:58:44.187 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot interfaces_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689                 
2021-03-22 10:58:44.187 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot af_bridge_ifs_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689              
2021-03-22 10:58:44.188 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot af_bridge_vlans_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689            
2021-03-22 10:58:44.188 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot p2p_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689                        
2021-03-22 10:58:44.188 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot ifinfo_bridge_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689              
2021-03-22 10:58:44.189 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot ifinfo_bond_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.190 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot ifinfo_vlan_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.190 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot ifinfo_vxlan_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.190 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot ifinfo_gre_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.191 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot ifinfo_vrf_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.191 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot ifinfo_vti_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.191 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot ifinfo_vti6_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.192 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot addresses_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.192 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot neighbours_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.192 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot af_bridge_fdb_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.193 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot routes_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.193 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot nh_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.194 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot metrics_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.194 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot enc_mpls_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.194 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot netns_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.195 808577 DEBUG pyroute2.ndb.139820721861296.schema [-] create snapshot rules_139820862939912 save_deps /usr/local/lib/python3.6/site-packages/pyroute2/ndb/schema.py:689
2021-03-22 10:58:44.197 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] apply: [(1616410724.1812854, 'invalid'), (1616410724.1832862, 'system'), (1616410724.1833293, 'remove')] apply /usr/local/lib/pyt$
on3.6/site-packages/pyroute2/ndb/objects/__init__.py:662
2021-03-22 10:58:44.198 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] load_sql: ('localhost', 0, 2, 32, 0, 0, 201, 3, 253, 1, 0, '172.24.200.142', None, None, 13, None, 0, None, None, None, 201, None$
 '', '', None, None, None, None) load_sql /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:850
2021-03-22 10:58:44.199 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] apply req: {'target': 'localhost', 'tflags': 0, 'family': 2, 'dst_len': 32, 'tos': 0, 'RTA_DST': '172.24.200.142', 'RTA_PRIORITY'$
 0, 'RTA_TABLE': 201, 'RTA_VIA': '', 'RTA_NEWDST': ''} apply /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:683
2021-03-22 10:58:44.199 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] apply idx_req: {'target': 'localhost', 'tflags': 0, 'family': 2, 'dst_len': 32, 'tos': 0, 'RTA_DST': '172.24.200.142', 'RTA_PRIOR$
TY': 0, 'RTA_TABLE': 201, 'RTA_VIA': '', 'RTA_NEWDST': ''} apply /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:684
2021-03-22 10:58:44.199 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] apply state: remove apply /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:685
2021-03-22 10:58:44.199 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] run del ({'target': 'localhost', 'tflags': 0, 'family': 2, 'dst_len': 32, 'tos': 0, 'RTA_DST': '172.24.200.142', 'RTA_PRIORITY': $
, 'RTA_TABLE': 201, 'RTA_VIA': '', 'RTA_NEWDST': ''}) apply /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:714
2021-03-22 10:58:44.200 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] error: (3, 'No such process') apply /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:723
2021-03-22 10:58:44.200 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] ignore error 3 for {'multipath': [], 'metrics': {}, 'dst': '172.24.200.142', 'dst_len': 32, 'family': 2, 'oif': 13, 'table': 201,
'target': 'localhost', 'tflags': 0, 'tos': 0, 'priority': 0, 'via': '', 'newdst': '', 'src_len': 0, 'proto': 3, 'scope': 253, 'type': 1, 'flags': 0, 'src': None, 'iif': None, 'gateway': None, 'prefsrc': None, 'pr
otoinfo': None, 'flow': None, 'mark': None, 'pref': None, 'encap_type': None, 'route_id': None, 'gc_mark': None} apply /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:725
2021-03-22 10:58:44.201 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] stats: apply del {objid 139820862939912, wtime 0.0, mqsize 0, nqsize 0} apply /usr/local/lib/python3.6/site-packages/pyroute2/ndb/
objects/__init__.py:748
2021-03-22 10:58:44.201 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] load_sql: ('localhost', 0, 2, 32, 0, 0, 201, 3, 253, 1, 0, '172.24.200.142', None, None, 13, None, 0, None, None, None, 201, None,
 '', '', None, None, None, None) load_sql /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:850
2021-03-22 10:58:44.202 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] check: [(1616410724.1812854, 'invalid'), (1616410724.1832862, 'system'), (1616410724.1833293, 'remove')] check /usr/local/lib/pyth
on3.6/site-packages/pyroute2/ndb/objects/__init__.py:611
2021-03-22 10:58:44.202 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] check state: False check /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:614
2021-03-22 10:58:44.202 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] check failed apply /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:752
2021-03-22 10:58:44.202 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] run del ({'target': 'localhost', 'tflags': 0, 'family': 2, 'dst_len': 32, 'tos': 0, 'RTA_DST': '172.24.200.142', 'RTA_PRIORITY': 0
, 'RTA_TABLE': 201, 'RTA_VIA': '', 'RTA_NEWDST': ''}) apply /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:714
2021-03-22 10:58:44.203 808577 DEBUG pyroute2.ndb.139820721861296.rtnl_object [-] error: (3, 'No such process') apply /usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py:723
...
...

And finally the lost sync in apply():
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task [-] Error during BGPAgent.sync: Exception: lost sync in apply()                                                                                     
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task Traceback (most recent call last):                                                                                                                  
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task   File "/usr/lib/python3.6/site-packages/oslo_service/periodic_task.py", line 216, in run_periodic_tasks                                            
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task     task(self, context)                                                                                                                             
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task   File "/usr/local/lib/python3.6/site-packages/bgp_agent/agent.py", line 61, in sync                                                                
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task     self.agent_driver.sync()                                                                                                                        
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task   File "/usr/lib/python3.6/site-packages/oslo_concurrency/lockutils.py", line 360, in inner                                                         
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task     return f(*args, **kwargs)                                                                                                                       
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task   File "/usr/local/lib/python3.6/site-packages/bgp_agent/platform/osp/ovn_driver.py", line 150, in sync                                             
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task     extra_routes)                                                                                                                                   
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task   File "/usr/local/lib/python3.6/site-packages/bgp_agent/platform/utils/linux_net.py", line 277, in delete_bridge_ip_routes                         
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task     r.remove()                                                                                                                                      
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task   File "/usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py", line 317, in __exit__                                             
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task     self.commit()                                                                                                                                   
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task   File "/usr/local/lib/python3.6/site-packages/pyroute2/ndb/auth_manager.py", line 69, in guard                                                     
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task     return f(obj, *argv, **kwarg)                                                                                                                   
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task   File "/usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py", line 578, in commit                                               
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task     self.apply()                                                                                                                                    
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task   File "/usr/local/lib/python3.6/site-packages/pyroute2/ndb/auth_manager.py", line 69, in guard                                                     
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task     return f(obj, *argv, **kwarg)                                                                                                                   
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task   File "/usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/route.py", line 624, in apply                                                   
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task     return super(Route, self).apply(rollback)                                                                                                       
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task   File "/usr/local/lib/python3.6/site-packages/pyroute2/ndb/auth_manager.py", line 69, in guard                                                     
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task     return f(obj, *argv, **kwarg)                                                                                                                   
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task   File "/usr/local/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py", line 757, in apply                                                
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task     raise Exception('lost sync in apply()')                                                                                                         
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task Exception: lost sync in apply()                                                                                                                     
2021-03-22 10:59:13.376 808577 ERROR oslo_service.periodic_task                                                                                                                                                     
2021-03-22 10:59:13.377 808577 WARNING oslo.service.loopingcall [-] Function 'functools.partial' run outlasted interval by 37.23 sec                                                                                
^C2021-03-22 10:59:56.434 808577 INFO oslo_service.service [-] Caught SIGINT signal, instantaneous exiting

**Comment by svinota** [comment]
Thanks for the logs, investigating

**Comment by svinota** [comment]
Reproduced, fixing.

**Comment by luis5tb** [comment]
Awesome! thanks!

**Comment by svinota** [comment]
```
$ ip route show table 201
default dev br-vlan scope link 
172.24.200.142 dev br-vlan.1 scope link 

$ sudo ip route del 172.24.200.142 dev br-vlan.1 scope link
RTNETLINK answers: No such process
```

eh… what? o_O

1. I have to change this `lost sync` to something more meaningful.
2. Looking into the kernel source in an attempt to understand what's going on here.

**Comment by svinota** [comment]
Nevermind. Found the mistake.

**Comment by luis5tb** [comment]
It should be "sudo ip route del 172.24.200.142 dev br-vlan.1 table 201" to delete the route

**Comment by svinota** [comment]
Yep :)))

**Comment by svinota** [comment]
Located the error in the library, the fix will be ready asap.

**Comment by svinota** [comment]
The fix is ready and doesn't seem to break anything. The test case to cover that will be submitted a bit later.
