### ISSUE TITLE
Error when creating ipv6 ip rules with NDB

### ISSUE THREAD

**Issue by luis5tb** [svinota/pyroute2#773]
NetlinkError thrown when trying to create an ip rule with ipv6 address. For example:

import pyroute2
ndb = pyroute2.NDB()
rule = {'dst': '2001:db8::f816:3eff:fe6f:183c', 'table': 200, 'dst_len': 128}
ndb.rules.create(rule).commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/auth_manager.py", line 69, in guard
    return f(obj, *argv, **kwarg)
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py", line 564, in commit
    raise e_i
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py", line 553, in commit
    return self.apply()
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/auth_manager.py", line 69, in guard
    return f(obj, *argv, **kwarg)
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py", line 736, in apply
    raise e
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/objects/__init__.py", line 717, in apply
    .api(self.api, method, **req))
  File "/usr/lib/python3.6/site-packages/pyroute2/ndb/source.py", line 229, in api
    return getattr(self.nl, name)(*argv, **kwarg)
  File "/usr/lib/python3.6/site-packages/pyroute2/iproute/linux.py", line 2038, in rule
    ret = tuple(ret)
  File "/usr/lib/python3.6/site-packages/pyroute2/netlink/nlsocket.py", line 869, in nlm_request
    callback=callback):
  File "/usr/lib/python3.6/site-packages/pyroute2/netlink/nlsocket.py", line 704, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (22, 'Invalid argument')

**Comment by luis5tb** [comment]
Thanks! this seems to work!
