### ISSUE TITLE
use ethtool error

### ISSUE THREAD

**Issue by yeyicong** [svinota/pyroute2#775]
from pyroute2.ethtool import Ethtool   

if __name__ == "__main__":
    etht = Ethtool()
    if_info = etht.get_link_mode(ifname="ens5")

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/pyroute2/ethtool/ethtool.py", line 264, in get_link_mode
    with_netlink, ifname)
  File "/usr/local/python3/lib/python3.7/site-packages/pyroute2/ethtool/ethtool.py", line 254, in _nl_exec
    raise UseIoctl()
pyroute2.ethtool.ethtool.UseIoctl

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/pyroute2/ethtool/ioctl.py", line 455, in ioctl
    if fcntl.ioctl(self.sock, SIOCETHTOOL, self.ifreq):
OSError: [Errno 95] Operation not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyroute_test.py", line 199, in <module>
    get_net_dev_info("lo")
  File "pyroute_test.py", line 29, in get_net_dev_info
    if_info = etht.get_link_mode(ifname="ens5")
  File "/usr/local/python3/lib/python3.7/site-packages/pyroute2/ethtool/ethtool.py", line 268, in get_link_mode
    link_settings = self._with_ioctl.get_link_settings()
  File "/usr/local/python3/lib/python3.7/site-packages/pyroute2/ethtool/ioctl.py", line 553, in get_link_settings
    self.ioctl()
  File "/usr/local/python3/lib/python3.7/site-packages/pyroute2/ethtool/ioctl.py", line 459, in ioctl
    raise NotSupportedError(self.ifname.decode("utf-8"))
pyroute2.ethtool.ioctl.NotSupportedError: ens5

**Comment by svinota** [comment]
Looks like it's not supported on your platform neither via netlink nor via ioctl.

Can you provide more details? What the system is, architecture, kernel version etc? Thanks!

**Comment by yeyicong** [comment]
[root@localhost network]# hostnamectl
   Static hostname: localhost.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 5f71b30f3f614cf2a55342c73fabf368
           Boot ID: 758911cb56144d1491b1d12f3cf8e977
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-514.el7.x86_64
      Architecture: x86-64
[root@localhost network]# cat /proc/version
Linux version 3.10.0-514.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Nov 22 16:42:41 UTC 2016
[root@localhost network]#

**Comment by svinota** [comment]
Thanks, setting up the environment to reproduce.

**Comment by svinota** [comment]
Reproduced the error, fixing.

**Comment by svinota** [comment]
Nope, I remove the «bug» label.

This is just not supported on the kernel on this platform, no matter which way.

**Comment by svinota** [comment]
I can only suggest you to use newer kernels to get this functionality working.

**Comment by yeyicong** [comment]
Thanks for your answer
