### ISSUE TITLE
Noticed `Exception: DB execute error` in the logs

### ISSUE THREAD

**Issue by mawiegand** [svinota/pyroute2#791]
I noticed some error messages like this in the log:

```python
ERROR:pyroute2.ndb.140278038932896.main:could not load event:
{'family': 2, 'prefixlen': 24, 'flags': 0, 'scope': 0, 'index': 5, 'attrs': [('IFA_ADDRESS', '192.168.56.108'), ('IFA_LOCAL', '192.168.56.108'), ('IFA_BROADCAST', '192.168.56.255'), ('IFA_LABEL', 'eth3'), ('IFA_FLAGS', 0), ('IFA_CACHEINFO', {'ifa_preferred': 600, 'ifa_valid': 600, 'cstamp': 536802, 'tstamp': 670844})], 'header': {'length': 88, 'type': 20, 'flags': 0, 'sequence_number': 1620384623, 'pid': 11458, 'error': None, 'target': '/proc/1/ns/net', 'stats': Stats(qsize=0, delta=0, delay=0)}, 'event': 'RTM_NEWADDR'}
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyroute2/ndb/main.py", line 890, in __dbm__
    handler(target, event)
  File "/usr/lib/python3/dist-packages/pyroute2/ndb/schema.py", line 811, in load_netlink
    self.execute('DROP VIEW %s' % name[7:])
  File "/usr/lib/python3/dist-packages/pyroute2/ndb/schema.py", line 215, in _do_dispatch
    return method(self, *argv, **kwarg)
  File "/usr/lib/python3/dist-packages/pyroute2/ndb/schema.py", line 452, in execute
    raise Exception('DB execute error: %s %s' % (argv, kwarg))
Exception: DB execute error: ('DROP VIEW vti6_140278013249056',) {}
```

Is this is known problem and nothing to worry about?
I hadn't noticed any "real" problems caused by the error so far.

Thanks! =)

**Comment by mawiegand** [comment]
Thanks for the explanation!
