### ISSUE TITLE
INET_DIAG_INFO in connections returned by DiagSocket.get_sock_stats sometimes just contains binary data

### ISSUE THREAD

**Issue by teuchert** [svinota/pyroute2#792]
Hello,

thank you a lot for creating pyroute2, it is incredibly useful. I use it to get information about established TCP connections.

I noticed that the INET_DIAG_INFO attribute sometimes doesn't contain a dict with the TCP diag information, but instead just binary data.

I can reproduce the problem with the following code:

```python
from pyroute2 import DiagSocket
from socket import AF_INET, AF_INET6

import time
import sys

ds = DiagSocket()
ds.bind()

while True:
    for stat in ds.get_sock_stats(family=AF_INET, states=(1<<1), extensions=2) + ds.get_sock_stats(family=AF_INET6, states=(1<<1), extensions=2):
        for attr in stat['attrs']:
            if attr[0] != 'INET_DIAG_INFO':
                continue

            if not isinstance(attr[1], dict):
                print(stat)
                sys.exit()

    time.sleep(1)
```

An example output would be:

```python
{'idiag_family': 2, 'idiag_state': 1, 'idiag_timer': 0, 'idiag_retrans': 0, 'idiag_sport': 52562, 'idiag_dport': 5044,
'idiag_src': '<IP address removed>', 'idiag_dst': '<IP address removed>', 'idiag_if': 0,
'idiag_cookie': 18446624253108727424, 'idiag_expires': 0, 'idiag_rqueue': 0, 'idiag_wqueue': 0, 'idiag_uid': 0,
'idiag_inode': 1711841094, 'attrs': [('INET_DIAG_SHUTDOWN', 0), ('INET_DIAG_INFO', 
b'\x94\x00\x02\x00\x01\x00\x00\x00\x00\x07\xbc\x00\x10\x15\x03\x00@\x9c\x00\x00\xa8\x05\x00\x00\xa8\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xdd\'\x00\x00\x00\x00\x00\x00\xd5\'\x00\x00\xd7\'\x00\x00(#\x00\x00\xf0\x8a\x00\x00:\x07\x00\x00\x05\x07\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\xf4"\x00\x00\x03\x00\x00\x00\xf0U\x00\x00\x00i\x00\x00\x0c\x00\x00\x00\x8c\x81_\x00\x00\x00\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff8\xb3$\x02\x00\x00\x00\x00\xaf\xcc \x00\x00\x00\x00\x00\xf3\xad\x01\x00#\xf9\x00\x00')],
'header': {'length': 244, 'type': 20, 'flags': 2, 'sequence_number': 255, 'pid': 20881, 'error': None,
'target': 'localhost', 'stats': Stats(qsize=0, delta=0, delay=0)}}
```

I'm using CentOS Linux release 7.9.2009 (Core) with kernel 3.10.0-1127.19.1.el7.x86_64.

**Comment by svinota** [comment]
That's 'cause the NLA couldn't be parsed — the library has no info how to parse the structure.

Thanks for the report, I will see what's missing and update the code asap.

**Comment by teuchert** [comment]
Hi,

I tried it again with version 0.6.4 from PyPI and noticed that this particular issue is gone. Unfortunately, I don't know with which version I tried it initially (I should have included that in the report in the first place).

Anyway, as far as I can tell, this issue can be closed.

**Comment by teuchert** [comment]
Actually, it seems as if the issue is not really solved, but it is now clearer what the issue is. I created the following test code:

```python
from pyroute2 import DiagSocket
from socket import AF_INET

ds = DiagSocket()
ds.bind()

for stat in ds.get_sock_stats(family=AF_INET, states=(1<<1), extensions=2):
    for attr in stat['attrs']:
        if attr[0] == 'INET_DIAG_INFO':
            print(attr[1])
```

For some connections 'INET_DIAG_INFO' is decoded fine, but for some it fails:

```
decoding INET_DIAG_INFO
Traceback (most recent call last):
  File "/opt/tcpi_exporter/lib64/python3.6/site-packages/pr2modules/netlink/__init__.py", line 1507, in try_to_decode
    cell.decode()
  File "/opt/tcpi_exporter/lib64/python3.6/site-packages/pr2modules/netlink/diag/__init__.py", line 235, in decode
    nla.decode(self)
  File "/opt/tcpi_exporter/lib64/python3.6/site-packages/pr2modules/netlink/__init__.py", line 2051, in decode
    nla_base.decode(self)
  File "/opt/tcpi_exporter/lib64/python3.6/site-packages/pr2modules/netlink/__init__.py", line 1007, in decode
    self.ft_decode(offset)
  File "/opt/tcpi_exporter/lib64/python3.6/site-packages/pr2modules/netlink/__init__.py", line 1432, in ft_decode
    value = struct.unpack_from(fmt, self.data, offset)
struct.error: unpack_from requires a buffer of at least 4 bytes
```

I figured out that I can fix this by editing the tcp_info NLA structure in `pr2modules/netlink/diag/__init__.py` so that it fits to the tcp_info struct from `include/uapi/linux/tcp.h` of the kernel version that's running on the system. As I'm using kernel 3.10 from CentOS 7 many of the attributes from tcp_info are missing compared to the current version.

So I guess that the root cause is that tcp_info depends on the kernel version.
