### ISSUE TITLE
WireGuard keys are parsed incorrectly

### ISSUE THREAD

**Issue by K900** [svinota/pyroute2#803]
Just getting interface info using a simple program like

```python
from pyroute2 import WireGuard
print(WireGuard().info('wg0'))
```

Results in lots of errors like: 

```
decoding WGPEER_A_PUBLIC_KEY
Traceback (most recent call last):
  File "/nix/store/xhifdnnxdif4nrhi434bads4dmb41ik2-python3.9-pyroute2-core-0.6.1/lib/python3.9/site-packages/pr2modules/netlink/__init__.py", line 1507, in try_to_decode
    cell.decode()
  File "/nix/store/xhifdnnxdif4nrhi434bads4dmb41ik2-python3.9-pyroute2-core-0.6.1/lib/python3.9/site-packages/pr2modules/netlink/generic/wireguard.py", line 158, in decode
    self['value'] = b64encode(self['value'])
  File "/nix/store/xhifdnnxdif4nrhi434bads4dmb41ik2-python3.9-pyroute2-core-0.6.1/lib/python3.9/site-packages/pr2modules/netlink/__init__.py", line 1194, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'value'
```

And similar for `WGDEVICE_A_PRIVATE_KEY`, `WGDEVICE_A_PRESHARED_KEY` and `WGPEER_A_PRESHARED_KEY`.

A device object is still returned, but the keys are one byte long: `'WGDEVICE_A_PRIVATE_KEY', {'key': b'\xc8'}`.

Using Python 3.9 and pyroute2 0.6.1 on NixOS.

**Comment by svinota** [comment]
Thanks! Investigating

**Comment by K900** [comment]
Took a quick look at the code myself and looks like it was just a few typos that broke everything. Submitted #804.

**Comment by svinota** [comment]
Yep, there was an error in the code, thanks.
