### ISSUE TITLE
NDB: Exception: lost sync in apply() when trying to update/create a route with onlink flag

### ISSUE THREAD

**Issue by rgrewe** [svinota/pyroute2#815]
```Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyroute2 import NDB
>>> ndb = NDB()
>>> r = ndb.routes["default"]
>>> r["flags"] = ["onlink"]
>>> r.commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pyroute2/ndb/auth_manager.py", line 69, in guard
    return f(obj, *argv, **kwarg)
  File "/usr/lib/python3/dist-packages/pyroute2/ndb/objects/__init__.py", line 676, in commit
    self.apply()
  File "/usr/lib/python3/dist-packages/pyroute2/ndb/auth_manager.py", line 69, in guard
    return f(obj, *argv, **kwarg)
  File "/usr/lib/python3/dist-packages/pyroute2/ndb/objects/route.py", line 668, in apply
    return super(Route, self).apply(rollback)
  File "/usr/lib/python3/dist-packages/pyroute2/ndb/auth_manager.py", line 69, in guard
    return f(obj, *argv, **kwarg)
  File "/usr/lib/python3/dist-packages/pyroute2/ndb/objects/__init__.py", line 892, in apply
    raise Exception('lost sync in apply()')
Exception: lost sync in apply()
>>> r["flags"] = 4
>>> r.commit()
{'multipath': [], 'metrics': {}, 'dst': '', 'target': 'localhost', 'table': 254, 'tflags': 0, 'family': 2, 'dst_len': 0, 'tos': 0, 'scope': 0, 'oif': 2, 'priority': 0, 'via': '', 'newdst': '', 'src_len': 0, 'proto': 4, 'type': 1, 'flags': 4, 'src': None, 'iif': None, 'gateway': '172.27.0.1', 'prefsrc': None, 'protoinfo': None, 'flow': None, 'mark': None, 'pref': None, 'encap_type': None, 'route_id': None, 'gc_mark': None}```

**Comment by centromere** [comment]
A very similar issue exists when trying to set the scope of a route. If I set the scope to `link`, the same exception occurs. However, despite the exception, the route *is* created successfully with the proper scope.

```
>>> n.routes.create({ 'target': 'foo', 'dst': '169.254.1.1/32', 'table': 1, 'oif': 16, 'scope': 'link' }).commit()
2021-08-25 14:38:41,599    DEBUG pyroute2.ndb.140438921618336.rtnl_object: init
2021-08-25 14:38:41,599    DEBUG pyroute2.ndb.140438921618336.view.routes: check if the key {'target': 'foo', 'dst': '169.254.1.1', 'table': 1, 'oif': 16, 'scope': 'link', 'dst_len': 32} exists in table routes
2021-08-25 14:38:41,600    DEBUG pyroute2.ndb.140438921618336.view.routes: not exists
2021-08-25 14:38:41,600    DEBUG pyroute2.ndb.140438921618336.rtnl_object: complete key {'target': 'foo', 'dst': '169.254.1.1', 'table': 1, 'oif': 16, 'scope': 'link', 'dst_len': 32} from table routes
2021-08-25 14:38:41,601    DEBUG pyroute2.ndb.140438921618336.rtnl_object: got none
2021-08-25 14:38:41,601    DEBUG pyroute2.ndb.140438921618336.view.routes: check if the key {'target': 'foo', 'dst': '169.254.1.1', 'table': 1, 'oif': 16, 'scope': 'link', 'dst_len': 32, 'create': True} exists in table routes
2021-08-25 14:38:41,601    DEBUG pyroute2.ndb.140438921618336.view.routes: not exists
2021-08-25 14:38:41,602    DEBUG pyroute2.ndb.140438921618336.rtnl_object: commit: [(1629902321.5998113, 'invalid')]
2021-08-25 14:38:41,602    DEBUG pyroute2.ndb.140438921618336.rtnl_object: apply: [(1629902321.5998113, 'invalid')]
2021-08-25 14:38:41,602    DEBUG pyroute2.ndb.140438921618336.rtnl_object: load_sql: None
2021-08-25 14:38:41,603    DEBUG pyroute2.ndb.140438921618336.rtnl_object: apply req: {'target': 'foo', 'dst_len': 32, 'scope': 'link', 'RTA_DST': '169.254.1.1', 'RTA_OIF': 16, 'RTA_TABLE': 1, 'dst': '169.254.1.1', 'table': 1, 'oif': 16}
2021-08-25 14:38:41,603    DEBUG pyroute2.ndb.140438921618336.rtnl_object: apply idx_req: {'target': 'foo', 'dst_len': 32, 'scope': 'link', 'RTA_DST': '169.254.1.1', 'RTA_OIF': 16, 'RTA_TABLE': 1}
2021-08-25 14:38:41,603    DEBUG pyroute2.ndb.140438921618336.rtnl_object: apply state: invalid
2021-08-25 14:38:41,603    DEBUG pyroute2.ndb.140438921618336.rtnl_object: run add ({'target': 'foo', 'dst_len': 32, 'scope': 'link', 'RTA_DST': '169.254.1.1', 'RTA_OIF': 16, 'RTA_TABLE': 1, 'dst': '169.254.1.1', 'table': 1, 'oif': 16, 'multipath': [], 'metrics': {}})
2021-08-25 14:38:41,605    DEBUG pyroute2.ndb.140438921618336.rtnl_object: stats: apply add {objid 140438717932864, wtime 0.0, mqsize 0, nqsize 0}
2021-08-25 14:38:41,606    DEBUG pyroute2.ndb.140438921618336.rtnl_object: load_sql: None
2021-08-25 14:38:41,606    DEBUG pyroute2.ndb.140438921618336.rtnl_object: check: [(1629902321.5998113, 'invalid')]
2021-08-25 14:38:41,606    DEBUG pyroute2.ndb.140438921618336.rtnl_object: check state: False
2021-08-25 14:38:41,606    DEBUG pyroute2.ndb.140438921618336.rtnl_object: check failed
2021-08-25 14:38:41,606    DEBUG pyroute2.ndb.140438921618336.rtnl_object: run add ({'target': 'foo', 'dst_len': 32, 'scope': 'link', 'RTA_DST': '169.254.1.1', 'RTA_OIF': 16, 'RTA_TABLE': 1, 'dst': '169.254.1.1', 'table': 1, 'oif': 16, 'multipath': [], 'metrics': {}})
2021-08-25 14:38:41,608    DEBUG pyroute2.ndb.140438921618336.rtnl_object: error: (17, 'File exists')
2021-08-25 14:38:41,614    DEBUG pyroute2.ndb.140438921618336.rtnl_object: load_sql: None
2021-08-25 14:38:41,614    DEBUG pyroute2.ndb.140438921618336.rtnl_object: ignore error 17 for {'multipath': [], 'metrics': {}, 'target': 'foo', 'dst': '169.254.1.1', 'table': 1, 'oif': 16, 'scope': 'link', 'dst_len': 32}
2021-08-25 14:38:41,614    DEBUG pyroute2.ndb.140438921618336.rtnl_object: run fallback set ({'target': 'foo', 'dst_len': 32, 'scope': 'link', 'RTA_DST': '169.254.1.1', 'RTA_OIF': 16, 'RTA_TABLE': 1, 'dst': '169.254.1.1', 'table': 1, 'oif': 16, 'multipath': [], 'metrics': {}})
...
```

If I set scope to `253` instead of `link`, it completes without incident.

**Comment by svinota** [comment]
both scopes and flags support is tested now (and should work on the current code)
