### ISSUE TITLE
AttributeError: module 'select' has no attribute 'poll'

### ISSUE THREAD

**Issue by foojo** [svinota/pyroute2#820]
I'm using latest from git in a Debian 10.10 docker image and getting the following error after initializing ndb = NDB(log='debug'):

2021-06-28 00:54:51,683    DEBUG pyroute2.ndb.140402672892896.sources.localhost: init
init
2021-06-28 00:54:51,684    DEBUG pyroute2.ndb.140402672892896.sources.localhost: starting the source
starting the source
2021-06-28 00:54:51,684    DEBUG pyroute2.ndb.140402672892896.sources.localhost/nsmanager: init
init
2021-06-28 00:54:51,684    DEBUG pyroute2.ndb.140402672892896.sources.localhost/nsmanager: starting the source
starting the source
2021-06-28 00:54:51,684    DEBUG pyroute2.ndb.140402672892896.sources.localhost: connecting
connecting
2021-06-28 00:54:51,684    DEBUG pyroute2.ndb.140402672892896.sources.localhost: loading
loading
Exception in thread Netlink async cache:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pr2modules/netlink/nlsocket.py", line 569, in async_recv
    poll = select.poll()
AttributeError: module 'select' has no attribute 'poll'

Initially my docker image was based on Alpine Linux and I thought that musl (used in Alpine instead of glibc) would have been the issue as stated in the Python3 doc about the select.poll() not being in all OS, but I'm getting the same error on Debian.

**Comment by svinota** [comment]
Looks strange, but obviously we see what we see :) Please tell me the Debian docker image so I reproduce. And the Alpine Linux docker image as well, let's see if we can fix that too. Thanks!

**Comment by foojo** [comment]
So while creating a minimal Dockerfile to reproduce the issue, tossing away all my app stuff I obviously realized that it works alright!

My python app is a Ryu SDN controller and when I run the app the Ryu way (e.g. ryu-manager --verbose myfile.py) this is where it blows up. I'll dig there to see what horror they might be doing to select.poll().

I'll update back if I find something that incriminates them :)

**Comment by svinota** [comment]
Maybe the `select` symbol gets overridden?

**Comment by foojo** [comment]
Ok so Ryu uses some Open vSwitch Python libs and this one might be the trouble maker:

https://github.com/openvswitch/ovs/blob/f8be30acf2eb60d567bb7386b98f5cb58ddb9119/python/ovs/poller.py

Anything to do with this? https://docs.pyroute2.org/usage.html#eventlet

I don't know about all the eventlet potential problems...

**Comment by svinota** [comment]
The eventlet module is one huge problem for NDB, tbh…

The NDB is thread-based and I'm not sure it is compatible with eventlet at all. The machinery inside NDB uses also an SQL DB, and I have no idea if it will work correctly with eventlet.

If you plan to work with eventlet, then you may use plain `IPRoute` without `async_cache`, thus simple `IPRoute.bind()` if you need RTNL monitoring, or without any `bind()` at all if you don't need to monitor RTNL broadcasts.

Another alternative is to use NDB and eventlet in separate processes, connecting them via RPC (e.g. `pyroute2-cli` may be run as a service providing text/plain and json RPC).

**Comment by foojo** [comment]
I did notice that IPRoute() had no issue and I'll stick to it. Ryu receives OpenFlow async events and I wanted to take actions on the physical interfaces using pyroute2 without having to resync with the OS each time to make sure the interface view was always up to date. And I did like the NDB syntax better since it was closer to python object than 'set' strings etc.

But I have no control over what Ryu / OVS libs are doing, I'm just using the framework and don't want to go there ;)
