### ISSUE TITLE
can't pickle Value objects in route.py

### ISSUE THREAD

**Issue by srijnair-cisco** [svinota/pyroute2#829]
Hi,
We are hitting an issue with pyroute2. Any help to resolve is appreciated.

2021-08-10 21:53:48,367 INFO     [cntnr_lifecycle:]  [Getcntnr_lc]  Error messagg
e Traceback (most recent call last):
 
  File "xxxxxxxxxxxxxxxxx", line 465, in modify_veth_container
    ipdb.routes.add(spec).commit()
  File "/usr/lib/python2.7/site-packages/pyroute2/ipdb/route.py", line 480, in cc
ommit
    raise error
TypeError: can't pickle Value objects

Python 2.7.5
python2-pyroute2-0.4.13-2.el7.centos.noarch

**Comment by ljluestc** [comment]
```

import logging
from pyroute2 import IPDB

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def modify_veth_container(veth_name, ip_address):
    try:
        with IPDB() as ipdb:
            # Create or modify the veth interface
            if veth_name not in ipdb.interfaces:
                logger.info(f'Creating veth: {veth_name}')
                veth = ipdb.create(veth_name, kind='veth')
                veth.address = ip_address  # Set IP address
                veth.commit()
            else:
                logger.info(f'Modifying veth: {veth_name}')
                veth = ipdb.interfaces[veth_name]
                veth.address = ip_address  # Set IP address
                veth.commit()
            
            # Add route
            route_spec = {
                'dst': '0.0.0.0/0',  # Example destination
                'oif': veth.index,  # Output interface index
                'scope': 'global'
            }
            logger.info(f'Adding route: {route_spec}')
            ipdb.routes.add(route_spec).commit()

    except Exception as e:
        logger.error("Error modifying veth container", exc_info=e)

# Example usage
modify_veth_container('veth0', '192.168.1.1')
```
