### ISSUE TITLE
Regression: exception classes not working with pyroute2.minimal

### ISSUE THREAD

**Issue by liske** [svinota/pyroute2#847]
Hi,

this is a follow-up to #845 tested with pyroute2 0.6.5

Script:

```python
from pyroute2 import IPRoute
from pyroute2.netlink.exceptions import NetlinkError

ipr = IPRoute()

try:
    links = ipr.get_links(666)
except NetlinkError as err:
    print('lookup failed: {}'.format(err.args[1]))
```

With `pyroute2` installed:
```console
$ ./xcpt.py 
lookup failed: No such device
```

With `pyroute2-minimal` installed:
```console
$ ./xcpt.py 
Traceback (most recent call last):
  File "/home/thomas/src/ifstate/./xcpt.py", line 9, in <module>
    link = next(iter(ipr.get_links(666)), None)
  File "/home/thomas/src/ifstate/.venv2/lib/python3.9/site-packages/pr2modules/iproute/linux.py", line 286, in get_links
    result.extend(self.link(cmd, **kwarg))
  File "/home/thomas/src/ifstate/.venv2/lib/python3.9/site-packages/pr2modules/iproute/linux.py", line 1436, in link
    ret = self.nlm_request(msg,
  File "/home/thomas/src/ifstate/.venv2/lib/python3.9/site-packages/pr2modules/netlink/nlsocket.py", line 391, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/home/thomas/src/ifstate/.venv2/lib/python3.9/site-packages/pr2modules/netlink/nlsocket.py", line 882, in nlm_request
    for msg in self.get(msg_seq=msg_seq,
  File "/home/thomas/src/ifstate/.venv2/lib/python3.9/site-packages/pr2modules/netlink/nlsocket.py", line 394, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/home/thomas/src/ifstate/.venv2/lib/python3.9/site-packages/pr2modules/netlink/nlsocket.py", line 719, in get
    raise msg['header']['error']
pr2modules.netlink.exceptions.NetlinkError: (19, 'No such device')
```

**Comment by svinota** [comment]
please use `from pyroute2 import NetlinkError` in both cases
