### ISSUE TITLE
Import error on Windows

### ISSUE THREAD

**Issue by nehaljwani** [svinota/pyroute2#851]
```
>>> import win_inet_pton
>>> import pyroute2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\path\to\prefix\lib\site-packages\pyroute2\__init__.py", line 73, in <module>
    loaded = entry_point.load()
  File "\path\to\prefix\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "\path\to\prefix\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "\path\to\prefix\lib\site-packages\pr2modules\netlink\diag\__init__.py", line 3, in <module>
    from socket import AF_UNIX
ImportError: cannot import name 'AF_UNIX' from 'socket' (\path\to\prefix\lib\socket.py)
```

**Comment by nehaljwani** [comment]
Closing in favour of https://github.com/svinota/pyroute2/issues/1334
