### ISSUE TITLE
brport command does not work under NetNS

### ISSUE THREAD

**Issue by hunbalazs** [svinota/pyroute2#864]
When using brport command via NetNS object I always get `pr2modules.netlink.exceptions.NetlinkError: (22, 'Invalid argument')`

Tested with this script:
``` python
import pyroute2
underlay = pyroute2.NetNS("underlay")
underlay.brport("set", index=4, mcast_flood=0) # index 4 exists in the test environment and is a bridge port
```

By using IPRoute after `ip netns exec <netns>` the script works

Linux kernel version: Linux ubuntu 5.4.0-90-generic
Python version: Python 3.8.2

**Comment by hunbalazs** [comment]
One thing I forgot to mention is that using brport on a NetNS object always causes this exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/network/venv/lib/python3.8/site-packages/pr2modules/iproute/linux.py", line 690, in brport
    ret = self.nlm_request(msg,
  File "/opt/network/venv/lib/python3.8/site-packages/pr2modules/netlink/nlsocket.py", line 391, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/opt/network/venv/lib/python3.8/site-packages/pr2modules/netlink/nlsocket.py", line 881, in nlm_request
    self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
  File "/opt/network/venv/lib/python3.8/site-packages/pr2modules/netlink/nlsocket.py", line 630, in put
    self.sendto_gate(msg, addr)
  File "/opt/network/venv/lib/python3.8/site-packages/pr2modules/remote/transport.py", line 244, in _gate
    raise ret['error']
AttributeError: 'IPBrPortRequest' object has no attribute 'allowed'
```
by modifying transport.py I could extract the original exception:
```
Traceback (most recent call last):
  File "/opt/network/venv/lib/python3.8/site-packages/pr2modules/remote/transport.py", line 177, in Server
    msg.load(pickle.loads(cmd['argv'][1]))
  File "/opt/network/venv/lib/python3.8/site-packages/pr2modules/netlink/rtnl/req.py", line 622, in __setitem__
    if key in self.allowed:
AttributeError: 'IPBrPortRequest' object has no attribute 'allowed'
```
the issue seems to be that `IPBrPortRequest` is not derived from `IPRequest` like other requests so after modifying netlink/rtnl/req.py like this:
```patch
-class IPBrPortRequest(dict):
+class IPBrPortRequest(IPRequest):
```
the above error arises.

I'm not an expert in python pickle magic but I think that somewhere between the main and netns process the request gets modified.
