### ISSUE TITLE
NDB() NetlinkError: (22, 'Invalid argument') when adding rules.

### ISSUE THREAD

**Issue by carloslockward** [svinota/pyroute2#893]
Found this issue trying to create rules on pyroute2 `0.6.9`

## Exception

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/snap/iotr-cr-sysmgr/current/lib/python3.8/site-packages/pr2modules/ndb/auth_manager.py", line 68, in guard
    return f(obj, *argv, **kwarg)
  File "/snap/iotr-cr-sysmgr/current/lib/python3.8/site-packages/pr2modules/ndb/objects/__init__.py", line 700, in commit
    raise e_i
  File "/snap/iotr-cr-sysmgr/current/lib/python3.8/site-packages/pr2modules/ndb/objects/__init__.py", line 689, in commit
    return self.apply()
  File "/snap/iotr-cr-sysmgr/current/lib/python3.8/site-packages/pr2modules/ndb/auth_manager.py", line 68, in guard
    return f(obj, *argv, **kwarg)
  File "/snap/iotr-cr-sysmgr/current/lib/python3.8/site-packages/pr2modules/ndb/objects/__init__.py", line 911, in apply
    raise e
  File "/snap/iotr-cr-sysmgr/current/lib/python3.8/site-packages/pr2modules/ndb/objects/__init__.py", line 876, in apply
    (self.sources[self['target']].api(self.api, method, **req))
  File "/snap/iotr-cr-sysmgr/current/lib/python3.8/site-packages/pr2modules/ndb/source.py", line 285, in api
    return getattr(self.nl, name)(*argv, **kwarg)
  File "/snap/iotr-cr-sysmgr/current/lib/python3.8/site-packages/pr2modules/iproute/linux.py", line 2244, in rule
    ret = tuple(ret)
  File "/snap/iotr-cr-sysmgr/current/lib/python3.8/site-packages/pr2modules/netlink/nlsocket.py", line 908, in nlm_request
    for msg in self.get(
  File "/snap/iotr-cr-sysmgr/current/lib/python3.8/site-packages/pr2modules/netlink/nlsocket.py", line 734, in get
    raise msg['header']['error']
pr2modules.netlink.exceptions.NetlinkError: (22, 'Invalid argument')

```

## Steps to reproduce

 - Try to create a rule like so: `ndb.rules.create({"src": "beef:db8::", "src_len": 112, "table": 50, "priority": 50}).commit()` 
    - This would be equivalent to: `sudo ip -6 rule add priority 50 from beef:db8::/112 lookup 50`

## Notes

I also tried to use IPRoute instead of NDB but got the same result. `ip.rule("add", **{"src": "beef:db8::", "src_len": 112, "table": 50, "priority": 50})`.

**Comment by svinota** [comment]
Thanks for the report, investigating

**Comment by svinota** [comment]
Sorry for the delay. You haven't specified the family:

```python
>>> ipr.rule('add', family=AF_INET6, src='beef:db8::', src_len=112, table=50, priority=50)
…

>>> ndb.rules.dump().filter(family=AF_INET6, priority=50)
('localhost', 0, 10, 0, 112, 0, 50, 0, 0, 1, 0, '', 'beef:db8::', '', 0, 50, 0, 0, 0, 0, 4294967295, 50, 0, '', 0, '', 0, 0, '', '')

>>> ndb.rules.create(family=AF_INET6, src='beef:db9::', src_len=112, table=50, priority=50).commit()
…

>>> ndb.rules.dump().filter(family=AF_INET6, priority=50)
('localhost', 0, 10, 0, 112, 0, 50, 0, 0, 1, 0, '', 'beef:db8::', '', 0, 50, 0, 0, 0, 0, 4294967295, 50, 0, '', 0, '', 0, 0, '', '')
('localhost', 0, 10, 0, 112, 0, 50, 0, 0, 1, 0, '', 'beef:db9::', '', 0, 50, 0, 0, 0, 0, 4294967295, 50, 0, '', 0, '', 0, 0, '', '')

>>> ndb.rules.dump().filter(family=AF_INET6, priority=50).format('csv')
'target','tflags','family','dst_len','src_len','tos','table','res1','res2','action','flags','dst','src','iifname','goto','priority','fwmark','flow','tun_id','suppress_ifgroup','suppress_prefixlen','table','fwmask','oifname','l3mdev','uid_range','protocol','ip_proto','sport_range','dport_range'
'localhost',0,10,0,112,0,50,0,0,1,0,'','beef:db8::','',0,50,0,0,0,0,4294967295,50,0,'',0,'',0,0,'',''
'localhost',0,10,0,112,0,50,0,0,1,0,'','beef:db9::','',0,50,0,0,0,0,4294967295,50,0,'',0,'',0,0,'',''
```

But the library could guess it from the address format, thus adding this functionality asap.
